### ISSUE TITLE
Edit/Snapping to Vector Tiles (Protobuf)

### ISSUE THREAD

**Issue by EliezerB123** [geoman-io/leaflet-geoman#1011]
Leaflet has some plugins for working with VectorTiles here: https://leafletjs.com/plugins.html#vector-tiles

But **none** of them appear to work with Geoman.

In this related issue: https://github.com/geoman-io/leaflet-geoman/issues/664 it seems that Geoman is incompatible with [Leaflet.VectorGrid](https://github.com/IvanSanchez/Leaflet.VectorGrid) . (Note: This isn't using protobuf, but it's using a VectorTile nonetheless.)

However, the only other Leaflet plugin for this, [Leaflet.VectorTileLayer](https://gitlab.com/jkuebart/Leaflet.VectorTileLayer), appears to work in a similar way, and therefore seems to have the same problem. Is this true? Perhaps there's a work-around? (JSFiddle: https://jsfiddle.net/Terrafire123/96b8yvwg/16/.)

If both plugins are incompatible, then what's the recommended method of using Geoman to work with **protobuf VectorTiles**?

Thank you!

**Comment by Terrafire123** [comment]
@Falke-Design Thank you for your reply!

> What do you want to achieve? 

Primarily, we need to be able to draw shapes using Geoman, and snap the Geoman shapes to the features of the VectorTile layer. (Though full support would of course be ideal.)

> And why do you need to have this tiles as protobuf?

This is simply what we're currently using. (I'm given to understand it's more performant.) I'm not certain, but it may be possible to convert to GeoJSON, if necessary.

**Comment by Falke-Design** [comment]
I updated Leaflet.VectorTileLayer and made it possible to create a L.Polyline out of the .pbf data: https://gitlab.com/Falke-Design/Leaflet.VectorTileLayer

New functions:
 - Options: 
   - `leafletLayerOptions`: applied to the L.Polyline
   - `visibleTypes`: Default `['svg']`. The Leaflet layer can displayed also: `['svg','leaflet']` or `['leaflet']`
 - `toLatLngs(map)`: returns the current LatLngs which are visible on the map

Important! If you get the LatLngs from a low zoom-level the latlngs are not exactly correct.

Here you can download the dist files: [dist.zip](https://github.com/geoman-io/leaflet-geoman/files/7359518/dist.zip)

My sample with your tiles:
```
  var vectorTileLayer = L.VectorTileLayer("https://api.maptiler.com/tiles/7db16e50-77d7-48ac-84f1-ae3a391e3ff1/{z}/{x}/{y}.pbf?key=8BjhptJnVjQEcCDbVjO8", {
      maxDetailZoom: 17,
    style: {
      className: "vectorlayer",
      fillColor: 'red',
      color: 'red'
    },
    leafletLayerOptions: {color: 'green', pmIgnore: true, snapIgnore: false}, // makes it snappable but not editable
    visibleTypes: ['svg','leaflet']
  });
```

You can also only use `leafletLayerOptions: {color: 'green'}` but then when you edit / move the layer it will be reset after zooming. So I suggest you to use `vectorTileLayer.toLatLngs()` and create your own polyline.

------

It would be nice if you have some other vector tiles for testing then I can make a Pull Request to the main Library. Also some polygon vector tiles would be nice.

**Comment by EliezerB123** [comment]
It works!! Wow.

A little feedback:
It gives a couple errors if I forget to include 
` visibleTypes: ['svg','leaflet'] `
(Apparently, the default **options.visibleTypes** don't appear to be working.)

And I also don't see the correct color unless I do **BOTH**
` style: {color:'#ff0000'} `
**AND**
` leafletLayerOptions: {color:'#ff0000'} `

But it seems to work perfectly, otherwise!

Thank you!!

I'll see what I can do about getting you more examples.
