### ISSUE TITLE
I want to know the algorithm/code that used to cut polygon into any shape because i want to port this functionality to flutter to be used in flutter map

### ISSUE THREAD

**Issue by mohammedX6** [geoman-io/leaflet-geoman#1025]
Like this one 

![63919728-a0246180-ca3f-11e9-8441-0c81004ebdd7](https://user-images.githubusercontent.com/24648104/140020639-de7811d9-8b8c-40d7-a1c1-e36d0422e833.gif)

**Comment by mohammedX6** [comment]
https://user-images.githubusercontent.com/2399810/63919728-a0246180-ca3f-11e9-8441-0c81004ebdd7.gif

**Comment by Falke-Design** [comment]
We are using this code:
```
export function difference(polygon1, polygon2) {
  const geom1 = getGeometry(polygon1);
  const geom2 = getGeometry(polygon2);

  const differenced = polygonClipping.difference(
    geom1.coordinates,
    geom2.coordinates
  );
  if (differenced.length === 0) return null;
  if (differenced.length === 1) return turfPolygon(differenced[0]);
  return turfMultiPolygon(differenced);
}
```
Using this library: https://github.com/mfogel/polygon-clipping

# NEXT TIME: ask for help and write it friendlier, if you want to use our code without searching through Geoman by your self ... We are not working for you, so don't say "I want"! Else I will close your next question without answering.

**Comment by mohammedX6** [comment]
I don't mean it all, sorry if I hurt you.
