### ISSUE TITLE
Drag mode tool doesn't work with Canvas

### ISSUE THREAD

**Issue by robcdd** [geoman-io/leaflet-geoman#1027]
After drawing some geometries on the map, any attempt to move them using the drag mode tool results in the map view moving instead of the intended geometry. This appears to be caused by the use of leaflet's canvas mode, because if you remove the `preferCanvas` property from the `MapContainer` component, the bug disappears.

https://stackblitz.com/edit/react-bbsept?file=src/App.js

Although I'm using `react-leaflet`, I basically assumed it's not a factor, and I realize I could be wrong about that. I haven't done the same test without react.

**Comment by Falke-Design** [comment]
Thanks for reporting this. Looks like it was not possible anymore because of adding better touch support for dragging. It is a bigger problem that has Leaflet self not get managed, but I try to make this possible again.

**Comment by Falke-Design** [comment]
@robcdd can you please test with the code from #1046 if it works for you

**Comment by rm-rf-etc** [comment]
@Falke-Design I cloned your branch, built it, and linked using yarn link, but I'm getting a lot of typescript errors when trying to build my project. Not yet sure how to fix it.

**Comment by robcdd** [comment]
@Falke-Design I cloned your branch, built it, and linked using yarn link, but I'm getting a lot of typescript errors when trying to build my project. Not yet sure how to fix it.

**Comment by Falke-Design** [comment]
Here are the builded files, does it work with them?
[dist.zip](https://github.com/geoman-io/leaflet-geoman/files/7696564/dist.zip)

**Comment by robcdd** [comment]
Yup! It works! Thank you!
