### ISSUE TITLE
Prevent cut tool from dissecting a polygon? 

### ISSUE THREAD

**Issue by roderickn-wt** [geoman-io/leaflet-geoman#1033]
I am starting here cause I am not sure if this is even an option that I can see, but is there a way to prevent the cut tool from dissecting a polygon into two? I have read through the options available and unless I don't understand what one of the options is correct I am not seeing a way to prevent dissecting.

**Comment by Falke-Design** [comment]
You can add to the layer the option `allowCutting: false`.

```
layer.pm.setOptions({allowCutting: false})
```
