### ISSUE TITLE
Get beginning and end of each line segment of Polyline

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#1037]
Hello:

Notice in this pic I have drawn a polyline containing two segments:

![GetBeginninAndEndOfLatLngs1](https://user-images.githubusercontent.com/5943189/141818263-dab401c3-b3cf-475d-a21a-1430221ef620.JPG)

...also notice the getLatLngs function returns an array containing three elements for the two segments I have drawn:

![GetBeginninAndEndOfLatLngs2](https://user-images.githubusercontent.com/5943189/141818426-35cf5b36-bd59-45bd-9c7b-932298e744c2.JPG)

as I see it:
- element 0 contains the Latlng for the beginning of the first segment
- element 1 contains the Latlng for the end of the first segment
- element 2 contains the Latlng for the end of the second segment

Is there a way for me to get the Latlng of the  _beginning_ of all of the segments that were drawn?

thank you

**Comment by Falke-Design** [comment]
You only need to loop through the latlngs and keep the endpoint as new start point:
```
var segments = [];
var currentSegment = [];
e.layer.getLatLngs().forEach((latlng)=>{
   currentSegment.push(latlng);
   if(currentSegment.length > 1){
       segments.push(currentSegment);
       currentSegment = [latlng];
   }
});
`´`
