### ISSUE TITLE
toggleControls() does not work as expected

### ISSUE THREAD

**Issue by AlbertoMCS** [geoman-io/leaflet-geoman#1040]
In my application when clicking the rectangle button the previous layer created and stored in a featureGroup are removed (that's the behaviour I want). 
I also created a button which toggle the Toolbar. 
This is the issue: when clicking the button to toggle the Toolbar and clicking again to make the Toolbar show up, when clicking the rectangle button the layers stored in featureGroup are not removed. It is like the rectangle button selection (in my case the class) is "restarted" when using toggleControls().

```
//Toggle button
$("#ToggleButton").click(function(){
mymap.pm.toggleControls();
});

//Toolbar
var options = {
    position: 'topright',
    drawMarker: false,
    drawCircleMarker: false,
    drawPolyline: false,
    drawRectangle: true,
    drawPolygon: true,
    drawCircle: false,
    editMode: false,
    dragMode: false,
    cutPolygon: false,
    drawControls: true,
    removalMode: false,
    deleteLayer: true,
    };

mymap.pm.addControls(options);

//Rectangle creation and stored in featureGroup
var jsn;
mymap.on('pm:create',function(e){
    featureGroup1.addLayer(e.layer);
    jsn = e.layer.toGeoJSON().geometry;
});

//Clicking in the rectangle button remove previous layers
$(".leaflet-buttons-control-button").click(function(){
featureGroup1.clearLayers();
```

**Comment by Falke-Design** [comment]
It is working as expected. The controls are removed and added again to the map. This means the DOM elements are also removed and recreated, which means that there are no click listeners on it which you have added to the previous DOM element. You need to add the click listener again after calling `toggleControls`:
```
$("#ToggleButton").click(function(){
  map.pm.toggleControls();
  if(map.pm.controlsVisible()){
      $(".leaflet-buttons-control-button").click(function(){
          ....
      }
  }
});
```

**Comment by AlbertoMCS** [comment]
Many thanks @Falke-Design it worked perfectly.
Cheers.
