### ISSUE TITLE
Leaflet-Geoman does not work with WebView after update Java

### ISSUE THREAD

**Issue by bluemin** [geoman-io/leaflet-geoman#1041]
I have verified Leaflet-Geoman (OS Windows 10) with WebView of the javaFX versions 15 ,16, 17,17.0.1,18-ea+5; JDK1.8.0_301. 
In all these cases mouse Events as dragging, Edit Circle,Edit Polygon 
as well as osm-map dragging do not work. 
Is it possible to adapt some Leaflet Codes as Draw.Circle, Edit.Circle, 
Drag.Layer to Java 1.8.0_301? Any help would be greatly appreciated. 
Thank you

**Comment by Falke-Design** [comment]
Would it be possible to set up a demo project, we never used Geoman with Java so we would need a start point

**Comment by bluemin** [comment]
I would like to transfer the jar-File. How I can it do?

![leaflet-geoman-webview-javafx-jre1 8 0_131](https://user-images.githubusercontent.com/20658513/143234921-6264de2e-df11-46b8-b79c-1a2bdb057737.png)
![leaflet-geoman-webview-javafx-2](https://user-images.githubusercontent.com/20658513/143234936-d1391888-784b-436d-9151-13b1a6050ff9.png)
![leaflet-geoman-browser-firefox](https://user-images.githubusercontent.com/20658513/143234938-1e19b63d-cece-4534-8b73-3ff1484e94ed.png)
![leaflet-geoman-webview-javafx](https://user-images.githubusercontent.com/20658513/143234940-4c074ed2-fedc-4d49-ac7d-610bb5b96127.png)

**Comment by Falke-Design** [comment]
Create a zip and then upload it here. Or try for example: https://www.transfernow.net/

**Comment by bluemin** [comment]
[LeafletGeoMan-WebView.zip](https://github.com/geoman-io/leaflet-geoman/files/7595568/LeafletGeoMan-WebView.zip)
Start the jar-file LeafletGeoMan-WebView.jar from console:
**java -jar LeafletGeoMan-WebView.jar** or by doppel-click
All features of Leaflet-geoman under jre 1.8.0_xxx (xxx < 291) work fine however them do not work under xxx>=291.

**Comment by bluemin** [comment]
[src.zip](https://github.com/geoman-io/leaflet-geoman/files/7595666/src.zip)

**Comment by Falke-Design** [comment]
Please write to my mail design.falke@gmail.com. Would it be possible to have a web meeting in the evening? We can speak German.

**Comment by Falke-Design** [comment]
After a meeting we found out, that it is a JavaFX but also Leaflet related problem. After switching to Leaflet 0.7.7 the dragging does work again

**Comment by bluemin** [comment]
Hallo Florian,

ich bedanke mich vielmals bei Dir für die Hilfe. OSM-Karte bewegt sich!
Ich teste leaflet weiter.

Schöne Grüße
Liudmila

Falke Design ***@***.***> schrieb am Mo., 29. Nov. 2021,
07:59:
