### ISSUE TITLE
The pm:update event is not fired after calling disable on a layer for the version 2.11

### ISSUE THREAD

**Issue by adamsjoe96** [geoman-io/leaflet-geoman#1042]
I've updated my version from 2.9.0 to 2.11. The pm:update event is not fired after calling disable on a layer. I downgrade to 2.9 and it works.

**Comment by adamsjoe96** [comment]
in addition to that in version 2.9 when the Edit mode is activated for polygons, the corner points are not visible.

**Comment by Falke-Design** [comment]
`pm:update` is only fired if the layer was edited. So it is not fired everytime. I found that `pm:update` is not fired only for markers, can you confirm that?

**Comment by adamsjoe96** [comment]
yes, I confirm that. It actually works well for polygons but I still can't see the corner points for polygons when edit mode is activated.

**Comment by Falke-Design** [comment]
> can't see the corner points for polygons

In the newest version?

**Comment by adamsjoe96** [comment]
Yes in the newest version 2.11.3

**Comment by Falke-Design** [comment]
> can't see the corner points for polygons

Can you please create an sample and confirm that this also happens here: https://jsfiddle.net/o1dwu2vg/
The corners looks good:
![grafik](https://user-images.githubusercontent.com/19800037/143924143-c740d8c8-cd20-4eb7-bbf8-b3b64937e07d.png)

**Comment by Falke-Design** [comment]
@adamsjoe96 ?

**Comment by adamsjoe96** [comment]
sorry for the delay. in the sample, it works correctly. I don't know why it still doesn't work for me. I'll test it again Tuesday.
