### ISSUE TITLE
Remove Layers button hook

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#1045]
Hello.  Is there any hook or listener code that can be used to do additional things when the "Remove Layers" button is clicked?

![geomanRemoveButtonQuestion](https://user-images.githubusercontent.com/5943189/144623138-b16a992e-39f5-4bfc-a42e-55b3f956cfb9.JPG)

Thank you

**Comment by Falke-Design** [comment]
You can listen on the [pm:globalremovalmodetoggled](https://github.com/geoman-io/leaflet-geoman#removal-mode9) event.
```
map.on('pm:globalremovalmodetoggled', (e)=>{
  console.log(e);
});
```

Or you listen on the [pm:buttonclick](https://github.com/geoman-io/leaflet-geoman#actions) event:

```
map.on('pm:buttonclick', function(e) {
  console.log(e)
});
```
