### ISSUE TITLE
markerStyle doesn't work

### ISSUE THREAD

**Issue by satrock1** [geoman-io/leaflet-geoman#1047]
hello, I'm trying to make a marker style by pulling data from json (https://github.com/geoman-io/leaflet-geoman/discussions/856), but it doesn't work for me, only polygon and line changes via 'style' works. But I just need a marker. Here is my jsfid https://jsfiddle.net/5arwg0k7/17/

**Comment by Falke-Design** [comment]
To style Marker or Circle you can't use the `style` option, you need to use [pointToLayer](https://leafletjs.com/reference.html#geojson-pointtolayer).

```
L.geoJSON(someGeojsonFeature, {
    pointToLayer: function (feature, latlng) {
        // here you would difference between marker and circle
        return L.marker(latlng,  {opacity: 0.5, draggable: true});
    }
}).addTo(map);
```

But this is a Leaflet "issue" no Geoman, so I will close this.
