### ISSUE TITLE
Delay Between Polyline Drawing Matching Cursor Movement

### ISSUE THREAD

**Issue by AlrightThen** [geoman-io/leaflet-geoman#1050]
When plotting a polyline, there is a delay between movement of the polyline and the position of the cursor. On slower computers this can cause a large delay of 1 second to occur at times.

**Comment by Falke-Design** [comment]
Can you please create a video or a gif. LICEcap is a nice Gif-making tool. And does it also happening here: https://jsfiddle.net/o1dwu2vg/
