### ISSUE TITLE
Question regarding optIn, markers and the edit mode

### ISSUE THREAD

**Issue by JanLoebel** [geoman-io/leaflet-geoman#1064]
Hi there,

today I've upgraded the leaflet-geoman from 2.9.0 to 2.11.4. Therefore, I had to change the ".initalize({ optIn: true })" to ".setOptIn(true)". Afterwards, I was surprised that snapping on my markers wouldn't work anymore. The markers are created without any reference to geoman, I only use it for lines or other polygons. However, If I set optIn to false, the snapping onto the marker position is working again. But then geoman can move and delete markers, which I don't want to.

Any ideas?

Thank you, best regards,
Jan

**Comment by Falke-Design** [comment]
> Snapping can be disabled for layers with the layer option snapIgnore: true. With snapIgnore: false it will be always snappable, also if pmIgnore is set.

Add the option `snapIgnore: false` to your markers while creation `L.marker([lat, lng], {snapIgnore: false}).addTo(map)`. We decided that `optIn: true` / `pmIgnore: true` means that it should not used by geoman, this includes snapping. But with the option `snapInfore: false` you can force geoman to include the layer again

**Comment by JanLoebel** [comment]
Thank you, sorry for misreading the documentation where you've already written that. Happy Christmas and thanks again!
