### ISSUE TITLE
Errors while dragging layer, with leaflet Canvas renderer

### ISSUE THREAD

**Issue by AndriyBroda** [geoman-io/leaflet-geoman#1069]
I've encountered some strange behavior while dragging the layer. That error occurs only when I use canvas `renderer` on the leaflet map. 

But it works fine with `preferCanvas: true` property though.

Here is the link: https://jsfiddle.net/etLsox8j/1/

![image](https://user-images.githubusercontent.com/44440418/147418630-49bbaa0d-c995-48c0-ba27-b45e587695e3.png)

**Comment by Falke-Design** [comment]
@AndriyBroda can you please check if the PR #1076 fix your issue. You can get the src from [here](https://florianbischof.net/leaflet/leaflet-geoman-canvas-drag.min.js)

**Comment by AndriyBroda** [comment]
@Falke-Design perfect, that fix works, nicely done 🙌
