### ISSUE TITLE
I want the source code/ or a hint for adding Vertex on Polygon

### ISSUE THREAD

**Issue by mohammedX6** [geoman-io/leaflet-geoman#1070]
I simply can not find anything on google, so by chance, I found a method called "addVertexOn" in this awesome library I could not resist porting this feature to my flutter app.
Thanks.

**Comment by Falke-Design** [comment]
Look into the source code which is shared in this github repository. https://github.com/geoman-io/leaflet-geoman/search?q=addVertexOn

The logic behinde is:
1. Calculate the middle position between P1 and P2 of the polygon
2. Add a marker at the middle position
3. if the action set in `addVertexOn` is fired on the marker (click, dblclick, ....), get the position of the marker and add it to the polygon
