### ISSUE TITLE
How to switch between two layers if one is selected at one time?

### ISSUE THREAD

**Issue by agishk** [geoman-io/leaflet-geoman#1073]
Hi,

I have layer control in which i select one layer as active. And then draw on the active selected layer. My issue exists on editing the drawn shapes/Output of the selected layers.
I found L.PM.Utils.findLayers(map) method to get the layers on map. But it get all the layers which are checked in the layer control. For instance, If i had an icon with each layer name in layer control which works as currently one selected at a time, then how can i edit the layer. Please reply ASAP.

**Comment by Falke-Design** [comment]
I don't really understand what you mean.

If you want to change the LayerGroup on which you draw, you can use: `map.pm.setGlobalOptions({ layerGroup: YOUR_LAYERGROUP });` together with the [overlayadd](https://leafletjs.com/reference.html#map-overlayadd) event on the map, which is fired by the layer control.

If you want to exclude layers from editing you can set `layer.pm.setOptions({ allowEditing: false });` on the layer or `pmIgnore: true`.

**Comment by agishk** [comment]
![lyr](https://user-images.githubusercontent.com/97210836/148366068-cd940954-6406-45ea-ab30-31b79e96e5c7.png)


Attached is the image, which has multiple layers. The layers will be already there on the map. I only need to switch between the layers by clicking on the pencil icon. yellow icon refers to the active icon and layer which is active. And gray icon refers to the inactive icon.I hope now you will understand what i mean to say

**Comment by Falke-Design** [comment]
after selecting a layer, call:
```
map.pm.setGlobalOptions({ allowEditing: false }); // disable editing for all layers
selectedLayer.pm.setOptions({ allowEditing: true}); // enable editing for the selected layers
```

**Comment by agishk** [comment]
Okay, Is there any method to get selected layer? Like the checkbox will be checked and i only need to select the pencil icon .As in my current code i am getting and setting the layer when clicked on pencil icon.
@Falke-Design

**Comment by Falke-Design** [comment]
With the [overlayadd](https://leafletjs.com/reference.html#map-overlayadd) event you can catch all layers which are enabled by the layer-control. Or you store your layers in an array and loop trough it and check if the layer is existing on the map with `map.hasLayer(layerFromArray)`

**Comment by agishk** [comment]
I have implemented, the following lines of code:
map.pm.setGlobalOptions({ allowEditing: false }); // disable editing for all layers
selectedLayer.pm.setOptions({ allowEditing: true}); // enable editing for the selected layers

But, now when i clicked on edit option in toolbar, I am unable to click on the layer and edit it. @Falke-Design

**Comment by Falke-Design** [comment]
Only the selectedLayer can be edited, all other layers are disabled. Can you please create a demo? https://jsfiddle.net/o1dwu2vg/

**Comment by agishk** [comment]
Demo would  not be possible as the code of lines are difficult to gather. I have already shared an image in the above comments as what actually i need to implement. @Falke-Design

**Comment by agishk** [comment]
When I clicked on pencil icon as shown in image above, i am setting the current layer in setEditableLayer function.
setEditableLayer = function(lyr) {  
   this.editableLayer = lyr;  
   if (lyr) {   
      switch (lyr.options.layerType) {
case 'cosmetic':  
this.map.pm.setGlobalOptions({ allowEditing: false,layerGroup: lyr });
 // disable editing for all layers 
lyr.pm.setOptions({ allowEditing: true}); 
// enable editing for the selected layers
break;

case 'edit':
this.map.pm.setGlobalOptions({ allowEditing: false,layerGroup: lyr });
lyr.pm.setOptions({ allowEditing: true}); 
break;
}
}

The above lines won't allow me to edit any layer. Can you please look into the issue.
@Falke-Design

**Comment by agishk** [comment]
@Falke-Design  Here is the demo in which we need to switch between the layer and edit on selected layer when clicked on radio buttons.
URL: https://jsfiddle.net/hoagies/u38rozg0/29/

**Comment by Falke-Design** [comment]
Ok there is a bug, which overwrites the layer options with them of the globaloptions.
Use following then it works:

```
function disableEditingForAllLayers() {
    L.PM.Utils.findLayers(map).forEach((value)=>{
        value.pm.setOptions({ allowEditing: false});
    });
}

this.map.pm.setGlobalOptions({ layerGroup: lyr });
disableEditingForAllLayers();
lyr.pm.setOptions({ allowEditing: true}); 
```

**Comment by agishk** [comment]
The works fine when we switch between the layers. Thanks.
If we need to set the default layer on page load, how can we do that?? @Falke-Design

**Comment by Falke-Design** [comment]
Do the same as in the click event:
```
this.map.pm.setGlobalOptions({ layerGroup: defaultLayer});
disableEditingForAllLayers();
defaultLayer.pm.setOptions({ allowEditing: true}); 
```

**Comment by agishk** [comment]
Tried but it didn't work.

**Comment by Falke-Design** [comment]
Check that all layers are loaded before you call the code

**Comment by agishk** [comment]
I have set my own layers style and features. But when i try to save the data then there are two features. for instance on circle marker, there are two features -> {"type":"Feature","geometry":{"type":"Point","coordinates":[8.069715,50.247795]} and 
Second -> {"type":"Feature","geometry":{"type":"Point","coordinates":[8.069715,50.247795]},"attributes":{"label":"hh","name":"hh","labelAlign":"rt"}};
Can you please tell me how to remove the default style for circle marker or any others? @Falke-Design

**Comment by Falke-Design** [comment]
This has nothing to do with Leaflet-Geoman anymore. 
I don't know your code and I don't know how you export your layers ... The `attributes` section normally does not exist. So you edit the circle somewhere and edit it to geojson. Check if you insert it twice.

**Comment by agishk** [comment]
Can you guide me if we need to make a dynamic label on circle maker click. and adding the style for them @Falke-Design

**Comment by Falke-Design** [comment]
With the `pm:create` event you can check if the circleMarker is created and then you can add a Tooltip to it:
```
map.on('pm:create',(e)=>{
   if(e.shape === 'CircleMarker'){
     e.layer.bindTooltip('My Label', {permanent: true, className: 'myHTMLClassForStyling'}).openTooltip();
   }
});
```

**Comment by agishk** [comment]
Let me elaborate more.
I open a div on CircleMarker click,which has some inputs like color of the label and a textbox for the dynamic label.
When i select the color and other things from div then click on the map to create it , the map should have the output .For intense, "testing". And testing string should be in red color. @Falke-Design

**Comment by Falke-Design** [comment]
You can set what ever you want with custom css class or with css-style in the html-text:

```
.customLabel{
	color: red;
	border: 2px solid #000;
}

var m = L.marker(map.getCenter()).addTo(map);

function setLabel(marker, text){
	marker.bindTooltip(text,{permanent: true, className: 'customLabel', direction : 'bottom', offset: [-15,25]}).openTooltip();
}

setLabel(m ,'testing');
```

Inline-Css:
```
function setLabel(marker, text){
	text = "<span style='color:green'>"+text+"</span>";
	marker.bindTooltip(text,{permanent: true, direction : 'bottom', offset: [-15,25]}).openTooltip();
}
setLabel(m ,'testing2');
```

**Comment by agishk** [comment]
![divStyle](https://user-images.githubusercontent.com/97210836/150277980-9d1973db-02a9-42fc-b801-480a6aa1470a.png)

The attached image has a div open with style properties, I want to show that properties which user will select form that div and then plot on the map by create event. I don't want to give inline CSS as my style properties will be purely dynamic. I hope now you will get a better understanding of this issue. 
Question:
How can i set the style for the features created? @Falke-Design
