### ISSUE TITLE
NodeJS engine version >= 16 specifier

### ISSUE THREAD

**Issue by claustres** [geoman-io/leaflet-geoman#1082]
Hi, first of all thanks for this module, which does a good job. I just want to highlight that this [recent commit](https://github.com/geoman-io/leaflet-geoman/commit/1a47ff13533aeefef90b734e7d2a485c0db5b182#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21) has broken our build, although it has been released as a patch. Indeed, you have added a specifier on the node engine version that does not allow to install the module with versions prior to 16.

Of course I understand NodeJS v16 should be the target version because it is the LTS version, but releasing such a change as a patch can probably raises some weird issues.

**Comment by codeofsumit** [comment]
@claustres good call out and apologies for that. It was meant as a way to streamline contributor versions - I actually wasn't aware this will affect users as well. I will revert this and release another patch version
