### ISSUE TITLE
Styling just 1 control button

### ISSUE THREAD

**Issue by AlbertoMCS** [geoman-io/leaflet-geoman#1086]
Hi, 
I created a custom button and I would like to apply some CSS just on it. When clicking the element in the browser to find out its class, I realise that all the buttons have the same class `leaflet-buttons-control-button`. Is there a way to select/access one single button to apply some CSS? 
Here my button:
```
mymap.pm.Toolbar.copyDrawControl('Rectangle', {
                  name: 'RectangleCopy',
                  block: 'custom',
                  onClick: () => {
                  //Whatever here
                  }
                });
```
Many thanks.

**Comment by Falke-Design** [comment]
You can add a `className`:

```
mymap.pm.Toolbar.copyDrawControl('Rectangle', {
                  name: 'RectangleCopy',
                  block: 'custom',
                  className: 'myCustomCSSClass',
                  onClick: () => {
                  //Whatever here
                  }
                });
```

**Comment by AlbertoMCS** [comment]
Thanks Falke-Design, but that class just seems to be modifying the icon inside the button not the button itself. I would like to make the button bigger. 
Look the screenshot below (I changed the colour to beige with the new class)
![image](https://user-images.githubusercontent.com/16774169/150685358-cfd07e4c-db33-40f0-bc98-b2a006b99df5.png)
Many thanks

**Comment by AlbertoMCS** [comment]
Hi, 
I do not need this capability anymore.
Many thanks.
