### ISSUE TITLE
Using my own buttons in my Application

### ISSUE THREAD

**Issue by AlbertoMCS** [geoman-io/leaflet-geoman#1087]
Hi, 
I am using my own set of buttons in my application. 
I have two questions: 
1 - is it possible to make a copy of a edit button (edit layer, remove and drag) following the same logic as draw buttons: 
Looking for something like the code below but for editing:
```
map.pm.Toolbar.copyDrawControl('Rectangle', {
  name: 'RectangleCopy',
  block: 'custom',
  title: 'Display text on hover button',
  actions: actions,
});
```
Something like: 
```
map.pm.Toolbar.copyEditControl('EditLayerMode', {
  name: 'EditLayerCopy',
  block: 'custom',
  title: 'Display text on hover button',
  actions: actions,
});
```
2 - I would like to implement with my own buttons the "remove last vertex" feature. Which is the function to do that? 
![image](https://user-images.githubusercontent.com/16774169/150704969-04b6f037-e06a-46f3-95e0-d2421070a06e.png)
Looking for something like this:

```
    $('#btnRemoveLastVertex').on('click', function() {
// Whichever function rules this capability. 
    }); 
    });
```
Many thanks!

**Comment by Falke-Design** [comment]
1. User `createCustomControl`:
```
// Click button -> toggle disabled
map.pm.Toolbar.createCustomControl({
  name: 'editLayers',
  block: 'custom',
  className: 'leaflet-pm-icon-edit xyz-class',
  title: 'Edit layers',
      afterClick: () => {
        map.pm.toggleGlobalEditMode();
      },
  toggle: true,
      actions: ['finishMode'],
});
```

2. You need to use a internal function
```
map.pm.Draw.Line._removeLastVertex();
```

**Comment by AlbertoMCS** [comment]
@Falke-Design many thanks for your answer.

Question number 1 worked very well. 

For the question number 2 I am getting the following:

![image](https://user-images.githubusercontent.com/16774169/151076406-2a6b8195-e370-47f1-bf2b-2d2ff98ef34c.png)
Am I missing something when implementing the internal function?
Here my code:

```
// Inherit from an Existing Control
    mymap.pm.Toolbar.copyDrawControl('Polygon', {
      name: 'PolygonCopy',
      block: 'custom',
      toggle: false,
    });

// Enable Polygon function
    $('#btnPolygon').on('click', function() {
      $( "#RemoveLastVertexDefineArea" ).prop( "hidden", false );
      defineAreaGroup.clearLayers();
      if (this.checked){
        mymap.pm.enableDraw('PolygonCopy', {
        snappable: true,
        snapDistance: 20,
        pathOptions:{color:"#FFBF00"}
        })
      } else {
        $( "#RemoveLastVertexDefineArea" ).prop( "hidden", true );
        mymap.pm.disableDraw('PolygonCopy', {
        snappable: true,
        snapDistance: 20,
        pathOptions:{color:"#FFBF00"}
        })
      }
      $('#btnCircle,#btnRectangle,#btnEdit,#btnMove').on('click', function() {
        $( "#btnPolygon" ).prop( "checked", false );
      }); 
    });

//Removal last Vertex onclick button
      $('#RemoveLastVertexDefineArea').on('click', function() {
        mymap.pm.Draw.Line._removeLastVertex();
      });
```
Many thanks,
Alberto

**Comment by Falke-Design** [comment]
You need to use `Line` for Polyline and `Polygon` for Polygon:
```
 mymap.pm.Draw.Line._removeLastVertex();

 mymap.pm.Draw.Polygon._removeLastVertex();
```

And it will throw an error if `enableDraw` is not active. You can check this with
```
mymap.pm.Draw.Polygon.enabled();
```

**Comment by AlbertoMCS** [comment]
HI Thanks for the answer. 
It was a very stupid mistake, 
I was using mymap.pm.Draw.Polygon._removeLastVertex();
but it had to be: mymap.pm.Draw.**PolygonCopy**._removeLastVertex(); instead as I am using a different instance.
Many thanks.

**Comment by hamish0361** [comment]
@AlbertoMCS  how about the action finish and cancle?
I can use  mymap.pm.Draw.Line._finish(); or mymap.pm.Draw. Polygon._finish(); and mymap.pm.Draw.Line._cancel(); or  mymap.pm.Draw. Polygon._cancel(). :(
Can you help me?
