### ISSUE TITLE
How to NOT toggle the toolbar when drawing is enabled programmatically

### ISSUE THREAD

**Issue by MarisaNat** [geoman-io/leaflet-geoman#1089]
I'm using the drawingtools for two purposes: 
1. "normal" drawing/editing on a layer to create features (triggered by the geoman toolbar)
2.  "drawing" a feature only to retrieve the coordinates = Selection tool. (triggered by non leaflet button) The feature is removed immediately after drawing and the geometry is used to find features in a database by geometric intersection. 

The issue is, when I enable one of the drawing tools by the "non leaflet button" programmatically by calling its enable function, the corresponding toolbar button is toggled, the context menu appears and I have two draw tools activated at the same time. E.g. the rectangle tool for getting the rectangle coordinates and the rectangle tool from the toolbar.

I had a look at the code but I could not find any setting which could pervent the toggling of the toolbar buttons when the function "enable" is called from any of the tools.

See L.PM.Draw.Rectangle Line 100 (The comment is exactly what I do NOT want)
![image](https://user-images.githubusercontent.com/77687551/150943364-c2195db3-ecd3-4336-9317-cb4d7759a06c.png)

So: Is there a trick how to prevent the toolbar toggling?

**Comment by MarisaNat** [comment]
Thanks for the super fast reply!
But I don't know if I could use it that way. As I said the button for the selection is a non leaflet button so it is not created by Toolbar.copyDrawControl().
I have my own instance of the L.PM.Draw (this.drawTool)  and I am calling this.drawTool.enable('Rectangle', this.drawOptions); when the user clicks on my button. Within this function the toolbar-buttons are toggled.  

For the first selection (drawing a rectangle) I can reset the toolbar toggling by calling this.map.pm.Toolbar.toggleButton('drawRectangle', false); right after I enabled the tool, but I have the option "continueDraw:true". As I have seen in the code, this options leads to the recall of the L.PM.Draw.Rectangle.enable() function which toggles the toolbar again.

**Comment by Falke-Design** [comment]
I suggest you to still create new instance of the Rectangle Control and then enable the new instance and not the existing one.
`this.drawTool.enable('RectangleCopy', this.drawOptions);`

**Comment by MarisaNat** [comment]
Hm, maybe I got it completely wrong. What I am doing is, I have a class rectangleSelection, circleSelection, pointSelection,etc. For each of these classes, when I instantiate them, I do this.drawTool = new L.PM.Draw(this.map); So rectangleSelection.drawTool is a new instance of L.PM.Draw, same for circle etc.. Then I create a button which will do the rectangle selection. On button click I call rectangleSelection.drawTool.enable('Rectangle', rectangleSelection.drawOptions); for the button which does the circleSelection it is circleSelection.drawTool.enable('Circle', circleSelection.drawOptions). But no matter which instance I use to enable the different tools, the enable function will always call this._map.pm.Toolbar.toggleButton(..) So as soon as a geoman toolbar is loaded to the map the enable function will toggle the buttons of this toolbar.

Back to your suggestion. Besides getting a new button in the toolbar which I do not want to have, isn't the called enable function the same as for the "normal" rectangle tool? so this._map.pm.Toolbar.toggleButton(..) is called anyway?

**Comment by Falke-Design** [comment]
Sorry I don't understand all what you want to explain and this is a very special usecase where I can't help you much.
Anyway look into this two samples (I can't do more):
https://jsfiddle.net/falkedesign/hz1wgdLb/

https://jsfiddle.net/falkedesign/qt9xpzvf/
