### ISSUE TITLE
Altitude value goes missing from dragged marker

### ISSUE THREAD

**Issue by mike16889** [geoman-io/leaflet-geoman#1096]
I have found that when editing a point/polyline/polygon that moved points loose the alt property on getLatLng(). this only happens for moved points, so if a point in a line is not moved, it retains the alt property.

I am assuming it happens on 'drag' of the marker as the position is updated, I have been having a look through the source but have not yet been able to find it.

I assume a simple as checking if the alt attribute exists on the original position and just copying it to the new position.

something like: 
```
if(typeof oldLatLng.alt !== 'undefined'){
	newLatLng.alt = oldLatLng.alt;
}
```

**Comment by Falke-Design** [comment]
Good catch! Will be fixed.

This is happening because we create a new LatLng object:
https://github.com/geoman-io/leaflet-geoman/blob/1fdc918fa39ffa84327fdf639fa75865168f716d/src/js/Mixins/Dragging.js#L345-L348

**Comment by mike16889** [comment]
Not surprised it was missed, Did not even know leaflet supported altitude until yesterday when I tested what would happen if I created a layer from GeoJSON that contains altitude in the coordinates.

I plan on using it in the wrong way as it is, I will be storing height there, not altitude, so an altitude of 1 will be 1m above ground. -0.6 will be 600mm below ground etc.
