### ISSUE TITLE
Toolbar interaction with a leaflet-canvas layer ?

### ISSUE THREAD

**Issue by jupadin** [geoman-io/leaflet-geoman#1101]
Hi there,

first thank you very much for this awesome plugin!!
I'm drawing around 1000 markers (with custom icons - png files) on a map, which results in low performance due to DOM and all the stuff.
That's why I just used the following leaflet-markers-canvas plugin:
https://github.com/francoisromain/leaflet-markers-canvas

However, now I'm not able to use your awesome toolbar any longer (like moving or removing these markers).
Is there any way to circumvent this circumstance ?

Thank you very much!!

If needed I - of course - would provide a jsfiddle.

**Comment by Falke-Design** [comment]
Hi,
i don't know if I get this work, but I can try it next week.

There are 3 other canvas marker plugins, can you please check if a other one will work for you. Your canvas plugin is archived and if it is possible we would like to support a plugin which is maintained.

And please create a jsfiddle

**Comment by jupadin** [comment]
Hi,

sorry for the late reply!
Yes, there are 3 other plugins:
1) https://github.com/eJuke/Leaflet.Canvas-Markers
2) https://github.com/lipton-ice-tea/leaflet-canvas-markers
3) https://github.com/francoisromain/leaflet-markers-canvas

I first used the first one since it looks pretty easy to understand but lacks some smooth update routine - somehow the icons are (re)drawn while the map is still moving / zooming.
Due to this, I switched to the third module, which does not have this "problem".

However, using all of them lacks the ability to move the drawn marker around with this awesome toolbar (see [jsfiddle](https://jsfiddle.net/zh4m10xg/1/)). (Sorry for not including the plugin as js-file but somehow I'm not able to include it as a file, so it's in front of the code :-(.

Regarding the maintenance of the plugin:
The last commit was on 26th November '21, so it seems like there is some maintenance and progress going on.

Any ideas where the problem might be and how to solve this ?
Thanks a lot in advance!!!

**Comment by Falke-Design** [comment]
With the attached script it is possible to drag the markers but:
 - Not working good with to much markers (always a problem with Geoman)
 - Touch is not supported
 - Only dragging is supported, no snapping or anything else

You need to include the script after importing `leaflet-markers-canvas`. Btw. here the cdn to the plugin `<script src="https://cdn.jsdelivr.net/gh/francoisromain/leaflet-markers-canvas@latest/dist/leaflet-markers-canvas.js"></script>`

And you need to set `preferCanvas: true` (and not like in the example prefer`e`Canvas):
```
var map = L.map('map', {
    preferCanvas: true,
  })
```

I will not dig into it more, because it is to much hacky.

[geoman-markers-canvas.js.txt](https://github.com/geoman-io/leaflet-geoman/files/8064262/geoman-markers-canvas.js.txt)

**Comment by jupadin** [comment]
Oh wow, awesome - thank you very much!!!!
Sorry for the typo!

Any chance that you can give me a hint how to implement that the remove button is also working for such markers ?
Otherwise the issue can be closed :-)

**Comment by Falke-Design** [comment]
To remove a marker with the remove button use this:

Replace
```
L.Marker.addInitHook(function(){
  this.on('pm:drag pm:dragend',(e)=>{
    this._renderer.parent._redraw(true);
  });
});
```
with:
```
L.Marker.addInitHook(function(){
  this.on('pm:drag pm:dragend',(e)=>{
    this._renderer.parent._redraw(true);
  });

  this.on('click',(e)=>{
    if(this._map && this._map.pm.globalRemovalModeEnabled()) {
      this._renderer.parent.removeMarker(this);
    }
  });
});
```
