### ISSUE TITLE
Circle drawing finishes as soon as it starts

### ISSUE THREAD

**Issue by wendrul** [geoman-io/leaflet-geoman#1115]
I'm adding the fiddle, but it will probably be useless (very trivial setup, does not recreate the error): https://jsfiddle.net/j1xp4L95/

The problem appears only in **_Safari_**, with a fresh setup of geoman, when one tries to draw a circle (or a square), after the initial click the circle is drawn at a very small size (as if one had clicked twice really fast). There is no window for the user to adjust the size of the circle. Using the adjusting tool to resize the circle does work, however.

This issue does not appear in chrome or firefox.
I am using a Macbook Pro with an M1 processor.

https://user-images.githubusercontent.com/53628737/155195983-448b2e18-267c-46c1-9c8f-d07154bd6880.mp4

**Comment by Falke-Design** [comment]
Hi,
please add to you map options `tap: false` this is a Leaflet bug with 1.7.1 see [here](https://stackoverflow.com/questions/65369083/popup-does-not-open-when-clicking-on-marker-safari/65369228?noredirect=1#comment124948610_65369228). But this will be fixed with Leaflet 1.8. 

```
var map = L.map('map', {
   tap: false,
   ...
});
```
