### ISSUE TITLE
 syncLayersOnDrag bug 

### ISSUE THREAD

**Issue by Spokt1** [geoman-io/leaflet-geoman#1119]
Good afternoon, please tell me, I ran into such a problem that in version 2.11.4 it became impossible to drag 1 polygon, but only a group. Couldn't you see [my example](https://codesandbox.io/s/sweet-snowflake-yx9l5p) . Thank you in advance

**Comment by Falke-Design** [comment]
The problem is `renderer: L.canvas(),`.

Will be fixed, thank you for reporting. As workaround you can use `preferCanvas: true`

**Comment by Spokt1** [comment]
Thank you for your answer and for the plugin in general

**Comment by Falke-Design** [comment]
Fixed with #1069
