### ISSUE TITLE
how to add to custom group?

### ISSUE THREAD

**Issue by clavijojuan** [geoman-io/leaflet-geoman#1121]
Hi,  I have a question about how to add a layer into custom group.

Example: 

I have created an custom draw control:

``` javacript
map.pm.Toolbar.copyDrawControl('Marker', { name: 'CUSTOM NAME' });
```
and then i have a L.GeoJSON added into application, so i want to add this new layer into the group "CUSTOM NAME".
The default function is add the layer to "marker" group because is based on type of geometry.

How can i do that?

Thanks.

**Comment by Falke-Design** [comment]
https://github.com/geoman-io/leaflet-geoman#options

You need to set the LayerGroup in the global options: `map.pm.setGlobalOptions({layerGroup: YOUR_LAYERGROUP})`

**Comment by clavijojuan** [comment]
Didn't work but i created the property like this:

```
layer.pm._shape = "CUSTOM NAME"
```

**Comment by Falke-Design** [comment]
It does work. Look into: https://jsfiddle.net/falkedesign/ohv2Lzy1/

But all new layers will be added to this LayerGroup then. So if you want to add different shape types to different layergroups you have to call `map.pm.setGlobalOptions({layerGroup: YOUR_LAYERGROUP})` after enabling draw. For example over the `pm:drawstart` event.

Else you can add the layer to a different group in the `pm:create` event:
```
map.on('pm:create', (e)=>{
   if(e.shape === 'CUSTOM NAME'){
     e.layer.addTo(YOUR_LAYERGROUP);
   }
});
```

**Comment by clavijojuan** [comment]
Ohh, thanks 👍
