### ISSUE TITLE
Problem with snap on ALT + TAB

### ISSUE THREAD

**Issue by RenaudAubert** [geoman-io/leaflet-geoman#1128]
Hi !
As mentionned in the [doc](https://github.com/geoman-io/leaflet-geoman#snapping) holding ALT disable snapping.

My problem is that when I press ALT + TAB to change the current window, snapping is disabled but when I focus again on the page with leaflet and geoman-leaflet snappinng is still disabled. I'm using the latest version (2.11.4) and I noticed a [fix ](https://github.com/geoman-io/leaflet-geoman/pull/999) was released in the previous version but I'm still having this issue.

Here's a [JSFiddle](https://jsfiddle.net/o1dwu2vg/)

**STEPS to reproduce**

1.  Draw a rectangle
2. Once rectangle drawn, select Draw Polygons. Snapping will work as usual
3. ALT+Tab to another window and then come back to the JSFiddle window, now snapping is disabled

I might hve missed it but if this is a wanted behaviour is there a way to have snapping but disable the geoman alt key event?
I have this implemented where I'm overriding `isAltKeyPressed` to always return `false`
```
map.pm.Keyboard.isAltKeyPressed = function () {
    return false;
};
```

EDIT: pressing ALT again re-enable snapping but I find this not ideal for our customers.

**Comment by Falke-Design** [comment]
Is working for me, I jumped away with alt+tab and back, also I tried to jump away and come with the mouse back but snapping is always working.
![snapping](https://user-images.githubusercontent.com/19800037/161528970-0d26d5ee-c4b2-4d56-9cd4-d597ba50a5dc.gif)


Can you please make a video of what you are doing or a step by step explaination when you use alt+tab, when mouse etc.

**Comment by RenaudAubert** [comment]
@Falke-Design Thank you for your quick reply.

Here's a video with the problem
![leaflet-geoman-bug](https://user-images.githubusercontent.com/15106918/161547571-7c983cf4-0e3c-4cf6-96f3-d2db82c40fe0.gif)

**Comment by Falke-Design** [comment]
This is only a problem with Chrome. Firefox is working as expected. Thank you.

**Comment by Falke-Design** [comment]
@RenaudAubert can you check if it works with Chrome 100 for you? I does work now with the latest Chrome version for me

**Comment by RenaudAubert** [comment]
@Falke-Design Hi! I have the latest Chrome version on Windows **100.0.4896.127** and the snapping problem is still happening.

**Comment by Falke-Design** [comment]
@RenaudAubert can you please check if  #1167 works for you.

**Comment by RenaudAubert** [comment]
@Falke-Design Hi! I checked on Chrome and Edge an it works great no more snapping problem. Thank you 🙏
