### ISSUE TITLE
Add enter to finishOn

### ISSUE THREAD

**Issue by owolfy** [geoman-io/leaflet-geoman#1145]
I am trying to cause a finish event by pressing enter. Enter does not appear as one of in finishOn valid options. Is it possible to add this feature? At this point I'm using an hacky way of Draw.Polygon._finishShape()

**Comment by Falke-Design** [comment]
Thank you for your suggestion. I will close this issue and add it to the Feature Request list. You can upvote the feature with 👍

Existing Feature Requests
