### ISSUE TITLE
Ability to edit/modify only some shape and remove only some other shape

### ISSUE THREAD

**Issue by SuperPat45** [geoman-io/leaflet-geoman#1147]
I have a complex case where some shapes that can be edited but not removed and, on the contrary, some can be removed but not edited.

Are-there any way to do this?

**Comment by Falke-Design** [comment]
Yes apply on the layer `allowRemoval: false` or `allowEditing: false`:
```
layer.pm.setOptions({allowEditing: false});
```

**Comment by SuperPat45** [comment]
thanks!
