### ISSUE TITLE
In removal mode, set cursor: not-allowed to all non-removable shapes

### ISSUE THREAD

**Issue by SuperPat45** [geoman-io/leaflet-geoman#1149]
In removal mode, all shape has the same pointer cursor, so we don't know which can be removed and which cannot without clicking.

It will be useful to show a not-allowed cursor on mouse hover non-removable shapes
(those having `allowRemoval:false` or `pmIgnore:true` options).

**Comment by Falke-Design** [comment]
I will add this to the Feature Requests.

You can do it by your self with adding following:
```
.not-allowed-cursor{
    cursor: not-allowed;
}

function setRemovalCursor(){
    var layers = map.pm.getGeomanDrawLayers();
    layers.forEach((layer)=>{
      var elem = layer.pm._getDOMElem();
      if(!map.pm._isRelevantForRemoval(layer)){
        L.DomUtil.addClass(elem, 'not-allowed-cursor');
      } else {
        L.DomUtil.removeClass(elem, 'not-allowed-cursor');
      }
    })
}

map.on('pm:globalremovalmodetoggled',setRemovalCursor);
setRemovalCursor();
```
