### ISSUE TITLE
Cannot install leaflet-geoman-free via bower

### ISSUE THREAD

**Issue by leslieli** [geoman-io/leaflet-geoman#1153]
Hi there,

I tried to install the `leaflet-geoman-free` with bower, but it failed.

The command is: 
`bower install @geoman-io/leaflet-geoman-free`
and returned error:
`ENOTFOUND Package @geoman-io/leaflet-geoman-free not found`

Also tried to add below dependency into `bower.json`
`"leaflet-geoman-free": "git+https://github.com/geoman-io/leaflet-geoman.git#2.12.0"`
and run 
`bower install`
It worked but no `dist` folder and no `leaflet-geoman.min.js` file which we need it in our project.

Could you please publish it to `bower` or commit the `dist/leaflet-geoman.min.js` to the repo?

Thanks.

**Comment by Falke-Design** [comment]
Please use npm or one of the [CDN](https://www.jsdelivr.com/package/npm/@geoman-io/leaflet-geoman-free)s. We don't support bower.
