### ISSUE TITLE
Feature request: new button to duplicate existing shapes

### ISSUE THREAD

**Issue by SuperPat45** [geoman-io/leaflet-geoman#1154]
I would need an option to add a button to duplicate existing shapes.

It could work like this:
You start by clicking on the shape you want to copy;
Then a clone of the shape would be created (with the same properties, color, line, stroke weight…) and its center would then follow the mouse cursor until you click where you want to put it.
Finally, fire a pm:duplicated event with the new and the original shape as parameter.
 
It will be necessary to add options to authorize or not which shape that could be duplicated.

**Comment by Falke-Design** [comment]
Thank you for your suggestion. I will close this issue and add it to the Feature Request list. You can upvote the feature with 👍 

[Existing  Feature Requests](https://github.com/geoman-io/Leaflet-Geoman/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22+sort%3Areactions-%2B1-desc)
