### ISSUE TITLE
Dragging layers is not possible on mobile devices

### ISSUE THREAD

**Issue by BaharWeb** [geoman-io/leaflet-geoman#1158]
Hi.
I am trying to drag layers while using mobile device but there is an issue with `_getPaneRenderer(layer.options.pane)` which is called from `_canvasTouchClick(e)` function 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/80047152/166209773-15aadbe1-31d8-4d15-a093-60423af415e8.png">

**Comment by Falke-Design** [comment]
Can you please share a demo https://jsfiddle.net/o1dwu2vg/

**Comment by BaharWeb** [comment]
this problem happens on mobile device when `preferCanvas `is set `true` 


https://jsfiddle.net/js02ykcx/

**Comment by BaharWeb** [comment]
Hi. I am wondering if there is a solution for this issue?
Thanks for the hardwork

**Comment by Falke-Design** [comment]
@BaharWeb can you please check if #1166 works for you

**Comment by BaharWeb** [comment]
> @BaharWeb can you please check if #1166 works for you

Yes it works perfect thanks for the fix
