### ISSUE TITLE
"listener not found" in console when using Leaflet 1.8.0

### ISSUE THREAD

**Issue by maxfelsher** [geoman-io/leaflet-geoman#1160]
See https://jsfiddle.net/qo1hj6dz/1/ for a JSFiddle. This uses Leaflet 1.8.0, calls `enableDraw('Rectangle')`, and adds a toolbar with some of the controls.

There's no apparent effect on user-facing functionality, but there are console warnings of "listener not found" in the following situations:

- When the cursor first enters the map on initial run (connected to the `enableDraw('Rectangle')`, I believe)
- When the second marker of the rectangle is placed, finishing the rectangle
- 4 times when clicking the "Edit Layers" control when a rectangle exists on the page
- 2 times every time a marker is moved to a new location in edit mode

Thanks for the great plugin! I hope this is useful in debugging the issue!

**Comment by agishk** [comment]
@maxfelsher Did you get a solution for this. As i am also facing the exact issue.

**Comment by agishk** [comment]
@Falke-Design @codeofsumit Can anyone help on this issue?

**Comment by Falke-Design** [comment]
Yes we are on it. But it is only a warning not a really issue.

**Comment by agishk** [comment]
> Yes we are on it. But it is only a warning not a really issue.

When can we expect for a future release, as need to remove the warnings from console.

**Comment by Falke-Design** [comment]
Earliest with the Leaflet 1.8.1 release, because then the required functions to prevent this warning are available

**Comment by Falke-Design** [comment]
Will be fixed with the next Leaflet Version https://github.com/Leaflet/Leaflet/pull/8234
