### ISSUE TITLE
Typescript incomplete definition `setGlobalOptions` ?

### ISSUE THREAD

**Issue by hoetmaaiers** [geoman-io/leaflet-geoman#1164]
When using the function `map.pm.setGlobalOptions` I am obliged to pass `snappingOrder` and `panes`. 

```typescript
map.pm.setGlobalOptions({ hideMiddleMarkers: true }); 
```

Might it be better to update the typing to:

```typescript
setGlobalOptions(options: Partial<GlobalOptions>): void;
```

This depend on the exact implementation of course. But if the new options are applied on top of the default ones I see no problem.

**Comment by Falke-Design** [comment]
What does `Partial` mean?

The implementation is the same as everywhere in Leaflet. Only the passed options are overwritten and the others are still available / applied

**Comment by Falke-Design** [comment]
@ryan-morris what do you think?

**Comment by ryan-morris** [comment]
@Falke-Design I agree with the suggestion. it's either that or we need to make all properties on `GlobalOptions` allow undefined. I think the `Partial<GlobalOptions>` is a cleaner approach

**Comment by Falke-Design** [comment]
@ryan-morris Thank you, your help is very useful for me!

**Comment by Falke-Design** [comment]
@hoetmaaiers can you please check if #1168 works for you
