### ISSUE TITLE
_coordBeforeEdit error

### ISSUE THREAD

**Issue by clavijojuan** [geoman-io/leaflet-geoman#1172]
Hi,

I'm trying to reset latlng node of polyline if snaps with specific layer when edit the line but have been some troubles with attribute "_coordsBeforeEdit" because it is displaced

![image](https://user-images.githubusercontent.com/57905996/169667184-483c0108-5095-4177-826d-a7606a6f5435.png)

The line is a geojson feature.

Can someone help me? Thanks

**Comment by Falke-Design** [comment]
Please share a demo

**Comment by clavijojuan** [comment]
> Please share a demo

here is demo:
https://clavijojuan.github.io/_coordBeforeEdit_demo/

try to edit the line to snap red point and then see the difference between origin and final position.

The source code is here:

https://github.com/clavijojuan/_coordBeforeEdit_demo

**Comment by Falke-Design** [comment]
Do something like that:

```
if(name === 'line') {
                layer._preLatlng = JSON.parse(JSON.stringify(layer.getLatLngs()));

                layer.on('pm:edit', (ed) => {
                  if(wrongSnap) {
                    layer.setLatLngs(layer._preLatlng);
                    layer.pm._initMarkers();
                  } else {
                    layer._preLatlng = JSON.parse(JSON.stringify(layer.getLatLngs()));
                  }
                });
}
```
