### ISSUE TITLE
Multipolygon delete individual polygon

### ISSUE THREAD

**Issue by benboughton1** [geoman-io/leaflet-geoman#1174]
I am attempting to edit multipolygons. So far it works pretty good. One question I have is is there any scope to delete individual polygon rather than the whole feature? 

I suppose I have two options, one is to convert the multipolygons to a bunch of single polygons, the other is a manual delete function. But I thought I would get others thoughts on this. 

Thanks for the great tool.

**Comment by Falke-Design** [comment]
Hi @benboughton1,
saddly it is not possible to use the default Geoman delete tool to "edit" multipolygons.
I will let this issue open for a few weeks, maybe someone has a solution for you, but after that I will close it.
