### ISSUE TITLE
AddControls is not defined when trying to add Toolbar after including the CSS and JS files via CDN

### ISSUE THREAD

**Issue by Pranav4399** [geoman-io/leaflet-geoman#1177]
I'm a beginner leaflet user trying to build a leaflet toolbar but facing the above error on using geoman. If this issue was already raised and closed, it'll be of great help to link that issue here and I can refer to that

**Comment by Falke-Design** [comment]
This looks pretty clear for me. Did you added the Geoman CSS & JS files before executing `map.pm.addControls()`? Else this error would not be shown.

Before calling `map.pm.addControls()` add following:
```
console.log(L.PM)
console.log(map.pm)
map.pm.addControls()
```

**Comment by Pranav4399** [comment]
Just now found what was the issue. I wrote the script tags in incorrect order lol. I'll close the issue.
