### ISSUE TITLE
Prevent polygon and polyline to disappear when right-clicking the last vertexes

### ISSUE THREAD

**Issue by SuperPat45** [geoman-io/leaflet-geoman#1185]
In edit mode, we can right-click on a vertex to remove it.

For polygon, if you right-click on the three last vertex, the shape disappear.
For polyline, if you right-click on the two last vertex, the shape disappear.

I think, leaflet geoman should prevent this.

**Comment by Falke-Design** [comment]
@SuperPat45 there is a option for this `removeLayerBelowMinVertexCount: false`
