### ISSUE TITLE
A "rectangle" can be rotated using the UI. Shouldn't it then it becomes "polygon" type?

### ISSUE THREAD

**Issue by designcomputer** [geoman-io/leaflet-geoman#1189]
I am having an issue with rectangles that are rotated using the UI's "Rotate Layers" control. The "layer.feature.properties.type" created using leaflet's "layer.toGeoJSON()" remains a "rectangle". Shouldn't it become a "polygon" type after a rectangle is rotated?

![Screenshot (210)](https://user-images.githubusercontent.com/25017723/176260169-f314f2e6-8b6f-47d6-9233-a39964b634d8.png)

**Comment by Falke-Design** [comment]
No because you rotate a rectangle and still want to edit it like a rectangle. (Keeping the sides while moving a corner point in sync)

You can change it to a polygon by your self.
```
layer.on('pm:rotateend',(e)=>{
   layer.remove();
   L.polygon(layer.getLatLngs()).addTo(map);
});
```

**Comment by designcomputer** [comment]
Thanks for the quick response @Falke-Design . 

I can see what you mean. Being able to edit a rotated rectangle as a rectangle is nice.

The problem I am having is when saving and loading a "rectangle".  I can't find the rectangleAngle value in the JSON structure created by leaflet's layer.toGeoJSON(). I also don't see a way to recreate a rotated "rectangle" manually other than as a "polygon".  I'm even having some trouble seeing the "pm:rotateend" you mentioned above.
