### ISSUE TITLE
How to call action draw polygon/ polyline/ Text , edit or remove in new button custom on the app?

### ISSUE THREAD

**Issue by hoangdangcodecomplete** [geoman-io/leaflet-geoman#1196]
Hi,
I'm currently making an app and using geoman I feel it's great.
Now what I'm doing is customizing the external buttons and calling actions inside the map like drawing shapes, deleting, and editing each shape.
Can you guide me to do it?
![Screen Shot 2022-07-06 at 10 30 02](https://user-images.githubusercontent.com/104552361/177462873-2e0075cd-21a7-43b8-a9b7-f5b66b13220f.png)

Thank you

**Comment by Falke-Design** [comment]
You need to enable drawing after clicking on a button: `map.pm.enableDraw('Text')`,  `map.pm.enableDraw('Line')`,  `map.pm.enableDraw('Polygon')`
