### ISSUE TITLE
Cannot create text in "Editor" tab

### ISSUE THREAD

**Issue by beatrochee** [geoman-io/leaflet-geoman#1197]
First of all, amazing app! It's exactly what I'm looking for to easily craft some GeoJSON, thank you for building it!

Secondly, I believe I may have found a bug relating to text creation. Apologies, attempted to reproduce in JSFiddle but this is only presenting itself in the "Editor" tab: https://geoman.io/geojson-editor

Steps to reproduce:

1. Click the "Text" control
2. Click anywhere on the map

Expected behavior: I see an editable text box
Actual behavior: I see a Marker

Here's a video I recorded of me reproducing it:

https://user-images.githubusercontent.com/18202038/177630193-fef47ab6-2503-414d-97b4-b76c41af871f.mov

**Comment by Falke-Design** [comment]
Thank you! We will fix this

**Comment by Falke-Design** [comment]
Fixed
