### ISSUE TITLE
Text is not scaled with Zoom functionality

### ISSUE THREAD

**Issue by Akshay-sheth** [geoman-io/leaflet-geoman#1204]
Hey,

First of all thanks for creating and maintaining such a good plugin. Really appreciate your efforts.

We are using Geoman to annotate image. When we add text on image, it is not scalling properly with zoom. Demo is attached. 

I want to reduce text-size when we zoom out. 

Is there any solution to scale text with zoom?

![text added](https://user-images.githubusercontent.com/40789066/178098560-dd081068-bdaf-4216-bbc1-59fc39249cfc.gif)

**Comment by Falke-Design** [comment]
There is currently no way.

Here you have some code to start:
```
var rootCSS = document.querySelector(':root');
map.on('zoom zoomend',(e)=>{
	if(layer){
  	var size = 18 * (map.getZoom() / 18); // you need a better step system per zoom
    console.log(size, map.getZoom())
  	rootCSS.style.setProperty('--fontSize', size+'px');
  	layer.pm._autoResize();
  }
});
```
```
:root{
  --fontSize: 20px;
}

.pm-textarea{
  font-size: var(--fontSize);
}
```
https://jsfiddle.net/13v2jfk7/

**Comment by Akshay-sheth** [comment]
Thank you @Falke-Design for quick response.
