### ISSUE TITLE
How to setGlobalOptions for a layer as layerGroup to perform update or delete actions for only one selected shape?

### ISSUE THREAD

**Issue by HoangDang1410** [geoman-io/leaflet-geoman#1205]
I'm trying so that when I select a layer, setGlobalOptions gives it something like below:

```
 map.on("pm:create", function (e) {
        e.layer.on("click", (x) => {
          map.pm.setGlobalOptions({ layerGroup: e.layer });
          disableEditingForAllLayers();
          e.layer.pm.setOptions({ allowEditing: true });
        });
      });


  const disableEditingForAllLayers = () => {
    L.PM.Utils.findLayers(map).forEach((value) => {
      value.pm.setOptions({ allowEditing: false });
    });
  }
```
Once that's done, I'll edit or delete just that one selected layer. And when selecting another image, the layerGroup will be changed to the selected layer.
My solution is like that however it fails I can't set the selected layer as globalLayer. So can you help me?
Thank you very much, have a good day.

**Comment by Falke-Design** [comment]
With the `layerGroup` option you define to which group the new drawn layers will be added, so this has no effect while editing.

I don't really understand what you want, but maybe `e.layer.pm.enable()` is after `e.layer.pm.setOptions({ allowEditing: true });` missing.

**Comment by hoangdangcodecomplete** [comment]
Thank you so much @Falke-Design !
