### ISSUE TITLE
New image element

### ISSUE THREAD

**Issue by SuperPat45** [geoman-io/leaflet-geoman#1207]
It will be awesome if geoman can have a button to draw an image (like tree, boat, arrow)
(not as a marker, but as a shape in the SVG layer because I need this image to zoom with the map).
I also need the ability to edit, resize and rotate images.

There is a leaflet plugin for an image draw/edition on which we could be inspired:
https://github.com/publiclab/Leaflet.DistortableImage
Except I need an option to not distort the image by just enlarge, shrink, rotate and always keeping aspect ratio.

**Comment by Falke-Design** [comment]
This is already possible with https://github.com/publiclab/Leaflet.DistortableImage you only need to enable the correct actions
