### ISSUE TITLE
Add custom attributes to control DOM button elements

### ISSUE THREAD

**Issue by slutske22** [geoman-io/leaflet-geoman#1217]
I am integrating this library with react-leaflet, and I want to be able to use react-tooltip on the buttons for a better user experience.  In order to do that, I need to be able to attach custom attributes to the dom elements which make the control buttons.  For example, here is the DOM for a geoman control with 3 drawing options (rectangle, polygon, circle):

<img width="550" alt="Screen Shot 2022-08-25 at 1 37 24 PM" src="https://user-images.githubusercontent.com/52637023/186787116-df7184db-a316-4aba-9322-e5a06d76ad67.png">

For each div with a class of `button-container`, or its child `<a>` element, I need to add these attributes:

- `data-tip`
- `data-for="geoman-rectangle-button"`

So the result would be something like this:

<img width="759" alt="Screen Shot 2022-08-25 at 1 47 29 PM" src="https://user-images.githubusercontent.com/52637023/186788082-eeae16c9-7f3f-4504-8161-877af53b9463.png">

If you want to know why, you can check out [react-tooltip](https://github.com/wwayne/react-tooltip).

How can I add these custom attributes?  Even the instructions for creating a custom control don't seem to give any method to add DOM attributes, not even an `id`. 

What would be the best tactic to do this?

**Comment by Falke-Design** [comment]
You can access the containers over `map.pm.Toolbar.buttons.drawRectangle.buttonsDomNode`
