### ISSUE TITLE
Updating marker with setLatLng before and after dragging

### ISSUE THREAD

**Issue by SellingSystems** [geoman-io/leaflet-geoman#1218]
I am allowing the user to both drag the marker and/or enter coords which are used in a setLatLng command. When I try to drag the marker after updating the position with a setLatLng it momentarilly snaps back to the position it was at before the setLatLng. I have tried using toggleEdit and disabling and enabling PM but it doesn't seem to help.

**Comment by itcareerswitch** [comment]
Sorry, I had StackOverflow open at the same time and put the question here by mistake.
