### ISSUE TITLE
I haven't found the specific method of action: removelastvertex

### ISSUE THREAD

**Issue by duping123456** [geoman-io/leaflet-geoman#1222]
I haven't found the specific method of action: removelastvertex，Can the author give me an answer, thank you

**Comment by Falke-Design** [comment]
We currently have no public method for it, but it will be implemented. Until then you can use the private method.

You need to use `Line` for Polyline and `Polygon` for Polygon:
```
 mymap.pm.Draw.Line._removeLastVertex();

 mymap.pm.Draw.Polygon._removeLastVertex();
```

And it will throw an error if `enableDraw` is not active. You can check this with
```
mymap.pm.Draw.Polygon.enabled();
```
