### ISSUE TITLE
markers that stay the same size at the zoom level you put them in

### ISSUE THREAD

**Issue by deadzora** [geoman-io/leaflet-geoman#1223]
Hey there I didn't see anything in the issues or anywhere in docs (I could just be blind) but I was wondering if there was any way for me to make it so that when I am zoomed in and place a marker, it scales along with the map as I zoom out. this might not even be some that the geoman plugin would deal with at all, either way please let me know if I should look else where or if there is a way for me to make it happen.

**Comment by Falke-Design** [comment]
Saddly there is no Marker in Leaflet which scales with the zoom (and then Geoman can not support this type). But you can try to use a `ImageOverlay`

**Comment by deadzora** [comment]
I actually found a way to do it, with the regular markers, thank you for the quick reply though I very much appreciate it.
