### ISSUE TITLE
I've got a problem with rotate

### ISSUE THREAD

**Issue by Keuta** [geoman-io/leaflet-geoman#1224]
Hi everyone !
I've got an issue with the rotate control.
I create a rectangle on my code with : 
`new_planche = L.rectangle([SW,SE]).addTo(map); `
Then I try to move my rectangle with the geoman controls, and that works fine, but if i try to then rotate the rectangle, I've got this error showing : 
`Polyline.js:223 Uncaught TypeError: Cannot read properties of null (reading '0')
    at i._projectLatlngs (Polyline.js:223:14)
    at i._projectLatlngs (Polyline.js:236:10)
    at i._projectLatlngs (Polyline.js:236:10)
    at i._project (Polyline.js:204:8)
    at i._updatePath (SVG.js:137:9)
    at i.redraw (Path.js:97:19)
    at i.setLatLngs (Polyline.js:78:15)
    at i._onRotate (leaflet-geoman.min.js:1:152985)
    at i.fire (Events.js:190:11)
    at i._onDrag (Marker.Drag.js:145:8)
_projectLatlngs @ Polyline.js:223
_projectLatlngs @ Polyline.js:236
_projectLatlngs @ Polyline.js:236
_project @ Polyline.js:204
_updatePath @ SVG.js:137
redraw @ Path.js:97
setLatLngs @ Polyline.js:78
_onRotate @ leaflet-geoman.min.js:1
fire @ Events.js:190
_onDrag @ Marker.Drag.js:145
fire @ Events.js:190
_updatePosition @ Draggable.js:192
requestAnimationFrame (async)
M @ Util.js:228
_onMove @ Draggable.js:178
c @ DomEvent.js:92
Ut @ DomEvent.Pointer.js:98
d @ DomEvent.Pointer.js:108`
![image](https://user-images.githubusercontent.com/63020398/188168724-71cc90e4-14e2-4cde-8256-55007ef126a7.png)
thank's for your help.

**Comment by Falke-Design** [comment]
Do you use a custom CRS or `L.Proj`? We don't have complete support for this
