### ISSUE TITLE
add text to shapes

### ISSUE THREAD

**Issue by GhadaAjimiDblog** [geoman-io/leaflet-geoman#1226]
Can you plz add a small text to shapes? Like a description that is inside the shape and visible when printing the map.
![image](https://user-images.githubusercontent.com/107615211/188458723-27935810-3b71-40f5-a846-75af1ffddec6.png)

**Comment by GhadaAjimiDblog** [comment]
Or make the popup visible when we print with easyPrint for exemple

**Comment by Falke-Design** [comment]
I add it to the Feature Requests. Can be upvoted with 👍 

> Or make the popup visible when we print with easyPrint for exemple

Needs to be done by your self or by easyPrint
