### ISSUE TITLE
Text and circle layers do not produce correct geojson

### ISSUE THREAD

**Issue by avisitor** [geoman-io/leaflet-geoman#1229]
When saving geojson for the geoman-created layers with text or circles, only a blank marker is saved, no circle and no text:

`var geojson = map.pm.getGeomanLayers( true ).toGeoJSON();`

```
0:
geometry: {type: 'Point', coordinates: Array(2)}
properties: {}
type: "Feature"
[[Prototype]]: Object
1:
geometry: {type: 'Point', coordinates: Array(2)}
properties: {}
type: "Feature"
[[Prototype]]: Object
length: 2
```

**Comment by Falke-Design** [comment]
You need to store the properties by your self. `toGeoJSON()` is a Leaflet function and not one from Geoman.
