### ISSUE TITLE
drawing a circle

### ISSUE THREAD

**Issue by monologuesa** [geoman-io/leaflet-geoman#1231]
When drawing a circle, vertices jump back to a certain point instead of stopping at the mouse position。

**Comment by Falke-Design** [comment]
Can you please share a video?

It is working fine for me. Please test out the demo: https://jsfiddle.net/o1dwu2vg/

**Comment by monologuesa** [comment]
> > 你能分享一个视频吗？
> > 它对我来说很好。请测试演示：[https ://jsfiddle.net/o1dwu2vg/](https://jsfiddle.net/o1dwu2vg/)
> 
>  ce135acf869d3ca6bf94da289861974a.mp4

did you encounter this situation

**Comment by Falke-Design** [comment]
Looks like you are going directly into edit-mode after drawing. Maybe you have implemented some thing in the `pm:create` event

**Comment by monologuesa** [comment]
> pm:create



> 看起来你在绘图后直接进入编辑模式。也许你已经在`pm:create`事件中实现了一些东西

You are right, I will directly enter the editing state after drawing, what do I need to do in pm:create so that the vertices will not be drawn on my mouse?

**Comment by monologuesa** [comment]
> Looks like you are going directly into edit-mode after drawing. Maybe you have implemented some thing in the `pm:create` event

You are right, I will directly enter the editing state after drawing, what do I need to do in pm:create so that the vertices will not be drawn on my mouse?

**Comment by monologuesa** [comment]
> Looks like you are going directly into edit-mode after drawing. Maybe you have implemented some thing in the `pm:create` event

Is there any method I need to call when I draw to achieve my purpose?

**Comment by Falke-Design** [comment]
I do not really understand what you want. The purpose of the edit mode is that is shows the vertices to make the modifications.

**Comment by monologuesa** [comment]
> I do not really understand what you want. The purpose of the edit mode is that is shows the vertices to make the modifications.

I just want the position of the outer circle point to be where my mouse clicked when the drawing is done
