### ISSUE TITLE
Support for indoor mapping

### ISSUE THREAD

**Issue by ppo-intelligentsystems** [geoman-io/leaflet-geoman#1232]
I need a product similar to leaflet to draw building elements (e.g. walls) and interior (e.g. a table (a square) on top of a background image uploaded by the user. Is that possible using leaflet? Further more I need to be able to create custom shapes, e.g. a quarter of a circle to represent a door and it opening direction.

**Comment by Falke-Design** [comment]
Yes it is possible to create indoor maps with Leaflet: [Non-geographical maps](https://leafletjs.com/examples/crs-simple/crs-simple.html)

You can draw / edit default shapes like Circle, Rectangle, Line, Polygon with Leaflet-Geoman, but we don't support custom shapes like semi-circles. You need to adapt Geoman for your usecase by your self.  

I will close this issue but you can still ask me questions here
