### ISSUE TITLE
Start vertex on center map when active tool polyline and polygon 

### ISSUE THREAD

**Issue by BlackNg11** [geoman-io/leaflet-geoman#1233]
Hello all.

First of all I want to say geoman is a excellent plugin for leafletjs.

The issue i want to ask:

- When i active draw polyline and polygon then center map have vertex, so can i remove this and behavior like rectangle only have vertex when move mouse.

Thank.

**Comment by Falke-Design** [comment]
Hi @BlackNg11,
can you please share a video what you mean. I don't understand it.

**Comment by Falke-Design** [comment]
![start-marker](https://user-images.githubusercontent.com/19800037/197031437-f1458db7-d524-4513-9e4d-8e2d104b34a0.gif)

I don't know if we want to hide the start marker. The tooltip is a important notifaction. I would also say we should change the rectangle to act like the polygon.

Anyway a workaround for you:

```
  map.on('pm:drawstart',(e)=>{
    if(e.shape === 'Line' || e.shape === 'Polygon') {
      map.pm.Draw[e.shape]._hintMarker.setLatLng([0, 0]);
    }
  })
```

**Comment by Falke-Design** [comment]
With `cursorMarker: false` you can hide the cursor marker completly. We will not hide it while enabling a draw mode.
