### ISSUE TITLE
Get Center Points After Rotation Done

### ISSUE THREAD

**Issue by erdoganabaci** [geoman-io/leaflet-geoman#1273]
I need center cooordinate in order to calculate rotated latitude longitude manually.

Is it possible to take center coordinate after rotation completed? @Falke-Design

**Comment by Falke-Design** [comment]
You can listen on the `pm:rotationend` event and then get the center by the default Leaflet way:

```
layer.on('pm:rotationend', (e)=>{
   var center = e.layer.getCenter();
   console.log(center);
});
```
