### ISSUE TITLE
Rotate Shape Manually

### ISSUE THREAD

**Issue by erdoganabaci** [geoman-io/leaflet-geoman#1275]
I want to rotate clockwise shape manually I try to implement with function but I got different result for single lat lng coordinate than mine. So which algorithm geoman is using in order to rotate coordinates in this function => `shapeLayer.pm.rotateLayer(45);` ?  @Falke-Design 

Here my custom function rotate base on center point 
```ts
function rotateCoordinate(coordinates: any, center: any, angle: number) {
    const radians = (Math.PI / 180) * angle;
    const cos = Math.cos(radians);
    const sin = Math.sin(radians);
    const rotatedLat =
        (coordinates.lat - center.lat) * cos -
        (coordinates.lng - center.lng) * sin +
        center.lat;
    const rotatedLon =
        (coordinates.lat - center.lat) * sin +
        (coordinates.lng - center.lng) * cos +
        center.lng;
    return { rotatedLat, rotatedLon };
}
```

input parameter rotateCoordinate function
```js
const coordinates = {
    "lat": 40.36328834091583,
    "lng": 27.685546875000004
}

const center = {
    "lat": 40.9052096972735,
    "lng": 29.498291015625043
}

const angle = 45
```

This is geoman coordinate after rotate 
```json
{
    "lat": 41.48973988680658,
    "lng": 27.711534378593587
}
```

This is my custom function rotated coordinate output
```json
{
    "rotatedLat": 41.9878483247729,
    "rotatedLon": 28.03005310407559
}
```

**Comment by Falke-Design** [comment]
We are using the rotation from https://github.com/w8r/Leaflet.Path.Transform

It looks like your rotation function doesn't contain the earth bearing, maybe this makes a difference.

**Comment by erdoganabaci** [comment]
So to make earth bearing manually it's not possible right ? I am curious about is it possible to make manually with my own function.

**Comment by Falke-Design** [comment]
I think if you google it you can find it, maybe not in javascript but you can port it to javascript or use ChatGPT for porting 😄

**Comment by erdoganabaci** [comment]
Yes you were right. We need to take into earth bearing distortion.First I didnt consider mercator projection then your previous commit about earth bearing it gives me light. I thought the rotation of the coordinates was just a simple rectangle or polygon rotation, but we have to consider the distortion of the world :) Here the article tells how the world is distorted [https://en.wikipedia.org/wiki/Circle_of_latitude](https://en.wikipedia.org/wiki/Circle_of_latitude) . I found really helpful implementation how we transform our rectangle or polygon point to latlng or latlng to point. [https://stackoverflow.com/questions/13512141/google-maps-rotate-polygon](https://stackoverflow.com/questions/13512141/google-maps-rotate-polygon)

According to StackOverflow link I create rotate function and now I consider about earth distortion with latLngToPoint and  pointToLatLng. If you want to implement these transformation you can follow this beneficial link => [http://www.movable-type.co.uk/scripts/latlong.html](http://www.movable-type.co.uk/scripts/latlong.html)
