### ISSUE TITLE
Unwanted rotation not from center point on small rectangle

### ISSUE THREAD

**Issue by Mushr0000m** [geoman-io/leaflet-geoman#1281]
I'm using Leaflet 1.9.3 with Leaflet-geoman 2.13.1 and for some weird reason when rotating a small rectangle (less than 2 meter) the rotation is not from the center point, it's working on large rectangle. It looks like this : 

https://user-images.githubusercontent.com/5532323/211056591-b421cde3-af54-4e16-9687-af2bb1a03310.mov

You can reproduce the issue here https://jsfiddle.net/y0x2e3wk/ just create a very small rectangle on max zoom and try to rotate it. I updated the base jsFiddle to use the latest Leaflet version, the base one uses v1.6.0, here is the v1.9.3

**Comment by Falke-Design** [comment]
Thank you for reporting this issue. This is a [bug](https://github.com/Leaflet/Leaflet/issues/8783) in the Leaflet center calculation. Will be fixed in Leaflet 1.9.4.

**Comment by Falke-Design** [comment]
[Leaflet 1.9.4](https://github.com/Leaflet/Leaflet/releases/tag/v1.9.4) with the fix is released
