### ISSUE TITLE
Start the draging programmatically on layers

### ISSUE THREAD

**Issue by Philip2809** [geoman-io/leaflet-geoman#1282]
Hey!

Is there any way I can start the "dragging" of polygons programmatically? I want to add a copy paste feature and when you press paste I want it to "stick" to your mouse, without the user having to hold down, and when they press the mouse button it places the polygon. I was able to make my own little script for the circles but polygons have multiple corners and they can be nested... 

I tried to use dig a bit in the source code but sadly was not able to get it to work. Any way it would be possible to start the dragging programmatically or if it would be possible to expose a function where you can do that? Another fun feature that I would like but not needed, is to add a rotation handle to the normal markers so that they can be rotated as using L.RotatedMarker you can just add a rotationvalue and it automatically rotates the picture.

Best Regards
Philip Magyar

**Comment by Falke-Design** [comment]
Take a look into our `moveCoords` function. You need to define a `deltaLatLng` with the values how much in each directions the coords should be moved. You can get this in a way like this:
```
    const deltaLatLng = {
      lat: latlng.lat - this._tempDragCoord.lat,
      lng: latlng.lng - this._tempDragCoord.lng,
    };
```

https://github.com/geoman-io/leaflet-geoman/blob/d11cafd347fa18d7f913bb2699dcb0b3d90b21a1/src/js/Mixins/Dragging.js#L347-L366

And the set the coords to the layer:
```
layer.setLatLngs(moveCoords(layer.getLatLngs()));
```

**Comment by Philip2809** [comment]
Thank you, this works perfectly!
