### ISSUE TITLE
Prevent Intersection With Shapes

### ISSUE THREAD

**Issue by Grey41** [geoman-io/leaflet-geoman#1284]
Hello, this is a very cool library. I am aware that the `allowSelfIntersection` option prevents intersection while drawing. Is there a way to prevent polygons from intersecting with each other?

You can use the `snapIgnore` option to ignore snapping on a shape. If a similar feature doesn't exist already, you could add `allowIntersection` option to prevent or allow intersection with other shapes.

![Screenshot 2023-01-09 at 09 17 05](https://user-images.githubusercontent.com/85015029/211277401-41f07e5b-87a0-4b6b-bc54-60734f8e74e8.png)

**Comment by Falke-Design** [comment]
I close this issue and add it to the `Feature Requests`. You can upvote it with a 👍

**Comment by skywalk49** [comment]
Good！I need  it
