### ISSUE TITLE
How can I edit rectangle on Cypress ?

### ISSUE THREAD

**Issue by erdoganabaci** [geoman-io/leaflet-geoman#1286]
I want to edit my rectangle in cypress but how can I do that? @Falke-Design 

First I created a rectangle 

```js
 cy.get("[data-testid=map-div_0]")
       .click(200, 200)
       .click(400, 350);
```

then I try to edit it doesn't work as I want 

```js
cy.get("[data-testid=map-div_0] .leaflet-interactive")
      .eq(1)
      .trigger("mousedown", { screenX: 200, screenY: 200 })
      .trigger("mousemove", { screenX: 250, screenY: 250 })
      .trigger("mousemove", { screenX: 300, screenY: 300 })
      .trigger("mouseup");
```

**Comment by Falke-Design** [comment]
You can try to use [Prosthetic-Hand](https://github.com/Leaflet/prosthetic-hand):

```
 it('keeps alt in LatLng while dragging', (done) => {
    cy.window().then(({ map, Hand }) => {
      const handMarker = new Hand({
        timing: 'frame',
        onStop: () => {
          const marker = map.pm.getGeomanDrawLayers()[0];
          expect(marker.getLatLng().alt).to.eq(10);
          done();
        },
      });
      const toucherMarker = handMarker.growFinger('mouse');
      toucherMarker
        .wait(100)
        .moveTo(150, 240, 100)
        .down()
        .wait(500)
        .moveTo(170, 290, 400)
        .up()
        .wait(100);
    });
  });
```

If you are creating tests outside of Leaflet-Geoman you need to add a few adjustments:
https://github.com/geoman-io/leaflet-geoman/blob/d11cafd347fa18d7f913bb2699dcb0b3d90b21a1/cypress/support/index.js#L57-L92

**Comment by erdoganabaci** [comment]
I tried to use native event and cypress real click but still doesn't mousedown vertex points. I want to mouse down upper left then move to center and then I want to mouse up. Is there any alternative way to do it? @Falke-Design 

![Screen Shot 2023-01-10 at 01 44 27](https://user-images.githubusercontent.com/43154455/211437186-176b02c1-4000-4992-942f-eccc2567d1af.png)

Cypress real event usage in this library but doesn't click I guess geoman doesn't listen to real event? ![Real Event Library] => https://github.com/dmtrKovalenko/cypress-real-events

```js
 cy.get(".cloned-shape")
    .realMouseDown({ position: "topLeft" })
    .realMouseMove(10, 10, { position: "center" })
    .realMouseUp({ position: "center" });
```

I also tried alternative dispatch events simulate mousedown,mousemove, mouseup for drag drop but still doesnt click left corner of shape

```js
    cy.window().then((win) => {
                    cy.get(".cloned-shape").then((el) => {
                        dragElementNative(
                            el,
                            { xMoveFactor: 6, yMoveFactor: -3 },
                            win
                        );
                    });
                });
```  

here the function =>

```js
function dragElementNative(
    element: JQuery<HTMLElement>,
    obj: MoveFactor,
    win?: Cypress.AUTWindow,
    shiftKey?: boolean
): void {
    // Get the raw HTML element from jQuery wrapper
    const container = element.get(0);
    const rect = container.getBoundingClientRect();
    // Position is the position with respect to the element passed to the function
    // Default position is 2 which is the center of the element(e.g., map, div)
    let position: number = 2;
    if (obj.position) {
        position = obj.position;
    }
    const center = {
        x: rect.left + rect.width / position,
        y: rect.top + rect.height / position
    };

    // Start dragging from the center of the map
    cy.log("mousedown", {
        clientX: center.x,
        clientY: center.y
    });
    container.dispatchEvent(
        new MouseEvent("mousedown", {
            clientX: center.x,
            clientY: center.y,
            view: win,
            shiftKey: !!shiftKey,
            bubbles: true
        })
    );

    // Let Leaflet know the mouse has started to move. The diff between
    // mousedown and mousemove event needs to be large enough so that Leaflet
    // will really think the mouse is moving and not that it was a click where
    // the mouse moved just a tiny amount.
    cy.log("mousemove", {
        clientX: center.x,
        clientY: center.y + 5
    });
    container.dispatchEvent(
        new MouseEvent("mousemove", {
            clientX: center.x,
            clientY: center.y + 5,
            view: win,
            shiftKey: !!shiftKey,
            bubbles: true // important to add!! default value is false
        })
    );

    // After Leaflet knows mouse is moving, we move the mouse as depicted by the options.
    cy.log("mousemove", {
        clientX: center.x + rect.width * obj.xMoveFactor,
        clientY: center.y + rect.height * obj.yMoveFactor
    });
    container.dispatchEvent(
        new MouseEvent("mousemove", {
            clientX: center.x + rect.width * obj.xMoveFactor,
            clientY: center.y + rect.height * obj.yMoveFactor,
            view: win,
            shiftKey: !!shiftKey,
            bubbles: true // important to add!! default value is false
        })
    );

    // Now when we "release" the mouse, Leaflet will fire a "dragend" event and
    // the search should register that the drag has stopped and run callbacks.
    cy.log("mouseup", {
        clientX: center.x + rect.width * obj.xMoveFactor,
        clientY: center.y + rect.height * obj.yMoveFactor
    });
    requestAnimationFrame(() => {
        container.dispatchEvent(
            new MouseEvent("mouseup", {
                clientX: center.x + rect.width * obj.xMoveFactor,
                clientY: center.y + rect.height * obj.yMoveFactor,
                view: win,
                shiftKey: !!shiftKey,
                bubbles: true
            })
        );
    });
}
```

**Comment by Falke-Design** [comment]
It is not Geoman which makes the problem, it is Leaflet.

You need to pass `button: 1` in the mouse events, then the dragging will work:

```
  it.only('opens a map in a browser', () => {
    cy.toolbarButton('polygon').click();

    cy.get(mapSelector)
      .click(90, 250)
      .click(100, 50)
      .click(150, 50)
      .click(150, 150)
      .click(90, 250);

    cy.toolbarButton('edit').click();

    cy.get(mapSelector)
      .trigger('mousedown', 150, 150, {button: 1})
      .trigger('mousemove', 170, 170, {button: 1})
      .trigger('mouseup', 170, 170, {button: 1})
  });
```

**Comment by erdoganabaci** [comment]
Thank you very much for response edit mode works fine I can able click upper left using `button:1` but when I try to move rectangle using `button:1` it doesn't work however if i remove `button:1` it works moving the shape. So `button:1` suppose to be default option. What makes the difference if I add button:1 or remove it ? @Falke-Design 

This case doesn't work while moving shape if I add `button:1`
```js
  it.only('drag rectangle', () => {
    cy.toolbarButton('rectangle').click();

    cy.get(mapSelector).click(200, 200).click(400, 350);

    cy.toolbarButton('drag').click();

    cy.get('.leaflet-pm-draggable')
    .trigger('mousedown', 50, 50, { button: 1 })
    .trigger('mousemove', 100, 100, { button: 1 })
    .trigger('mouseup', 150, 150, { button: 1 });
  });

```
This case works without problem but why ?

```js
 it.only('drag rectangle', () => {
    cy.toolbarButton('rectangle').click();

    cy.get(mapSelector).click(200, 200).click(400, 350);

    cy.toolbarButton('drag').click();

    cy.get('.leaflet-pm-draggable')
    .trigger('mousedown', 50, 50)
    .trigger('mousemove', 100, 100)
    .trigger('mouseup', 150, 150);
  });

```

**Comment by Falke-Design** [comment]
@erdoganabaci the difference is, that for dragging the vertex marker, the Leaflet internal dragging is used. For dragging a layer we use a Leaflet-Geoman own function. 

Leaflets validation: 
https://github.com/Leaflet/Leaflet/blob/main/src/dom/Draggable.js#L91

Geoman validation: 
https://github.com/geoman-io/leaflet-geoman/blob/d11cafd347fa18d7f913bb2699dcb0b3d90b21a1/src/js/Mixins/Dragging.js#L179

Leaflet works with `button: 1` but Geoman checks if `button` is not higher 0. Replace `button` with `which: 1` then everything works.

**Comment by erdoganabaci** [comment]
Thank you for your quick response. `which:1` works for both of them without a problem. But there is an issue with using `which`. Currently which becomes a deprecated web standard and it will be removed future. If i add which:1 it will save a day but this is a temporary solution. Is it possible to remove `if check condition is dragging ?` or can you support `button:1` while dragging shape? [https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which) @Falke-Design 

[https://github.com/geoman-io/leaflet-geoman/blob/d11cafd347fa18d7f913bb2699dcb0b3d90b21a1/src/js/Mixins/Dragging.js#L179](https://github.com/geoman-io/leaflet-geoman/blob/d11cafd347fa18d7f913bb2699dcb0b3d90b21a1/src/js/Mixins/Dragging.js#L179)

![Screen Shot 2023-01-13 at 16 55 58](https://user-images.githubusercontent.com/43154455/212365796-f190bf30-e306-43c1-8c2f-0389e8dd57cb.png)

Btw will you update the test according to dragging, editing, rotate? or I can send a pull request so you can approve the cypress test to geoman. 

Currently,  if i use `which:1`, both drag and edit work but temporary solution saving day :)

```js
 it('drag rectangle', () => {
    cy.toolbarButton('rectangle').click();

    cy.get(mapSelector).click(200, 200).click(400, 350);

    cy.toolbarButton('drag').click();

    cy.get('.leaflet-pm-draggable')
      .trigger('mousedown', 50, 50, { which: 1 })
      .trigger('mousemove', 100, 100, { which: 1 })
      .trigger('mouseup', 100, 100, { which: 1 });
  });

  it('edit rectangle', () => {
    cy.toolbarButton('rectangle').click();

    cy.get(mapSelector).click(200, 200).click(400, 350);

    cy.toolbarButton('edit').click();

    cy.get(mapSelector)
      .trigger('mousedown', 200, 200, { which: 1 })
      .trigger('mousemove', 250, 250, { which: 1 })
      .trigger('mouseup', 250, 250, { which: 1 });
  });
```

**Comment by erdoganabaci** [comment]
Hi @Falke-Design, We were incorrect in our usage of which or button. When we use cy.trigger, it creates a default Event constructor. If we pass button: 0 or button: 1, properties such as clientX and clientY will not be added to the Event constructor. Upon examination of the cy.trigger parameters, I discovered the eventConstructor option and changed it to MouseEvent, which resolved the issue. Cypress tests with Leaflet now works correctly, and changing the event constructor in Cypress makes more sense.

```js
cy.get("#map").
.trigger("mousedown", 575, 371, {
eventConstructor: "MouseEvent",
force: true })
```
