### ISSUE TITLE
I want to display polygons index number on each point, using Leaflet Geoman. Can anyone help me how to do this?

### ISSUE THREAD

**Issue by ali-mozaffari** [geoman-io/leaflet-geoman#1292]
This image is an example of UI/UX in Figam which I should do the same in front.
![polygon points](https://user-images.githubusercontent.com/103691384/212708855-887445e7-e7e6-4274-b06b-2091333e0800.PNG)

I have read the existing polygons here, but I don't know how to display numbers above of each polygon break point.
![Capture](https://user-images.githubusercontent.com/103691384/212709011-82d219f9-0220-4b58-a74b-3fa213be4a19.PNG)

**Comment by Falke-Design** [comment]
This has nothing to do with Leaflet-Geoman, this is Leaflet self.

Just create a marker for each point on the polygon:
```
polygon.getLatLngs().flat(999).forEach((latlng)=>{
   var marker = L.marker(latlng).addTo(map);
});
```
or a Tooltip:
```
polygon.getLatLngs().flat(999).forEach((latlng)=>{
   var tooltip = L.tooltip(latlng, {content: 'Hello world!<br />This is a nice tooltip.'}).addTo(map);
});
```

**Comment by ali-mozaffari** [comment]
This is my component. Could you please help me to use your code here?


const GeomanUTM = ({stringPolygan, data}) => {
  const context = useLeafletContext();

  useEffect(() => {
    const leafletContainer = context.layerContainer || context.map;

    var multipolygon = L.geoJson(
      WKT.parse(`SRID=4326;${stringPolygan}`.split(';')[1]),
    );
    multipolygon.addTo(context.map);
    context?.map.fitBounds(multipolygon.getBounds());


    leafletContainer.pm.getGeomanLayers()?.map((layer, index) => {
      layer.setStyle({
        pmIgnore: false,
        color: '#E4E4E4',
        fillColor: '#E4E4E4',
        fillOpacity: 1,
      });
    });
  }, [context]);

  return null;
};

export default GeomanUTM;

**Comment by Falke-Design** [comment]
```
leafletContainer.pm.getGeomanLayers()?.map((layer, index) => {
      layer.setStyle({
        pmIgnore: false,
        color: '#E4E4E4',
        fillColor: '#E4E4E4',
        fillOpacity: 1,
      });

      if(layer.getLatLngs){
        layer.getLatLngs().flat(999).forEach((latlng)=>{
           var tooltip = L.tooltip(latlng, {content: 'Hello world!<br />This is a nice tooltip.'}).addTo(map);
        });
      }
    });
```

**Comment by ali-mozaffari** [comment]
Thank you so much man. you helped me.
