### ISSUE TITLE
vertexclick event not fired for circles

### ISSUE THREAD

**Issue by benjaminbenaisfamoco** [geoman-io/leaflet-geoman#1296]
Hi, I've noticed that the "pm:vertexclick" event is not fired when clicking a vertex of a circle shape.

```js
const layer = new L.Circle(coordinates);

layer.on('pm:vertexclick', (event) => {
  console.log('vertex clicked);
});
```

In this example the console.log is never displayed on the console.

It works well with Polygon so I'm not sure if I'm doing something wrong or if there is no vertexclick event on circle shapes.

**Comment by Falke-Design** [comment]
We haven't implemented this for Circles. I will think about it, if it makes sense to add it.

**Comment by Falke-Design** [comment]
Until then you can use this workaround:
```
map.on('pm:create', (evCreate) => {
  evCreate.layer.on('pm:enable',(evEnable)=>{
    if(evEnable.shape === 'Circle'){
      evEnable.layer.pm._helperLayers.eachLayer((helperLayer)=>{
        if(helperLayer instanceof L.Marker){
          helperLayer.on('click',(evClick)=>{
            console.log(evClick)
          })
        }
      })
    }
  })
});
```

**Comment by codeofsumit** [comment]
@benjaminbenaisfamoco @Falke-Design I think this is a great addition. We should have this event for all supported shapes. Added to the roadmap 👍 - we will take care of this.
