### ISSUE TITLE
How to show polygon area in generated pdf using "html2canvas"? 

### ISSUE THREAD

**Issue by ali-mozaffari** [geoman-io/leaflet-geoman#1297]
I am using "html2canvas" to generate pdf from HTML. It works for all html tags and styles except drawn polygon area.
here are the examples:
HTML view:
![1](https://user-images.githubusercontent.com/103691384/214551686-00c2aa16-40d9-42ef-9524-2d67b7dc9ef8.PNG)

PDF view:
![2](https://user-images.githubusercontent.com/103691384/214551729-19acbbc1-65ad-44e6-a803-dfcb9d4f6435.PNG)

this is the function that convert html to pdf:

```
export const createPDF = () => {
  const data = document.getElementById('utmPagePdf');
  html2canvas(data, {
    allowTaint: true,
    useCORS: true,
    crossOrigin: 'anonymous',
  }).then(canvas => {
    const imgWidth = 208;
    const pageHeight = 295;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;
    heightLeft -= pageHeight;
    const doc = new jsPDF('p', 'mm');
    doc.addImage(canvas, 'PNG', 0, position, imgWidth, imgHeight, '', 'FAST');
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      doc.addPage();
      doc.addImage(canvas, 'PNG', 0, position, imgWidth, imgHeight, '', 'FAST');
      heightLeft -= pageHeight;
    }
    doc.save('Downld.pdf');
  });
};
```

Please help me to solve this issue.

**Comment by Falke-Design** [comment]
This issue tracker is used for reporting bugs of Leaflet-Geoman and discussing new features. For questions on using Leaflet or Leaflet-Geoman, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
