### ISSUE TITLE
The response of editing massive point pages is too slow

### ISSUE THREAD

**Issue by raopengfei** [geoman-io/leaflet-geoman#1299]
I encountered the problem of a large number of dead points in page editing when using the latest **leaf-geoman** version. I tried to solve the problem in the demo and found that the **enableGlobalEditMode** method parameter passed
` options: {limitMarkersToCount: 20, allowSelfIntersection: false, allowSelfIntersectionEdit: false},`
However, the editing of the page is still very difficult. After the **performance** analysis of **Chrome**, the **hasSelfIntersection** method in the **L.PM.Edit.Line** file is too long. After the analysis of the code, this is the logic to judge the self intersection. It should be called after the **allowSelfIntersection** parameter  and **allowSelfIntersectionEdit** parameter. The writing method referring to the **_onMarkerDragStart** method is better than the **_onMarkerDragEnd** method, In addition, the **hasSelfIntersection** method is also called in its method, such as the **handleLayerStyle** method Please refer to the screenshot for the specific execution time. I think you should review the method call check and judgment.
My English is poor. I hope you can understand my description. Thank you.
![ME1674907951337](https://user-images.githubusercontent.com/22318761/215265850-5c55f71d-bdb7-4030-8564-b125dac9074a.png)
![ME1674907956858](https://user-images.githubusercontent.com/22318761/215265853-25ac653d-c788-4020-b81a-4704ce0207e1.jpeg)

**Comment by Falke-Design** [comment]
If I understand you correctly, you suggest to move the `hasSelfIntersection()` call into `_onMarkerDragStart`. We can't do this, because we need to check after moving a vertex, we need to check if there is now a intersection.

**But** I think we should calculate self intersection only if `allowSelfIntersection` is `true`. I will create a fix in the next days.

**Comment by raopengfei** [comment]
Thank you for your reply. Your last remark is correct. Before calling the **hasSelfIntersection** method, you need to check that the parameter **allowSelfIntersection** is **true**, but this is not the case in the **_onMarkerDragEnd** method and the **handleLayerStyle** method. Under multi-point conditions, it can reduce a lot of performance overhead.

**Comment by 905807873** [comment]
I have confirmed that the allowSelfIntersection parameter is true. The current page has tens of thousands of points. When the editing function is called, the animation cannot run smoothly, and the editing function is also affected by the performance problem 

https://github.com/user-attachments/assets/3ca09676-a9bf-494c-acd7-4b9dbffbef1b

**Comment by 905807873** [comment]
I've found a workaround for this, {allowSelfIntersection: true, snappable:false }  The edit function allows to pick up the vertices of other layers by default, although it is helpful to edit, but when the number of layers is too large, it will lead to too much calculation, snappable parameter can be changed to false, thank the author for providing the tool, thank you

**Comment by raopengfei** [comment]
Optimizing this code can significantly improve the performance of editing massive amounts of line and surface data. As I mentioned in the screenshot above, `hasSelfIntersection ` will take more than 8 seconds to execute, severely blocking the browser's rendering. `Options. allSelfIntersectionEdit=false` should no longer be used for judging self intersection logic. The root cause of the problem is the lack of effective adjustment of the order of judgment conditions in _onMarkerDragEnd. 
![image](https://github.com/user-attachments/assets/2c4024e4-ea7f-4a85-b214-31f4768d79e4)
You can rudely add a judgment in the `hasSelfIntersection `method to solve it
![image](https://github.com/user-attachments/assets/d112f1e9-a0f0-4876-8057-a64c72ec632b)
We hope it will be helpful to you.

**Comment by edwh** [comment]
I came across this issue because I was moving to geoman and seeing very slow performance - about ten seconds to add a new vertex.

The workaround above from @905807873 was very helpful - everything becomes fast.  The `snappable` part does seem to be necessary.

But it still means that for me the `allowSelfIntersection` option isn't usable - which is a shame, because it would be very useful.  @Falke-Design, is there any work planned to improve the performance here?

**Comment by Falke-Design** [comment]
@edwh if you see some improvements which can be done in the code, feel free to submit a PR

**Comment by edwh** [comment]
@Falke-Design Completely fair.  I'm new to geoman, but once I've found my feet I'll see if I can figure out why it's slow.  It looks like you're using turf, so the algorithm should be fine.
