### ISSUE TITLE
Map is not draggable after adding a text

### ISSUE THREAD

**Issue by lmachens** [geoman-io/leaflet-geoman#1300]
Hey 👋,

I tried out the text layer functionally and really like it.
But after adding a text, my map is not draggable anymore.

The same issue is reproduceable on https://geoman.io/leaflet-geoman.

Am I missing something?

![draggable](https://user-images.githubusercontent.com/10058950/215443351-f4a9b685-88ae-4d96-8c2f-b578afa2c12b.gif)

As workaround, I set `map.dragging.enable()` after using the tool.

**Comment by Falke-Design** [comment]
Thank you for reporting! Will be fixed in #1302
