### ISSUE TITLE
How to hide marker on mouse move in text marker

### ISSUE THREAD

**Issue by agishk** [geoman-io/leaflet-geoman#1305]
I have a text marker and on mouse cursor move I have shown some dynamic text.  Along with text there is a blue icon coming. I want to hide the blue icon instead only text should be shown. Can you help me on this? @Falke-Design  @codeofsumit

**Comment by Falke-Design** [comment]
Please add images, code and a demo

**Comment by agishk** [comment]
![Capture](https://user-images.githubusercontent.com/97210836/217160662-f5ac6248-3a9a-45d1-82b7-25ed2227287a.PNG)

@Falke-Design   I have overridden the enable function of text marker as below:
`enable(options) {  
   L.PM.Draw.Marker.prototype.enable.call(this, options);     // add tooltip to hintmarker     this.options.textMarkerOptions.textContent = this._getTextContent(this.options.textMarkerOptions);     if (this._hintMarker) {         this._hintMarker             .bindTooltip(this.options.textMarkerOptions.textContent, this.options.textMarkerOptions.textOptions)             .openTooltip();     
} },
`
And basic properties as below:
initialize(map) {  
   this._map = map;  
   this._shape = 'TextMarker';   
   this.textMarkerOptions = {         fontColor: "orange",         fontSize: 12,         fontFamily: "arial",         fontWeight: "normal",         text: "TextMarker Default",         textOptions: {             permanent: true,             opacity: 1,             direction: 'right',             className: 'agis-text-label'         },         markerStyle: {             draggable: true,             icon: L.icon(),//div icon created         }     };      this.textMarkerOptions.textContent = this._getTextContent(this.textMarkerOptions);     // Set radius for CircleMarker     L.setOptions(this, {         //templineStyle: {radius: 10},         //pathOptions: {radius: 10},         textMarkerOptions: this.textMarkerOptions     });     //this.options = L.extend({}, this.options, );  
},

**Comment by Falke-Design** [comment]
Instead of `icon: L.icon()` you need to create a `divIcon`: `icon: L.divIcon()` and hide it via css
