### ISSUE TITLE
Limit number of drawn objects?

### ISSUE THREAD

**Issue by TheTiGuR** [geoman-io/leaflet-geoman#1308]
I would like to set a limit of number of drawn objects on a given map, while also retaining the ability to edit them. Realistically I just want a user to be able to draw a single item, at which point I will take the geoJson from that drawn item and export it, including if that item is then edited, export the edited version. Is this possible? I've been looking through all the options and I'm not sure that I've found anything that made sense to achieve this.

For a clarified workflow:
1. Map is opened with editing tools (marker, rect, poly, circle, edit)
2. Item is drawn
3. upon completion of drawing, layer information is exported
4. Drawn item can be edited, or deleted, but second item cannot be added, without deleting the first

Similarly, if I am opening the map with an existing item, be able to edit, but not add a second item

Hope that's clear. Thanks for any guidance.

**Comment by Falke-Design** [comment]
The easiest way is to hide the draw controls:
```
// prevent drawing of multiple markers
map.pm.setGlobalOptions({continueDrawing: false});

var layer;
// listen to when a new layer is created
map.on('pm:create', function(e) {
	layer = e.layer;
	map.pm.addControls({drawControls: false});

	// if the layer is deleted, the draw controls will be visible again
	layer.once('remove',()=>{
  		map.pm.addControls({drawControls: true});
	})
});
```

https://jsfiddle.net/cz7m5e38/

**Comment by TheTiGuR** [comment]
I thought it might be along those lines, just hadn't gotten to test it yesterday. Tried this morning and works exactly like I was wanting, thank you very much.
