### ISSUE TITLE
Prevent remove last vertex

### ISSUE THREAD

**Issue by prancius** [geoman-io/leaflet-geoman#1310]
Any ideas how to prevent remove last vertex for geometry (circle, polygon, square). When using edit mode it is possible to remove one by one vertexes and at the last geometry disappear and no way to edit it.

Than you

**Comment by Falke-Design** [comment]
You can set `removeLayerBelowMinVertexCount: false`:
```
map.pm.setGlobalOptions({removeLayerBelowMinVertexCount: false})
```

https://jsfiddle.net/wjzqo2ud/

**Comment by prancius** [comment]
Nice! Thank you
