### ISSUE TITLE
To remove the tooltip of textMarker when its enabled

### ISSUE THREAD

**Issue by agishk** [geoman-io/leaflet-geoman#1319]
I have a button tool for textMarker . How can I remove the tooltip of text marker when the button is clicked?
@codeofsumit

**Comment by Falke-Design** [comment]
You can disable the tooltip by setting `tooltips: false`:

```
map.pm.enableDraw('Text', {tooltips: false})
```
https://jsfiddle.net/n6yfm8xk/
