### ISSUE TITLE
When select Text layer and click on a point on map, I see [object HTMLTextAreaElement]

### ISSUE THREAD

**Issue by susanirwinC5T** [geoman-io/leaflet-geoman#1320]
https://jsfiddle.net/o1dwu2vg/ did not reproduce the problem. 

May just need additional instruction on how to use the Text layer.  When I click on the "T" and click on a place on the map, I can't enter text. I see [object HTMLTextAreaElement]

**Comment by Falke-Design** [comment]
Sorry we can't help you until you show us an reproducable demo.
