### ISSUE TITLE
Add support draw/edit rectangle min/max width/height

### ISSUE THREAD

**Issue by nchizhov** [geoman-io/leaflet-geoman#1324]
How can I add support min/max width/height for draw new or edit exists rectangles?

I'm trying with pm:markerdrag - rectangle stopping changing for min, but markers on rectangle continue moving.

Thank you

**Comment by Falke-Design** [comment]
Maybe this helps you: #843

Try out the option `moveVertexValidation`, this will prevent moving the vertex-marker after your custom function returns `false`.
