### ISSUE TITLE
tips for dragging entire LayerGroup?

### ISSUE THREAD

**Issue by hypergig** [geoman-io/leaflet-geoman#1330]
I have a layer group that together, makes up a single entity that I would like to treat as if it was a single layer. That means I would like to be able to drag all of the layers in that group together as if it was one thing. 

The best way I can figure to do this is by creating a rectangle, make that draggable with `pm.enableLayerDrag()`, then set its `"pm:drag"` event to actively set the bounds of the other layers in the `LayerGroup`, essentially binding them all together. 

This is just in theory, I haven't gotten it to work yet, but that made me wonder if there was a better way to do this?

**Comment by hypergig** [comment]
not sure if this is the exactly _correct_ but:

```js
    const ref = React.useRef<LeafletFeatureGroup>(null)
    React.useEffect(() => {
        ref.current?.pm.getLayers(true).forEach((l: Layer) => {
            // Layer doesn't extend PMDragLayer?
            // @ts-ignore
            l.pm.enableLayerDrag()
        })
        ref.current?.pm.setOptions({syncLayersOnDrag: true})
    })
    return (
        <FeatureGroup ref={ref}>
            <Rectangle bounds={bounds}/>
            <ImageOverlay url={props.imgUrl} bounds={bounds}/>
        </FeatureGroup>
    )
```

**Comment by Falke-Design** [comment]
@hypergig using `syncLayersOnDrag: true` is the correct way. Does it work for you?

**Comment by hypergig** [comment]
Yes, this is working for me as I would expect, the only snag was the missing typescript for `pm.enableLayerDrag` on `Layer` which tripped me up a little. Thanks!
