### ISSUE TITLE
snap layer to LatLang?

### ISSUE THREAD

**Issue by hypergig** [geoman-io/leaflet-geoman#1331]
Is snapping strictly for precision drawing or can it be used to snap a layer to a specific LatLang or bound while dragging? I am trying to support the ability to grid snap draggable layers. For example, if you are dragging an image layer, it snaps to every _n_th LatLang intersection instead of freely being draggable anywhere.

**Comment by Falke-Design** [comment]
We don't have implemented any snapping for ImageOverlay, so you need do add this logic by your self. 

I will add this as a Feature Request

**Comment by hypergig** [comment]
Thanks @Falke-Design I did what you suggested.

For those that are interested, I used two layers: a `Circle` and an `ImageOverlay`, and only set the `Circle` as draggable. On `Circle` `change` I set the position of the underlying `ImageOverlay` after `Math.round`ing the `LatLang` to the nearest integer, which is the nearest grid position as per my map scale. Once I drop the `Circle` I have its position also snap to keep the two layers together.

You can see it here: https://github.com/hypergig/LeafyVTT/pull/1
