### ISSUE TITLE
pm:intersect issue

### ISSUE THREAD

**Issue by dvazquez-lightbox** [geoman-io/leaflet-geoman#1332]
hey Everyone, after looking through the docs, I wanted the ability to log when an intersection occurs. im able to log other events outside of the pm:intersect. Is this the correct way of calling it the intersect event when drawing a shape?
```
.on('pm:drawstart', ({ workingLayer } ) => {
         workingLayer.on('pm:vertexadded', (layer) => {
             console.log("vertex added is logged");
         });
         workingLayer.on('pm:intersect', (layer) => {
            console.log("intersect is not logged");
         });
      });

**Comment by Falke-Design** [comment]
Currently we don't support the `intersect` event while drawing. But I will implement it 👍 .

**Comment by dvazquez-lightbox** [comment]
thanks @Falke-Design that would be awesome.
