### ISSUE TITLE
Restrict radius

### ISSUE THREAD

**Issue by meersonv** [geoman-io/leaflet-geoman#1341]
How can I limit the circle radius to max value?

**Comment by Falke-Design** [comment]
With `maxRadiusCircle`:

```
map.pm.enableDraw('Circle', {maxRadiusCircle: 2000});
```

https://jsfiddle.net/7Lyafbg2/

**Comment by meersonv** [comment]
And a similar question about the ability to limit the area of a polygon.
Thank you!
