### ISSUE TITLE
Hide the line in the Circle when editing

### ISSUE THREAD

**Issue by fatihcandev** [geoman-io/leaflet-geoman#1350]
@codeofsumit @Falke-Design  Hi. I looked through the issues but couldn't find anything similar. As you can see down below, there is a line in my Circle shape when the edit mode is active. Is it possible to hide it or give it a custom color? Thanks.

![image](https://user-images.githubusercontent.com/54099904/236192557-984075ab-df35-4f62-ad4f-243ecb411744.png)

**Comment by Falke-Design** [comment]
You can style the hintline with `layer.pm.setOptions({hintlineStyle: {color: 'green'}})`

**Comment by fatihcandev** [comment]
> You can style the hintline with `layer.pm.setOptions({hintlineStyle: {color: 'green'}})`

Thanks a lot! 🙏🏻
