### ISSUE TITLE
Drag in edit mode

### ISSUE THREAD

**Issue by zenggpzqbx** [geoman-io/leaflet-geoman#1352]
When you drag an element in edit mode, the vertices do not move
![image](https://user-images.githubusercontent.com/112957325/236654516-13161809-54b6-41af-ad96-d0d5e5cf0d24.png)

**Comment by Falke-Design** [comment]
Geoman doesn't support combining this modes. You need to do this by your self.
Try to catch the `pm:dragstart` event, then disable editing and enable editing again with `pm:dragend`
