### ISSUE TITLE
disable toggling of a button

### ISSUE THREAD

**Issue by alexh1673** [geoman-io/leaflet-geoman#1354]
I'm trying to make it so that my geomean button will not trigger when clicking off of it. In other words clicking once on button, then on another button will trigger the former twice. I want to make sure the former only gets triggered when the user clicks on it. Heres my button - 
```
  map.pm.Toolbar.createCustomControl({
    name: 'redo',
    block: 'custom',
    className: 'redo-button',
    title: 'redo',
    doToggle: false,
    onClick: () => {
      handleredo();
    }
  });
```

**Comment by Falke-Design** [comment]
Replace `doToogle` with `toggle` and then it should work.

```
  map.pm.Toolbar.createCustomControl({
    name: 'redo',
    block: 'custom',
    className: 'redo-button',
    title: 'redo',
    toggle: false,
    onClick: () => {
      handleredo();
    }
  });
```
