### ISSUE TITLE
bug: wrong radius when drawing circle

### ISSUE THREAD

**Issue by jingss** [geoman-io/leaflet-geoman#1356]
when the zoom is low, the radius of drawing circle is not right.

https://github.com/geoman-io/leaflet-geoman/assets/5043792/a13d399b-7134-4619-a45f-bae2cb782893

**Comment by Falke-Design** [comment]
Thank you for reporting but we can't fix this. This happens because of the earth projection

**Comment by jingss** [comment]
I have already fix this bug.
add a new custom circle class, save the lat and lng of point on circle ,calculate the radius (pointOnCircle - centerPoint)
`export const CustomCircle = L.circle.extend({
  _project(){
    const map = this._map;
    //center point, in pixel
    this._point = map.latLngToLayerPoint(this._latlng);
    let pointOnCircle = map.latLngToLayerPoint(this.options.pointOnCircleLatLng);
    //calculate radius, pointOnCircle - centerPoint
    this._radius = this._point.distanceTo(pointOnCircle);
    this._updateBounds();
  }
});`
