### ISSUE TITLE
Fix links to new website.

### ISSUE THREAD

**Issue by ByMykel** [geoman-io/leaflet-geoman#1357]
In the repository details on the right, the link is https://geoman.io/leaflet-geoman.
![image](https://github.com/geoman-io/leaflet-geoman/assets/38622893/194cd62b-b7f2-408b-8c8f-75808d1267a1)

Also there are two lines in the code:
https://github.com/geoman-io/leaflet-geoman/blob/144c0c89a55a93f011d7b90170c7dee748de8189/src/js/L.PM.js#L8
https://github.com/geoman-io/leaflet-geoman/blob/144c0c89a55a93f011d7b90170c7dee748de8189/package.json#L83

**Comment by codeofsumit** [comment]
will do 👍
