### ISSUE TITLE
Demo marker not loading

### ISSUE THREAD

**Issue by joonaspaakko** [geoman-io/leaflet-geoman#1364]
<img width="307" alt="CleanShot 2023-06-15 at 14 16 39@2x" src="https://github.com/geoman-io/leaflet-geoman/assets/1164476/5b59d0c5-b071-49eb-a60b-1492e870b494">

**Comment by codeofsumit** [comment]
Ah thanks - forgot about this leaflet bug.
There are workarounds for it:
https://stackoverflow.com/questions/41144319/leaflet-marker-not-found-production-env

Added the workaround to geoman.io - fixed now 👍
