### ISSUE TITLE
Replace hard-coded Earth radius with the Leaflet Earth radius

### ISSUE THREAD

**Issue by Falke-Design** [geoman-io/leaflet-geoman#1366]
Use instead: `L.CRS.Earth.R`

https://github.com/geoman-io/leaflet-geoman/blob/932d4a986ec5853f183a1a69fa8d9d55bff963de/src/js/helpers/index.js#L51

https://github.com/geoman-io/leaflet-geoman/blob/932d4a986ec5853f183a1a69fa8d9d55bff963de/src/js/helpers/index.js#L156

Reference: https://github.com/makinacorpus/Leaflet.GeometryUtil/pull/96

**Comment by tangerine-orange** [comment]
Hey, first time contributor here. Looking at picking up this simple ticket, but I noticed that there is no test coverage for these chunks of code. Futhermore there are no unit tests in the codebase, only cypress end-to-end tests. Is my understanding correct? If so, why no unit tests?

Sorry if this is not the right place to talk about this.
