### ISSUE TITLE
Draw Line to exit when the last point is overlapping the first point

### ISSUE THREAD

**Issue by ABPW10** [geoman-io/leaflet-geoman#1377]
I need to create closed polylines ( that stand for loop trajectories ) all of which start and end in the same location. When I use `Draw.Line._createVertex()` to create vertex at each `latlng` location, the Draw Mode exits as soon as the last `latlng` is passed in, so the shape finishes with the last point left out. Could we have an option to allow closed polylines in Draw.Line , and not to finish the shape if the same latlng as the first latlng is encountered.

**Comment by Falke-Design** [comment]
I will mark this as a Feature Request. You also can try to make a PR by your self.

You can upvote this with 👍
