### ISSUE TITLE
Disable snapping feature with ALT stops working

### ISSUE THREAD

**Issue by FritschP** [geoman-io/leaflet-geoman#1378]
Hi!

If you disable the snapping feature temporarily by pressing the ALT key, it works as intended. But if you stop holding the ALT key, and then hold it again, the snap feature won't disable. 

This is also reproducible in your Demo:
* Place a rectangle
* Try to place another rectangle
* Disable the snap feature by holding the ALT key
* Enable the snap feature by letting go of the ALT key
* Try to disable the snap feature again by holding the ALT key <- not working

Best Regards

**Comment by Falke-Design** [comment]
Thank you for reporting. Will be fixed with #1379
