### ISSUE TITLE
Geoman event pm:create doesn't fire when adding polygon programmatically

### ISSUE THREAD

**Issue by Javad1992** [geoman-io/leaflet-geoman#1382]
Hi
thanks for awesome plugin.
I'm using leaflet with the Geoman plugin, and I notice that pm:create doesn't fire when I add new polygon programmatically like this:
L.polygon([JSON.parse("[" + data + "]")]).addTo(map)

**Comment by Falke-Design** [comment]
Yes because the polygon is not created by Geoman. You can catch the event with the Leaflet default event [`layeradd`](https://leafletjs.com/reference.html#map-layeradd):

```
map.on('add', (e)=>{

});
```

**Comment by Javad1992** [comment]
Thanks for help. I add `  map.on('add', ({ layer }) => {

      console.log("on add!");
    });`

but it doesn't work. I add polygon like this `        let geoJson = {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "type": "Polygon",
            "coordinates": [
              [
                [
                  55.281143,
                  37.227458
                ],
                [
                  55.275478,
                  37.219393
                ],
                [
                  55.290928,
                  37.218983
                ],
                [
                  55.281143,
                  37.227458
                ]
              ]
            ]
          }
        }

        L.geoJSON(geoJson).addTo(map);` 

when html page load, but log doesn't appeared. (sorry for bad English)

**Comment by Falke-Design** [comment]
Sorry my fault you need to use [`layeradd`](https://leafletjs.com/reference.html#map-layeradd):

```
map.on('layeradd', (e)=>{

});
```

**Comment by Javad1992** [comment]
Thanks @Falke-Design 

it works. now can I use code like this  `    map.on("pm:create", ({ layer }) => {
      map.pm.Toolbar.setButtonDisabled("drawPolygon", true);

      setPupup(layer)

      layer.on("pm:edit", ({ layer }) => {

        setPupup(layer)
      });

      layer.on("pm:remove", ({ layer }) => {
        map.pm.Toolbar.setButtonDisabled("drawPolygon", false);
      });
    });`                and instead of pm:create use layeradd. in another word when I want to use {layer} object from layeradd and want to use layer.toGeoJSON method it throws layer.toGeoJSON is not a function. is my way wrong? correct way please.

**Comment by Falke-Design** [comment]
If you use `layeradd` you need to use `e.target` instead of `e.layer`

**Comment by Javad1992** [comment]
I use
 `e.target.toGeoJSON()`
but it yet throws same error
