### ISSUE TITLE
how to fire pm:create programmatically

### ISSUE THREAD

**Issue by Javad1992** [geoman-io/leaflet-geoman#1383]
Hi.
how to create polygon programmatically to fire pm:create ?
I use this code 
`L.geoJSON(geoJson).addTo(map);`
but it doesn't fire pm:create

**Comment by Falke-Design** [comment]
`pm:create` is only fired if you create an layer over the drawing tools from Geoman. You can listen on the `layeradd` event on the map to detect other layers too.
