### ISSUE TITLE
Rotating markers support

### ISSUE THREAD

**Issue by cubecleveland** [geoman-io/leaflet-geoman#1384]
Hi Guys, 

Thanks for this awesome lib that is serving us well.
Im sure that this was asked before but i wanted to know if there is any support or any idea ho we can implement rotating markers we have a speific markers that are large and we want to be able to rotate them when entering rotate mode... not sure if Geoman can do it nativelly... or need to use some hack or other lib.

Thanks!

**Comment by Falke-Design** [comment]
We do not support Marker rotation. You can try: https://github.com/bbecquet/Leaflet.RotatedMarker

**Comment by cubecleveland** [comment]
Thanks so much for your response!
