### ISSUE TITLE
is there a way to recalculate the geometry when event is received?

### ISSUE THREAD

**Issue by Adryian4ik** [geoman-io/leaflet-geoman#1389]
Hi. I have a problem. 
When I drag vertex of exclusion-polygon outside of polygon, I want to get cutted polygon. I tried all events of edit mode, but nothing give me right result.

https://github.com/geoman-io/leaflet-geoman/assets/112876989/fb3120dd-9bd9-49ea-b068-d645f9360555

Waitied result:
![image](https://github.com/geoman-io/leaflet-geoman/assets/112876989/e17149c4-37d7-4094-9db6-bfb8e4a25896)

**Comment by Falke-Design** [comment]
You can use the `pm:update` event (after disabling the edit mode) or `pm:edit` after finishing moving the vertex. 
But to achive your wanted result, you need to get the difference between the "hole" and the layer. You can use for that [turfjs.org](https://turfjs.org/docs/#difference).

https://jsfiddle.net/dy0tqon6/

```
map.on('pm:cut', (e)=>{
        e.layer.on('pm:update', (ev)=>{
          console.log(ev);
          if(ev.layer.pm.hasSelfIntersection()){
            const geoJSONPolyCoordLayers = ev.layer.getLatLngs().map((coords)=>{
              return L.polygon(coords).toGeoJSON();
            })

            let mainPolyGeoJSON = geoJSONPolyCoordLayers[0];
            geoJSONPolyCoordLayers.forEach((geojsonCoords,idx)=>{
              if(idx === 0){
               // jump over "main" polygon
                return;
              }
              const difference = turf.difference(mainPolyGeoJSON, geojsonCoords);
              if(difference) {
                mainPolyGeoJSON = difference
              }
            });

            const newPoly = L.geoJSON(mainPolyGeoJSON).getLayers()[0];
            newPoly.addTo(map);
            ev.layer.removeFrom(map);
          }
        })
      })
```

**Comment by Adryian4ik** [comment]
Thank you very much for answer and example for my situation)
