### ISSUE TITLE
Add api to change layer coordinates

### ISSUE THREAD

**Issue by huangyingjie** [geoman-io/leaflet-geoman#1396]
Hi, I'd like to change Polygon coordinates by some data directly, ie: union with another Polygon, then continue to editing manually.

This is an important feature while editing district or aoi with too many point, where we want to cut or join with another district, instead of dragging manually.

**Comment by Falke-Design** [comment]
You can always update the coordinates with `layer.setLatLngs(coords)` by your self and then call `layer.pm.enable()` to set all the vertex handlers.
