### ISSUE TITLE
leaflet  用 esri-leaflet 加载了矢量要素图层后, 使用@geoman-io/leaflet-geoman-free  进行绘制特别特别卡顿

### ISSUE THREAD

**Issue by godeev** [geoman-io/leaflet-geoman#1408]
![image](https://github.com/geoman-io/leaflet-geoman/assets/36323493/c022d426-e6fa-4d0c-b549-10d2ac62987a)

**Comment by Falke-Design** [comment]
I think your problem is, that you have to many points on your layers.

Try `limitMarkersToCount` https://geoman.io/docs/modes/edit-mode

**Comment by godeev** [comment]
你好, 你的这个解决方案跟我的现象完全不搭边, 我这是在已有图层的地图上绘制, 而不是编辑!

红色的图层是用 esri-leaflet 加载的矢量图层,  然后这时候我使用 @geoman-io/leaflet-geoman-free 进行绘制, 鼠标放到地图上, 特别卡顿, 几乎没法进行绘制操作
