### ISSUE TITLE
getting script error drawing polygons, any help?

### ISSUE THREAD

**Issue by meshed-genc** [geoman-io/leaflet-geoman#1427]
hi, hallo!
i couldn't find a code demo.html config page for geoman from start to finish except partial code demos.
So i made one working page with 27 lines of code   [Basic map with Leaflet.js and OpenStreetMap - JSFiddle - Code Playground](https://jsfiddle.net/5vn8mrbk/)
But i am getting script error when i draw polygons any help?

**Comment by Falke-Design** [comment]
Use the latest version of Leaflet (1.9.4), then everything works fine. https://jsfiddle.net/kjsbtao1/

**Comment by meshed-genc** [comment]
thank you very much
