### ISSUE TITLE
Add uniq id to geoman drawn polygon

### ISSUE THREAD

**Issue by meshed-genc** [geoman-io/leaflet-geoman#1429]
Hi there!
I already have a json retrieve system where I can highlight 2 polygons with uniq id, but I also want to access to a new drawn polygon from geoman how can I add and increment the uniq id for new polygon

https://jsfiddle.net/tkj4uyas/2/

**Comment by meshed-genc** [comment]
the whole system is needed for animation purposes thanks..

**Comment by meshed-genc** [comment]
this is a small project, I also don't want to install a server side extension for GIS

**Comment by Falke-Design** [comment]
To get the new drawn layer, you can use the `pm:create` event on the map.

To apply the new drawn layer to your GeoJSON group do following:
```
map.pm.setGlobalOptions({layerGroup: geoJSON});
  
map.on('pm:create',(e)=>{
	console.log('I\'m the new layer', e.layer)
	e.layer.feature = e.layer.toGeoJSON();
	e.layer.feature.id = 3;
	geoJSON.setStyle(style);
})
```
https://jsfiddle.net/vcoqyxre/

**Comment by meshed-genc** [comment]
thank you very much for the help
