### ISSUE TITLE
Drawing Polygon reports error and cannot close  the Polygon

### ISSUE THREAD

**Issue by huangyingjie** [geoman-io/leaflet-geoman#1437]
I use @geoman-io/leaflet-geoman-free@^2.14.2, the following error occurs when drawing polyon.
<img width="530" alt="image" src="https://github.com/geoman-io/leaflet-geoman/assets/1618397/fffe57bc-93c3-4fbe-aa0b-1146e664b112">
```js
      this.map.pm.enableDraw('Polygon', {
        tooltips: false,
        snappable: true
      })

```

* details
<img width="714" alt="image" src="https://github.com/geoman-io/leaflet-geoman/assets/1618397/3d474655-0e1f-4555-8ae4-e6bf2fd3cf58">

I'm sorry I can't reproduce it every time, but it happens.

**Comment by Falke-Design** [comment]
Can you please try if you can reproduce it on this fiddle: https://jsfiddle.net/3mhcsn2e/
