### ISSUE TITLE
Add a text marker to a map

### ISSUE THREAD

**Issue by artem1643** [geoman-io/leaflet-geoman#1439]
Hi !

I'm facing a problem adding a text marker to a map.When I place a marker on the map, the [Object HTMLTextAreaElemet] array is displayed instead of what it should be. I suspect I'm the only one who has encountered this
![pict](https://github.com/geoman-io/leaflet-geoman/assets/123530623/e03028a5-d5eb-43be-a38a-b08e63824c51)
And the DOM looks like this
![dom](https://github.com/geoman-io/leaflet-geoman/assets/123530623/695e7c70-f070-4fbf-995e-5cf8a26bf4a6)
Is there any way to solve this problem?

**Comment by Falke-Design** [comment]
How do you create the Text-Marker? Please share your code or snipptes from your code, else we can't help you

**Comment by Falke-Design** [comment]
Do you overwrite somewhere the creation of the Text-Layer?

That's happing in the back:
```
var textArea = document.createElement('textarea');
textArea.readOnly = true;
textArea.classList.add('pm-textarea', 'pm-disabled');

var x = L.divIcon({
  className: 'pm-text-marker',
  html: textArea, // Looks like textArea.toString() is called
});

m = L.marker(map.getCenter(), {icon: x}).addTo(map);
```

But it looks like `html: textArea.toString()` is executed instead of `html: textArea` for `L.divIcon`.

Can you please try to reproduce your issue in this fiddle: https://jsfiddle.net/sqe60fxm/
Also please make sure to use the latest Geoman and Leaflet version.

Just to try it out... Does it work if you remove this two lines?
```
 let icon = map.pm.Toolbar.copyDrawControl('drawMarker', { name: 'justPin', title: 'Pin by marker' });
            icon.drawInstance.setOptions({ markerStyle: { icon: markerIcon } });
```

**Comment by artem1643** [comment]
> Do you overwrite somewhere the creation of the Text-Layer?
> 
> That's happing in the back:
> 
> ```
> var textArea = document.createElement('textarea');
> textArea.readOnly = true;
> textArea.classList.add('pm-textarea', 'pm-disabled');
> 
> var x = L.divIcon({
>   className: 'pm-text-marker',
>   html: textArea, // Looks like textArea.toString() is called
> });
> 
> m = L.marker(map.getCenter(), {icon: x}).addTo(map);
> ```
> 
> But it looks like `html: textArea.toString()` is executed instead of `html: textArea` for `L.divIcon`.
> 
> Can you please try to reproduce your issue in this fiddle: https://jsfiddle.net/sqe60fxm/ Also please make sure to use the latest Geoman and Leaflet version.
> 
> Just to try it out... Does it work if you remove this two lines?
> 
> ```
>  let icon = map.pm.Toolbar.copyDrawControl('drawMarker', { name: 'justPin', title: 'Pin by marker' });
>             icon.drawInstance.setOptions({ markerStyle: { icon: markerIcon } });
> ```

Thank you. I found out the reason of the problem. I had to update the latest version. Now I works. Thanks a lot
