### ISSUE TITLE
Translation problem with texts related to measurements in the Pro version

### ISSUE THREAD

**Issue by neterror** [geoman-io/leaflet-geoman#1440]
I enable the measurement functionality of Geoman Pro with:
`map.pm.setGlobalOptions({measurements: {measurement: true}});`

It works as expected with some languages (english, german, polish). For other languages like French it displays 'undefined' for the measurement text titles.  It looks like some text keys like coordinatesMarker are missing from the localization files. 

Steps to reproduce: 

1. `map.pm.setGlobalOptions({measurements: {measurement: true}});`
2. `map.pm.setLang('fr');`
3. Observe the measurements.

My geoman-pro account is plamen@abrites.com

**Comment by Falke-Design** [comment]
Thank you for submitting this issue. We will take care of it.

**Comment by mscno** [comment]
This has been foxed in the 2.11 release of Leaflet-Geoman Pro
