### ISSUE TITLE
More toolbar orientations?

### ISSUE THREAD

**Issue by kawallala** [geoman-io/leaflet-geoman#1446]
Hello! I've been using this library in a personal project, however, I' having the issue that I want the toolbar to be in the top middle of the map, in a horizontal orientation instead of the 4 provided ways in the [documentation]( https://www.geoman.io/docs/customize/toolbar), are more orientations something in the planning or is there a way to do them manually? 

Thanks!

**Comment by Falke-Design** [comment]
Hi @kawallala,
we only support the default [Leaflet Control positions](https://leafletjs.com/reference.html#control-position). But you can create your own toolbar / controls anywhere on your website. For example set somewhere an button which calls `map.pm.enableDraw('Polygon')`.
