### ISSUE TITLE
"Cut Layers" only deletes polygon objects

### ISSUE THREAD

**Issue by IanMayo** [geoman-io/leaflet-geoman#1452]
This issue is present in the vanilla GeoMan version on the demo page.

The "Cut layers" action only deletes polygons, it does not delete point markers or lines:
![screencast](https://i.gyazo.com/cb923217a8639b16e587b1fc9dbb8b79.gif)

I believe it should delete all features within the specified polygon.

My _guess_ is that [this](https://github.com/geoman-io/leaflet-geoman/blob/1d54501024a87caba4fd446334ecb6ab23bc20a9/src/js/Draw/L.PM.Draw.Cut.js#L142) code needs to be extended to support feature types other than `polygon`:
![image](https://github.com/geoman-io/leaflet-geoman/assets/1108513/5a2d6b1d-7a3a-44aa-8d53-cd90fea6b7bc)

**Comment by Falke-Design** [comment]
The cut mode can be only used for area shapes like Rectangles and Polygons.

I will transform this into a Feature Request and if there are enough likes, we will think about implementing it.
