### ISSUE TITLE
merge two layers or more 

### ISSUE THREAD

**Issue by AbdulrahmanM0** [geoman-io/leaflet-geoman#1463]
is there is a way to merge 
two layers in one layer 

from this 
![Screenshot 2024-202-29 173736](https://github.com/geoman-io/leaflet-geoman/assets/109548830/8ee94d15-14a1-4765-a149-1e86750753c7)
to this
![Screenshot 2024-02-29 174212](https://github.com/geoman-io/leaflet-geoman/assets/109548830/d771659b-2ea4-43c6-bf55-d081ba6b5c29)

**Comment by dailyprice** [comment]
This is a feature that we are including in the Geoman Pro version in an upcoming release.
