### ISSUE TITLE
Mobile and PWA: Drag Tool on a Marker opens the "Save as.." etc. dialogue for the graphic

### ISSUE THREAD

**Issue by CptHolzschnauz** [geoman-io/leaflet-geoman#1467]
Issue: A marker is set and the "Drag" Tool is enabled. Now sometimes the browser open the "Save as.." dialogue for the marker, sometimes it works as intended.

Reproduce: Just open the Geoman demon page with a mobile phone (at least with an iPhone), drop and drag a marker, stay a bit on the graphic with the finger.

Result:

![IMG_6359 Mittel](https://github.com/geoman-io/leaflet-geoman/assets/68701579/1174d904-d02b-48f0-8f22-e96623094662)
![IMG_6358 Mittel](https://github.com/geoman-io/leaflet-geoman/assets/68701579/65a31530-cce5-4c57-aba9-0b2093e77375)

Remediation: Prevent the dialogue

PS: Thx again for this lib and the maintance of the github page. Like it should be all over!

**Comment by Falke-Design** [comment]
Thank you for reporting the issue. 
Saddly this is a known bug of ios / Leaflet but there is currently no good solution for this.

https://github.com/Leaflet/Leaflet/issues/6865

I will close this, because we will wait until it is fixed in Leaflet

**Comment by CptHolzschnauz** [comment]
Thank you for your attention. Sorry for not finding the #6865, i searched but did nor found.
