### ISSUE TITLE
Cursor style glitching when drawing polygons

### ISSUE THREAD

**Issue by patdahl** [geoman-io/leaflet-geoman#1478]
Leaflet defines the style for .leaflet-interact as cursor: pointer, but Geoman has the style for .cursor-marker as pointer: crosshair. Depending on where the user's cursor lands while they are drawing a polygon, the cursor continues to flip between the two depending on whether the browser decides they are over the drawing marker or the helper line from the previous vertex. 

If you move the cursor fast enough, this behavior can also be seen when drawing rectangles and circles, though it is not nearly as obvious.

To recreate, you can just go to the demo site and place at least one marker to start a polygon : 
[https://www.geoman.io/demo](https://www.geoman.io/demo)

Obviously not a functional issue, but it seems like if someone took the time to intentionally put in .cursor-marker { pointer: crosshair } that this may matter to someone.

**Comment by Falke-Design** [comment]
Thank you for reporting. We will try to solve this.
![crosshair_cursor](https://github.com/geoman-io/leaflet-geoman/assets/19800037/143301a9-d228-4d68-960f-4aa097c008bd)
