### ISSUE TITLE
Unminified version? 

### ISSUE THREAD

**Issue by CalebCurry** [geoman-io/leaflet-geoman#1480]
Hi there, general question here as I have been running in to errors within the geoman library. The errors are not very user friendly

```
leaflet-geoman.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'optIn')
    at NewClass.t (leaflet-geoman.js:2:222109) 
```
all on line 2
Using the browser tools I was able to find these lines:

```
addInitHooks() {
    function t() {
        this.pm = void 0,
        L.PM.optIn ? this.options.pmIgnore === !1 && (this.pm = new L.PM.Map(this)) : this.options.pmIgnore || (this.pm = new L.PM.Map(this)),
        this.pm && this.pm.setGlobalOptions({})
    }
```

Where it immediately sets `pm` to undefined and then tries to access a property on it (throwing an error).

However, I am unclear the best way to map this to the original source code of leaflet-geoman to see what is going on. wondering if you provide a non-minified library for debugging? or a variation of the build script that does not minify

**Comment by mscno** [comment]
Source maps will be added from next release
