### ISSUE TITLE
Shadow point when removing vertex from linestring

### ISSUE THREAD

**Issue by MonfretAugustin** [geoman-io/leaflet-geoman#1486]
Hello,

We have recently integrated Leaflet-Geoman-Pro into our project and discovered a bug related to vertex manipulation on linestrings. For information the issue only appears on the pro version.

When a vertex is removed from a linestring and the map is dragged slightly, the removed vertex reappears.

### Steps to Reproduce:

1. Navigate to your [demo site](https://www.geoman.io/demo).
2. Remove a vertex from any linestring.
3. Slightly drag the map.
4. Observe that the previously removed vertex reappears.

![output](https://github.com/geoman-io/leaflet-geoman/assets/45000246/aaff1086-55a0-4b92-bd67-d3a17b59837c)

**Comment by Falke-Design** [comment]
Thank you for reporting. We will fix this asap

**Comment by Falke-Design** [comment]
@MonfretAugustin we fixed the issue. It will be in the next release of the pro version.
