### ISSUE TITLE
Point added with addVertexOn is "jumping" upon zooming in or out

### ISSUE THREAD

**Issue by MonfretAugustin** [geoman-io/leaflet-geoman#1487]
Hello,

When a vertex is added using the `addVertexOn` function, the point exhibits a "jumping" behavior upon zooming in or out.  The behavior disappears when we drag the map in any direction.

![Enregistrement de l’écran 2024-04-25 à 10 32 35 (1)](https://github.com/geoman-io/leaflet-geoman/assets/45000246/dfbc8663-e1cb-4b47-8e81-945f833cdbda)

### Step to reproduce

1. Navigate to the demo [site.](https://www.geoman.io/demo)
2. Create a linestring
3. Add a point
4. Zoom in or out to observe the point "jumping".
5. Drag the map in any direction, then zoom again. The jumping behavior dissapear.

**Comment by Falke-Design** [comment]
@MonfretAugustin we fixed the issue. It will be in the next release of the free version.
