### ISSUE TITLE
The snapping feature for drawing points and lines is not functional when in drawing mode

### ISSUE THREAD

**Issue by mmmmasdasd** [geoman-io/leaflet-geoman#1496]
<img width="677" alt="image" src="https://github.com/geoman-io/leaflet-geoman/assets/47859908/7537d7b7-6210-412e-ae3a-9443501c3165">
<img width="525" alt="image" src="https://github.com/geoman-io/leaflet-geoman/assets/47859908/bb6c38b7-cd45-4f57-9514-d48016896631">

Chrome version: 125.0.6422.142
Os: macOs
leaflet-geoman: 2.17.0

This problem occurred suddenly some time after the completion of the function development. I rolled back the code version, but this problem still exists. I am not sure about the cause of this problem, so I hope the author can help me analyze it。Thank you。

**Comment by Falke-Design** [comment]
Without any code, this is realy hard to debug. Can you please try to reproduce this in this demo:  https://jsfiddle.net/o1dwu2vg/
Or can you share your project code?
