### ISSUE TITLE
Feature Request: Enhanced Pin Mode for Adding and Removing Points

### ISSUE THREAD

**Issue by MonfretAugustin** [geoman-io/leaflet-geoman#1505]
Hello,

I would like to propose an enhancement to the Pin Mode Pro feature, to extend its functionality to include both adding and removing points.

In our business cases, we often deal with multiple superimposed polylines, which can make it cumbersome to add or remove points. Here is an example of our use case:

![Geoman_pinmode_feature](https://github.com/user-attachments/assets/ae5b78db-e5d1-4e1d-9fa2-441de459423c)

In this example, we have 3 superimposed polylines. In some cases, we may have up to 15 superimposed polylines. To add a point, we currently need to click and drag multiple times (once for each polyline), and similarly, to delete a point, we need to repeat the action for each polyline. This process is quite tedious and time-consuming.

### Proposed Enhancement:

Allow adding and removing points with a single click when Pin Mode is enabled.

### Questions:

1.	Does this proposed enhancement make sense to include in the Pin Mode feature?
2.	If yes, do you have plans to implement it in the near future?
(If no, we will consider implementing this feature ourselves due to its necessity in our operations.)

Thank you !

**Comment by dailyprice** [comment]
Hi @MonfretAugustin - Thank you for suggesting this feature. This is not something we will consider implementing in the near future and I would advice you to go ahead with your own implementation given the necessity for your business.
