### ISSUE TITLE
Some icons broken after updating from 2.13.0 -> 2.16.0

### ISSUE THREAD

**Issue by viktorsmari** [geoman-io/leaflet-geoman#1511]
![image](https://github.com/user-attachments/assets/893d1a2d-47fd-4cfd-b2ed-0d466126bec5)

Here we have some icons (not all) broken after this update.

When inspecting we see some don't work
![image](https://github.com/user-attachments/assets/e4d8f070-ea16-4f2b-a30b-4e52907529eb)

Some work
![image](https://github.com/user-attachments/assets/1ea1955f-8506-48fe-b2a7-7c9760b1d038)

When I open up a broken icon **in a new tab** it actually works:
![image](https://github.com/user-attachments/assets/02087420-7ccc-45e3-8438-678345fc44da)

Could the `%0A` be a part of the issue?
![image](https://github.com/user-attachments/assets/b951ec43-1732-439a-a0c7-4f1566cd1f1f)

Any ideas how I could debug further?

**Comment by viktorsmari** [comment]
If I use a CDN it works, so I cannot reproduce on JSFiddle.

I am using Ruby on Rails and esbuild.

`package.json`:
```
  "dependencies": {
    "@geoman-io/leaflet-geoman-free": "^2.17.0",
 ```

`app/assets/stylesheets/application.bootstrap.scss`:
```
@import 'leaflet.markercluster/dist/MarkerCluster.Default';
@import 'flatpickr/dist/flatpickr';
@import '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman';
```

This works fine in earlier versions:
- 2.13 works
- 2.15 works
- 2.17 does not work

**Comment by Falke-Design** [comment]
Hi,
with the 2.16.0 Version we accidentally made a breaking change. The build process was updated and sometimes causes problems with older builders.
We suggest to try to update your builder.

See: https://github.com/geoman-io/leaflet-geoman/releases/tag/v2.16.0

**Comment by viktorsmari** [comment]
Thanks @Falke-Design 
I am using version 0.23.1 of `esbuild` - but still having this issue. What else should I upgrade?

**Comment by Falke-Design** [comment]
After some digging I wasn't able to reproduce it
