### ISSUE TITLE
Does not allow the drawing of controls.

### ISSUE THREAD

**Issue by alissonrodrigo** [geoman-io/leaflet-geoman#1513]
When clicking on any option to draw on the map, this message appears in the console

![erro](https://github.com/user-attachments/assets/13d9a53b-3c97-4322-b166-6089c3708d5d)

**Comment by Falke-Design** [comment]
The problem is, that the global object `L.PM` is not found. Please check if you overwrite somewhere the global `L` variable or importing a another `leaflet` instance
