### ISSUE TITLE
Option to Snap Rectangle Edges Without Snapping Corners

### ISSUE THREAD

**Issue by erdoganabaci** [geoman-io/leaflet-geoman#1528]
Hi @Falke-Design , Is there a way to disable snapping at the corners of a rectangle while keeping it active on the edges? This would allow more flexible adjustments without corner constraints.

![Screenshot 2024-10-29 at 01 04 12](https://github.com/user-attachments/assets/12c42dcc-920e-4852-ac85-e5eaeee5a93b)

**Comment by Falke-Design** [comment]
This check happens here:

https://github.com/geoman-io/leaflet-geoman/blob/772c47c0820403a2438dcd50439de6801d81dc10/src/js/Mixins/Snapping.js#L519

Saddly there is currently no option to change that but here is a workaround for you.

Drawing shapes:
```
map.pm.Draw.getShapes().forEach((shape)=>{
    if(map.pm.Draw[shape]._checkPrioritiySnapping){
        map.pm.Draw[shape]._checkPrioritiySnapping = function(closestLayer) {
        const oldDistance = this.options.snapDistance;
      this.options.snapDistance = 0;

      const result = L.PM.Draw[shape].prototype._checkPrioritiySnapping.call(this,closestLayer)

      this.options.snapDistance = oldDistance;
      return result;
    }.bind(map.pm.Draw[shape]);
  }
});
```

For shapes to edit you need to overwrite the `_checkPrioritiySnapping ` on every layer in the `pm:create` too.
```
map.on('pm:create', (e) => {
e.layer.pm._checkPrioritiySnapping = function (closestLayer) { ... } .bind(map.pm.Draw[e.shape]);
});
```
