### ISSUE TITLE
Element hides other elements after dragging, rotating or other edit.

### ISSUE THREAD

**Issue by tanthammar** [geoman-io/leaflet-geoman#1545]
When moving, rotating or in other way editing an element, it ends up on top of all other elements.
Is there a way to move it back to initial stack order when editing is complete.

(I can see in html source, that the <path> elements is moved to top after edit)

Problem description.
When, for example, moving a large rectangle to a position where the user expects it to be positioned behind smaller circles, the circles can't be reached with the drag tool without moving the rectangle away from the circles...

**Comment by Falke-Design** [comment]
You can use `layer.bringToBack()` after finishing editing. https://leafletjs.com/reference.html#polygon-bringtoback
