### ISSUE TITLE
Is it possible to set pmIgnore=true by default?

### ISSUE THREAD

**Issue by sshikov** [geoman-io/leaflet-geoman#191]
Its a bit too inconvenient to set this option for each layer created, because sometime it could be created in 3rd party plugin. It would be great if I can set pmIgnore = true for all layers, and then select some layers to be handled by PM.

**Comment by codeofsumit** [comment]
definitely something I can add in some way or another 👍 
will look into it and do it if suitable

**Comment by codeofsumit** [comment]
closing this as I'm adopting lodashs issue management.
Feature requests are marked and closed. Upvotes on the issues show popularity and help me prioritize. It also helps keeping the Issue tab clean so I can spot bugs & todos faster.
A list of existing Feature Requests can be found here
https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed

**Comment by carueda** [comment]
@codeofsumit Hi Sumit, this is a meta-question (and sorry if this is explained elsewhere): for the feature requests (which are marked closed after being entered as you indicate above), how could one, from the main list or your [link](https://github.com/codeofsumit/leaflet.pm/issues?q=label%3A%22feature+request%22+is%3Aclosed), quickly tell the ones already **implemented**?  One extra label for this purpose would be very useful.

(btw, excellent tool, many thanks for you work!)

**Comment by codeofsumit** [comment]
hi @carueda, good point. Up until now I've simply removed the `feature request` tag 🤔 so it doesn't appear in the list anymore. Implemented features are of course visible in the Github Releases and their notes. Is that sufficient?

**Comment by carueda** [comment]
@codeofsumit I guess it is sufficient, thanks for the explanation!

**Comment by limfinity** [comment]
Hey @codeofsumit! :) First of all awesome work on the library and on keeping the community alive and tidy. 💯I would love to revisit this feature request, as this seems to be currently the most upvoted one. I know 6 is not the highest of numbers, but maybe enough to talk a little more details. I'd love to offer my help in any way, if you already have some implementation ideas, maybe you could add them here, and I might be able to create a PR from that.

**Comment by codeofsumit** [comment]
would be awesome if you could take a look at https://github.com/geoman-io/leaflet-geoman/pull/504 where I'm adding the optIn option.

It basically works like this:
If you call the this after importing leaflet-geoman:
```js
L.PM.initialize({ optIn: false });
```

Only layers that have specifically set `pmIgnore: false` will be handled by leaflet-geoman:
```js
L.marker([51.50915, -0.096112], { pmIgnore: false }).addTo(map);
```

Does that make sense?

**Comment by codeofsumit** [comment]
released ✅
