### ISSUE TITLE
[Bug] Problem with PM and MarkerCluster

### ISSUE THREAD

**Issue by JanLoebel** [geoman-io/leaflet-geoman#316]
Hi Sumit :)

First of all, thank you for your great contribution of this awesome plugin for Leaflet. I really appreciate the work you do here.

I have the following problem with the combination of Leaflet.PM and Leaflet.markercluster:

- The edit mode is disabled for a single marker by `pmIgnore: true` -> so far so good
- If I remove one marker, all of them are getting deleted -> that should not happen, especially because I don't wont to be able to delete marker at all.

Fiddle to reproduce:   http://jsfiddle.net/tc7xwqz0/20/

In the end, I'm not sure if it is a problem of PM or MarkerCluster. Perhaps you can have a look and let me know what you think.

Best regards,
Jan

**Comment by cagritepebasili** [comment]
MarkerClusterGroup extends L.FeatureGroup and MarkerCluster extends L.Marker. So, behaviour you experinced is expected. Using MarkerCluster with PM together actually brings out more than this conflict especially in events. It would be really great making them work together. If there will be any work about conflicts between MarkerCluster and PM, I try to participate as much as i can.
.

**Comment by JanLoebel** [comment]
So far the deletion is the only problem I had to face with MarkerCluster and PM. But so far I don't get exactly the problem. A FeatureGroup should only be handled by PM if not set to `pmIgnore` but that is what I do. Can you explain me the problem a little bit more in detail? It would really great if we could fix the problems all together.

**Comment by JanLoebel** [comment]
So far I found a workaround to avoid deleting hole markerCluster groups. Therefore I've had to edit the `toggleGlobalRemovalMode`-method in the `L.PM.Map.js`-file. I know this isn't by far any good solution but a workaround. What could be a better solution? I was thinking about hooks for filtering removal layer so everybody can implement a filter them self, that would be at least a more general solution. Furthermore, I know that if you open a cluster and click edit the lines between the center of the cluster and the items will be editable, but I don't see any chance with PM to avoid that. There is no chance to see that, that line is from `markercluster`.

```
 toggleGlobalRemovalMode() {
        // toggle global edit mode
        if (this.globalRemovalEnabled()) {
            this._globalRemovalMode = false;
            this.map.eachLayer((layer) => {
                layer.off('click', this.removeLayer);
            });
        } else {
            this._globalRemovalMode = true;
            this.map.eachLayer((layer) => {
                // Do not register removeListener for markerPane's
                const layerIsMarkerPane = (layer.options && layer.options.pane) === 'markerPane';

                if(layer._markerCluster) {
                    // Special handling for the Leaflet.markercluster plugin
                    layer.eachLayer((clusterLayer) => {
                        // Register each single layer on click and not the cluster itself
                        if (clusterLayer.pm && !(clusterLayer.pm.options && clusterLayer.pm.options.preventMarkerRemoval)) {
                            clusterLayer.on('click', this.removeLayer);
                        }
                    });
                } else if (layer.pm &&
                    !(layer.pm.options && layer.pm.options.preventMarkerRemoval) &&
                    !layerIsMarkerPane) {
                    // Default usage
                    layer.on('click', this.removeLayer);
                }
            });
        }

        // toogle the button in the toolbar
        this.Toolbar.toggleButton('deleteLayer', this._globalRemovalMode);
    },
```

**Comment by JanLoebel** [comment]
Okay, found out that the `markerPane` approach is not a good idea at all. But checking for `layer._group` is much better because the internal implementation of Leaflet.markercluster depends on that variable. So we can be sure to skip layers which has the `_group` property. Together with the `spiderLegPolylineOptions` it looks really good for my use case.

```
toggleGlobalRemovalMode() {
        // toggle global edit mode
        if (this.globalRemovalEnabled()) {
            this._globalRemovalMode = false;
            this.map.eachLayer((layer) => {
                layer.off('click', this.removeLayer);
            });
        } else {
            this._globalRemovalMode = true;
            this.map.eachLayer((layer) => {
                if(layer._markerCluster) { // Special handling for the Leaflet.markerCluster plugin
                    layer.eachLayer((clusterLayer) => {
                        // Register each single layer on click and not the cluster itself
                        if (clusterLayer.pm && !(clusterLayer.pm.options && clusterLayer.pm.options.preventMarkerRemoval)) {
                            clusterLayer.on('click', this.removeLayer);
                        }
                    });
                } else if (layer.pm &&
                    !(layer.pm.options && layer.pm.options.preventMarkerRemoval) &&
                    !!layer._group) { // Do not register removeListener for leaflet.markercluster groups
                    // Default usage
                    layer.on('click', this.removeLayer);
                }
            });
        }

        // toogle the button in the toolbar
        this.Toolbar.toggleButton('deleteLayer', this._globalRemovalMode);
    },
```

**Comment by JanLoebel** [comment]
Sorry for spaming you with such a long thread. I just wanted to let others know how to deal with it, if you don't wont to fork the project.

Final solution:
```
/**
 * Overriding the toogleGlobalRemovalMode function to avoid markerCluster-Elements get removable.
 */
L.PM.Map.prototype.toggleGlobalRemovalMode = function() {
  // toggle global edit mode
  if (this.globalRemovalEnabled()) {
      this._globalRemovalMode = false;
      this.map.eachLayer((layer) => {
          layer.off('click', this.removeLayer);
      });
  } else {
      this._globalRemovalMode = true;
      this.map.eachLayer((layer) => {
          const layerHasGroup = !!layer._group; // MarkerCluster have the attribute _group, which should be ignored

          if(layer._markerCluster) { // Special handling for the Leaflet.markerCluster plugin
              layer.eachLayer((clusterLayer) => {
                  // Register each single layer on click and not the cluster itself
                  if (clusterLayer.pm && !(clusterLayer.pm.options && clusterLayer.pm.options.preventMarkerRemoval)) {
                      clusterLayer.on('click', this.removeLayer);
                  }
              });
          } else if (layer.pm &&
              !(layer.pm.options && layer.pm.options.preventMarkerRemoval && !layerHasGroup)) {
              // Default usage
              layer.on('click', this.removeLayer);
          }
      });
  }

  // toogle the button in the toolbar
  this.Toolbar.toggleButton('deleteLayer', this._globalRemovalMode);
}
```

**Note:** If there will be a new version you'll have to maintain the method yourself!!

**Comment by codeofsumit** [comment]
Hi guys, I'm back from vacation and looked into this today. It seems hard to identify layers from markercluster.
The state of my work on this can be seen in this PR: https://github.com/codeofsumit/leaflet.pm/pull/321

I've also opened an issue at the markercluster repo regarding the identification of layers created by markercluster.
https://github.com/Leaflet/Leaflet.markercluster/issues/905

Any help is greatly appreciated - feel free to comment in the PR about possible solutions.
https://github.com/codeofsumit/leaflet.pm/pull/321

**Comment by codeofsumit** [comment]
@JanLoebel is this the expected behavious for global edit mode and marker cluster?
![markercluster](https://user-images.githubusercontent.com/2399810/43005326-d27e088a-8c32-11e8-9013-eb431e538993.gif)

(I'm still working on removal mode)

**Comment by JanLoebel** [comment]
@codeofsumit absolutely :) looks brilliant so far! 👍 For my usecase it's also important to be able to prevent markers from being edited (move).

**Comment by codeofsumit** [comment]
@JanLoebel that's a different issue. If you want your markers to be ignored by leaflet.PM you can either:

1. ignore them individually:
``` js
L.marker([0, 1], { pmIgnore: true })
```

2. disable their drag individually
``` js
const marker = L.marker([0, 1], { pmIgnore: true });
marker.pm.enable({ draggable: false });
```

3. disable drag for globalEditMode by enabling it once with your preffered options
```js
map.pm.toggleGlobalEditMode({
  draggable: false,
});
```

The last option might not work correctly when used with markercluster, but I will try and fix this in #321 as well.

**Comment by JanLoebel** [comment]
@codeofsumit Thanks, yeah I know that and have done it like that. It was just that we have to assure that these two work still together in the end :)

**Comment by JanLoebel** [comment]
@codeofsumit Yes sorry, that is what I wanted to say in the end :) Of course, it has nothing to do with the compatibility. I've just had the problem with my solution that markers could not be deleted in a cluster till I've added the remove-listener to each layer of the marker cluster.

```
if(layer._markerCluster) {
              layer.eachLayer((clusterLayer) => { ... }
```
But I get the point that this will work as before and the non-editable stuff has to be defined by one of the methods you've presented. As I wrote I've solved the problem exactly as you mentioned before.

**Comment by henrikmaa** [comment]
Does someone have issue with geoman and markerCluster layer.pm.enable()? 

starting editing a single layer with layer.pm.enable(), changing zoom -> every layer in markerCluster is now being edited?

**Comment by ramirez** [comment]
I'm using the following workaround, right after importing markerCluster. This extends the leaflet class that draws the cluster markers and simply adds the pmIgnore option:
```
(L as any).MarkerCluster = (L as any).MarkerCluster.extend({
  options: { pmIgnore: true, ...L.Icon.prototype.options }
});
```

It would be a nice addition to add the possibility of passing options to the base of the marker cluster in the same way that you pass them to the bounding polygons and the spider leg polylines.

Hope it helps.

**Comment by Falke-Design** [comment]
Hi everyone, I need help for testing.

With the code below Geoman should be compatible with MarkerCluster and it would be nice if you can help me to test it.

```
// Extends / Overwrite the default L.MarkerCluster and add pmIgnore
L.MarkerCluster = L.MarkerCluster.extend({
    options: { pmIgnore: true, ...L.MarkerCluster.prototype.options }
});

// Create a cluster group with pmIgnore options
const clusterMarker = L.markerClusterGroup({
    pmIgnore: true,
    spiderLegPolylineOptions: {
        pmIgnore: true,
        weight: 1.5,
        color: '#222',
        opacity: 0.5
    },
    polygonOptions: {
        pmIgnore: true,
    }
});

clusterMarker.on('spiderfied', ()=>{
    // Don't call the disable-functions while drawing
   if(!map.pm.globalDrawModeEnabled()) {

        // get enabled states
        var edit = map.pm.globalEditEnabled();
        var drag = map.pm.globalDragModeEnabled();
        var removal = map.pm.globalRemovalEnabled();

        // disable all -> to remove listeners and co
        map.pm.disableGlobalEditMode();
        map.pm.disableGlobalDragMode();
        map.pm.disableGlobalRemovalMode();

        // reinit the current mode
        if (edit) {
            map.pm.enableGlobalEditMode();
        } else if (drag) {
            map.pm.disableGlobalDragMode();
            map.pm.enableGlobalDragMode();
        } else if (removal) {
            map.pm.enableGlobalRemovalMode();
        }
    }
});

map.on('pm:remove',(e)=>{
    // remove the layer also from the markerClusterGroup
    if(e.layer.__parent && e.layer.__parent._group) {
        e.layer.__parent._group.removeLayer(e.layer);
    }
})
```
http://jsfiddle.net/falkedesign/kvu24t6L/


If we have enough tests and reviews we can implement it in the main Library or we create a offical Sub-Library

**Comment by codeofsumit** [comment]
Hi all, please test the solution provided by @ramirez and @Falke-Design. If that works for you, we will document this or put it into a subplugin and close this issue. Let us know 👍

**Comment by codeofsumit** [comment]
Closing this issue now. Please let us know if there are still issues to be tackled, then we will reopen this.

**Comment by Falke-Design** [comment]
Can you please create a demo on https://codesandbox.io/ we don't develop with angular so we are not able to start your project local

**Comment by Rosscotini** [comment]
@codeofsumit @Falke-Design was there ever a sub-plugin created for geoman and markercluster compatibility?

**Comment by Falke-Design** [comment]
Sorry for the late answer! I had found the problem and wanted to solve this but I forget it to do. I will look into it in the next days!

No there was no plugin, only the code from above https://github.com/geoman-io/leaflet-geoman/issues/316#issuecomment-695086098

**Comment by Rosscotini** [comment]
Thank you @Falke-Design much appreciated

**Comment by Falke-Design** [comment]
@Rosscotini after merging #1035 (or you build the code by your self from the branche) you can use following with Markercluster 1.5.3:

```
// Extends / Overwrite the default L.MarkerCluster and add pmIgnore
      L.MarkerCluster = L.MarkerCluster.extend({
        options: { pmIgnore: true, ...L.MarkerCluster.prototype.options }
      });

      // Create a cluster group with pmIgnore options
      const clusterMarker = L.markerClusterGroup({
        pmIgnore: true,
        spiderLegPolylineOptions: {
          pmIgnore: true,
          weight: 1.5,
          color: '#222',
          opacity: 0.5
        },
        polygonOptions: {
          pmIgnore: true,
        }
      });

      function pmDragEnd(e){
        if (map.pm.globalDragModeEnabled()) {
          map.pm.disableGlobalDragMode();
          map.pm.enableGlobalDragMode();
        } else if (map.pm.globalEditModeEnabled()) {
          map.pm.toggleGlobalEditMode();
          map.pm.toggleGlobalEditMode();
        }
      }
      clusterMarker.on('layeradd',(e)=>{
          e.layer.on('pm:dragend',pmDragEnd);
      });

      map.on('pm:remove',(e)=>{
        if(clusterMarker.hasLayer(e.layer)) {
          clusterMarker.removeLayer(e.layer);
        }
      });
```

**Comment by Rosscotini** [comment]
Thanks @Falke-Design hope for it to be merged in and deployed with next version of geoman. With angular I'm using a package.json to restore npm packages which runs on deployment so cant bring the code in myself but will wait on a new deployment of geoman. Thank you again
