### ISSUE TITLE
"Cancel" operation does not seem to work when in edit_layer mode

### ISSUE THREAD

**Issue by lbusett** [geoman-io/leaflet-geoman#380]
Based on what shown in the [demo](https://geoman.io/editor/), when editing a layer (i.e., moving vertexes), clicking on "Cancel" does not seem to work. Clicking "Cancel" stops the editing and "saves" the edits instead. The "editing" feature would much benefit in my opinion by a "system" similar to what already available when drawing a layer, where the user can decide if saving ("Finish") the edits, cancel them or "undo" the last edit.

**Comment by m1dst** [comment]
Totally agree.  Just stumbled across this whilst trying to work out why I couldn't find the feature in the docs or in the source.  Will be a very useful feature.

**Comment by Captain-Oski** [comment]
Any news on this ? This is clearly a missing feature well worth having. Thank you

**Comment by codeofsumit** [comment]
Hi all,

to remove the confusion, the `cancel` action is replaced by a `finish` action with the current functionality in the next release of Leaflet-Geoman.
![image](https://user-images.githubusercontent.com/2399810/75114625-e9084c00-5657-11ea-91db-21573afc4e1a.png)

The additional feature you are asking for seems to be "Undo" and "Redo", [which is requested here](https://github.com/geoman-io/leaflet-geoman/issues/320).
Please upvote that one
