### ISSUE TITLE
[Question] How to trigger cancel automatically

### ISSUE THREAD

**Issue by pichaya07** [geoman-io/leaflet-geoman#413]
Hi!

I would like to trigger a "cancel" event.
How can I trigger this event?

![Screen Shot 2562-03-20 at 11 33 56](https://user-images.githubusercontent.com/8343315/54660632-bbdb2180-4b09-11e9-81a5-054c54d42fca.png)

**Comment by Falke-Design** [comment]
with
```map.pm.enableDraw('Line');
    map.pm.disableDraw('Line');
```
you can force a cancle, but i think the event 'cancle' is not fired

**Comment by pate313373** [comment]
Very nice project! I really like it! :)

I have a HTML select element where the user should select the layerGroup he wants to draw in. If none is selected, I want the draw/edit operation to be cancled.

I tried as suggested:
`mymap.on('pm:drawstart', ({ workingLayer }) => {
					if(typeof userLayers[$('#userLayers_sel').val()] === 'undefined'){
						mymap.pm.enableDraw('Line');
						mymap.pm.disableDraw('Line');
						alert('No layer selected!');
					}
					workingLayer.on('pm:vertexadded', e => {
						console.log(e);
					});
				});`

However, it seems the suggested code fails with "Uncaught RangeError: Maximum call stack size exceeded".

Is there any other way to fire a cancle directly? In my opinion it would be a way cleaner approach.

Thanks and best regards

**Comment by Falke-Design** [comment]
Hi @pate313373 you run into this error, because you create a loop. When you call `map.pm.enableDraw('Line')` the `pm:drawstart` event is called, and in the event listener you call again `enableDraw`.

The better version is:
```
map.on('pm:drawstart',(e)=>{
	const shape = map.pm.Draw.getActiveShape();
	if(shape){
		map.pm.disableDraw(shape)
	}
})
```

**BUT** we have a bug in the Library so I have to fix this first. The `pm:drawstart` is called to early.

Until them you have to use a workaround with `setTimeout`:

```
map.on('pm:drawstart',(e)=>{
	setTimeout(()=>{
		const shape = map.pm.Draw.getActiveShape();
		if(shape){
			map.pm.disableDraw(shape)
		}
	},0.5);
})
```

**Comment by pate313373** [comment]
Excellent, thx  for the fast help! :)
