### ISSUE TITLE
Add preventMarkerRemoval on new created Markers

### ISSUE THREAD

**Issue by Falke-Design** [geoman-io/leaflet-geoman#418]
Can you please add the preventMarkerRemoval options on new created Markers at line:
https://github.com/codeofsumit/leaflet.pm/blob/47192afb964c887fc80b495dde7e3570dc18ab1a/src/js/Draw/L.PM.Draw.Marker.js#L122

like in the Edit file:
https://github.com/codeofsumit/leaflet.pm/blob/47192afb964c887fc80b495dde7e3570dc18ab1a/src/js/Edit/L.PM.Edit.Marker.js#L35

**Comment by codeofsumit** [comment]
@Falke-Design can you explain what you want to achieve? If I would add that, the option `preventMarkerRemoval` would also prevent new markers from being dragged which is not desired.

Do you want to prevent regular markers from being removed?

**Comment by Falke-Design** [comment]
I want that if a new marker is placed, that no interaction while drawing will work. No dragging, no removing. If a marker is placed, it should be only editable with the right tools and not in the drawing mode. After disableing drawing mode, the markes can be removed and dragged but not while drawing.

**Comment by codeofsumit** [comment]
@Falke-Design ah I understand. How about that:
- I change the dragging option to false during Marker draw (to align it with other shapes)
- I add `preventMarkerRemoval` option to the drawing modes to disable marker removal on all shapes during draw

Would that be sufficient?

**Comment by Falke-Design** [comment]
Yes great!

**Comment by Falke-Design** [comment]
@codeofsumit have you implemented the changes? It doesn't look like that.

Why Markers and CircleMarkers are enabled by default? The other shapes don't do it either.
So it is a inconsistent use of `enable()` in the drawing mode.

Everyone who want to enable a shape after drawing can achieve this by add `layer.enable()` in the `pm:create` event.
