### ISSUE TITLE
Opt-in functionality

### ISSUE THREAD

**Issue by carueda** [geoman-io/leaflet-geoman#439]
I'm finding difficult to restrict the PM edit/drag/remove functionality to specific layers in my map. In other words, difficulty to exclude other layers (in particular, those created by third-party tools) where the PM functionality is not required at all. The `pmIgnore` mechanism is not really useful in these cases as it would minimally require one to traverse those layers and do something only for purposes of disabling PM functionality for them.

The kind feature request here is to provide an initialization option to indicate the desire for the PM functionality in an *opt-in* fashion. More concretely, something like the following:

- An new option `optIn` (or some other name for the intended effect) for the `addControls` method, of course with default value `false` for backwards compatibility.

- When adding a particular layer in my application, be able to indicate `pmEnable` (with basically the opposite meaning of `pmIgnore`). Example:

    ```js
    L.marker([51.50915, -0.096112], { pmEnable: true }).addTo(map);
    ```

Imho, this would really make your wonderful tool even more appealing!  Thanks!

**Comment by codeofsumit** [comment]
I like it! Marked as a feature request. Please upvote the above post to help me [prioritize feature requests](https://github.com/codeofsumit/leaflet.pm/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22+sort%3Areactions-%2B1-desc).

**Comment by codeofsumit** [comment]
@carueda would be awesome if you could take a look at https://github.com/geoman-io/leaflet-geoman/pull/504 where I'm adding the optIn option.

It basically works like this:
If you call the this after importing leaflet-geoman:
```js
L.PM.initialize({ optIn: false });
```

Only layers that have specifically set `pmIgnore: false` will be handled by leaflet-geoman:
```js
L.marker([51.50915, -0.096112], { pmIgnore: false }).addTo(map);
```

Does that make sense?

**Comment by carueda** [comment]
@codeofsumit Thanks much!  LGTM.  I don't have the cycles now to do proper verification but I trust it's all good. Thanks again.

**Comment by codeofsumit** [comment]
released ✅
