### ISSUE TITLE
Error when providing a "weight" value to hintLine style (leaflet 1.4.0+)

### ISSUE THREAD

**Issue by cosme-benito** [geoman-io/leaflet-geoman#443]
When providing a weight value to the hintLine style the draw doesn't work and the console is filled with Javascript errors. Removing the weight property seems to fix the problem completely. This only started happening after updating leaflet from version 1.3.0

Here's a JSFiddle with the repro steps: https://jsfiddle.net/by8cmhwn/7/

If you click the "Without weight" button you can draw a polygon just fine.
If you click the "With weight" button you can't draw anything and the console is filled with errors

The only difference is the weight value, nothing else.

**Comment by codeofsumit** [comment]
hi @cosme-benito, seems to be a leaflet issue. A PR with a fix was already proposed.
https://github.com/Leaflet/Leaflet/issues/6662

**Comment by cherniavskii** [comment]
Released in 1.6.0

**Comment by cosme-benito** [comment]
This unfortunately still happens in 1.6.0

**Comment by cosme-benito** [comment]
Fixed in !524
