### ISSUE TITLE
Draw Circle not working with CRF.simple (image) source.

### ISSUE THREAD

**Issue by tanthammar** [geoman-io/leaflet-geoman#450]
The circle tool does not work with an image source.
crs: L.CRS.Simple
Ignores second click to set the diameter.

[http://jsfiddle.net/6pof3t7a/](http://jsfiddle.net/6pof3t7a/)

**Comment by tanthammar** [comment]
Can this be added to the source?
Something like, if map.crs = CRF.simple ...

```js
   	L.LatLng.prototype.distanceTo = function(other) {
   	  var dx = other.lng - this.lng;
   	  var dy = other.lat - this.lat;
   	  return Math.sqrt(dx * dx + dy * dy);
   	}
```

Found the solution on the Leaflet Draw git repo.
[https://github.com/Leaflet/Leaflet.draw/issues/611](https://github.com/Leaflet/Leaflet.draw/issues/611)

**Comment by Pentiado** [comment]
Thanks, @tanthammar. You just saved me potentially hours of research : )

**Comment by codeofsumit** [comment]
Hm, @tanthammar I just tried it but honestly I do feel uncomfortable adding a hack like this into the library. It changes the prototype of leaflet functions that could've unintended consequences outside of this plugin. Additionally the source of the problem doesn't seem to be in leaflet-geoman or leaflet.draw according to [this comment](https://github.com/Leaflet/Leaflet.draw/issues/611#issuecomment-255251512).

So my current stand is to let users fix this inside their applications by applying that fix after leaflet-geoman was imported.

Feel free to continue the discussion here in case you disagree. Thanks for reporting and your time 👍

**Comment by haoxl3** [comment]
@tanthammar hello, I use the same method as you, but my cirle also looks bigger,my code looks like this
```javascript
const crss = CRS.Simple;
const zoom = this.map.getZoom();
let circleCenter = {x: 100, y:200}; // pixel
let radius = 50; // pixel

let onCirlePoint = {x: circleCenter.x + radius, y:circleCenter.y};
let myCircleCenter = crss.unproject(circleCenter, zoom);
let circleRadius = crss.unproject(onCirlePoint, zoom);
let len = myCircleCenter.distanceTo(circleRadius);

let layer = L.circle(myCircleCenter, {
     radius: len
});
```

**Comment by tanthammar** [comment]
@haoxl3 

Not sure, Do not recognize my script with yours. Sorry.
