### ISSUE TITLE
Support to fix multiple Self Intersections

### ISSUE THREAD

**Issue by SosthenG** [geoman-io/leaflet-geoman#455]
I use this plugin on a map with a geojson import feature (we just have to paste a geojson to create the layer).
Sometimes the imported geojson have multiple intersections, and when it does, the edit get blocked. When I try to move one of the intersected point, it goes back to its original location because the edit is canceled whenever there is still intersections.

I fixed the issue for me by doing [this](https://github.com/SosthenG/leaflet.pm/commit/143b03f7e42c32610e4c88a00c42c1be25bab3bb).
It seems to work but I don't know if this make sense to you. It it does, I can open a PR for it!

**Comment by codeofsumit** [comment]
Hi there,

have you tried `allowSelfIntersection` yet? At the beginning of your code, add:
```js
map.pm.enableDraw('Polygon', { allowSelfIntersection: true });
map.pm.disableDraw('Polygon');
```

to pass these options to leaflet.pm. The options should be preserved for future draws and edits. After that, add a your geojson and try again. Let me know if it works.

If it doesn't, please provide a JSfiddle that shows the problem.

**Comment by SosthenG** [comment]
Hey! Thanks for your answer and congrats for your wedding :tada: 
Sorry I wasn't clear in my first message, I actually need the selfIntersections to be prevented, I already activated it for my layer :
`layer.pm.enable({ allowSelfIntersection: false });`

I want the user to know when there is a selfIntersection so he can remove it. But my problem is that when I import a layer (from a geojson) that have multiple self-intersections, I can't edit it.
Everytime I try to move a point to remove a self-intersection, it goes back to its previous position because there is still other self-intersections detected.
Here is [a fiddle](https://jsfiddle.net/ygLp7xd1/) that shows the problem.

**Comment by codeofsumit** [comment]
Hmmm yes that is a problem. I will put this as a bug on my list 👍, thanks for the JSfiddle!
