### ISSUE TITLE
hintLineStyle & tempLineStyle not applied when drawing Polygon

### ISSUE THREAD

**Issue by knorke132** [geoman-io/leaflet-geoman#474]
Any hintLineStyle or tempLineStyle you provide is getting overriden by defaults **if** the drawShape is 'Rectangle'

https://jsfiddle.net/obcav6ht/3/

**Comment by knorke132** [comment]
While reading your code i found the option: 'pathOptions' which is getting applied to the Rectangle however you should include this in your documentation

**Comment by codeofsumit** [comment]
Will do - the issue itself is resolved when added to the documentation, right?

**Comment by codeofsumit** [comment]
This has already been documented here:
https://github.com/geoman-io/leaflet-geoman#customize-style

Let me know if that documentation is not sufficient.
