### ISSUE TITLE
Not snapping to shapes added during drawing phase

### ISSUE THREAD

**Issue by prasmo** [geoman-io/leaflet-geoman#477]
Hey,

First, thanks for the great library you've provided. It's helped me a lot to deliver what I have needed.

I've got a use case of trying to snap to a very large vector layer with many individual features. How I am getting around this is to load each feature as required (loading a polygon in on a mouseover).

The problem I've run into is that any shape that is added during the middle of drawing is not able to snapped to. I've tried adding each new shape into a feature group, but that doesn't seem to help either.

I've added a jsfiddle (https://jsfiddle.net/prasmo/0dLvmuto/) that shows the problem. How to replicate - during the middle of drawing a polygon, right click on the map to create a new shape. You should see that the drawing doesn't snap to the new shape.

**Comment by codeofsumit** [comment]
Thanks for reporting. I will take care of it
