### ISSUE TITLE
🎉👍 The Future: leaflet.pm becomes leaflet-geoman

### ISSUE THREAD

**Issue by codeofsumit** [geoman-io/leaflet-geoman#501]
Dear leaflet and leaflet.pm community,

In the past weeks, I've been thinking a lot on how I could spend more time developing this library with all the great features you suggest and I have in my head. I have big ideas that need time and effort. **I have been actively maintaining this library for 4 years now** without any compensation. Mainly because it's fun. I like to solve geospatial problems and I like building products.
That's why I'm trying to find a way to spend more time on it which means I need to generate some revenue. I've looked at the usual OSS maintainers monetizing channels and came up with a plan that I would like to openly share with you.
I'm going to try this out over the coming weeks and months and will see how it goes.

![image](https://user-images.githubusercontent.com/2399810/65829883-4ca96b80-e2aa-11e9-9f70-b528a6b62535.png)

- [x] leaflet.pm will move from my personal account to Geoman.io, a product and company I'm building
- [x] leaflet.pm will be renamed to `leaflet-geoman`, to show it's an OSS product of that company
- [x] I will start to offer a Pro version, `leaflet-geoman-pro`⭐️  targeted at large businesses. Besides a commercial license and dedicated support, it will have features that save business many hours of work and of course money. This revenue helps to make features and fixes for both, the OSS and the Pro version in the future. Over time, the features of the Pro version will trickle down to the OSS version. This is how I want to ensure the OSS version keeps getting better and better. Of course, many features will be released right away in the OSS version.
- [x] I will put a new demo page out in the coming days with a list of planned features and the ability to preorder

**This essentially means, the OSS version of leaflet.pm will become much more awesome, much faster.**

- If you need any of the Pro features for an Open Source project, I'm happy to give you a 100% discount to keep supporting open source
- If you have a small business and need Pro features but can't afford it, contact me. We will work something out.

With this, I hope to make your products better and geospatial management easier for you and your users in a much more professional and dedicated manner.
I would love to hear your honest thoughts on this.

Thanks and have a great Sunday!
Sumit

**Comment by tim-salabim** [comment]
@timelyportfolio Something to watch

**Comment by codeofsumit** [comment]
Everything is live now.
Leaflet-Geoman should be available through npm ([see the docs](https://github.com/geoman-io/leaflet-geoman#documentation)).

As there is no Leaflet-Geoman Pro ⭐️  release yet, I'm offering preorders for 50% off - forever.
So if you or your company knows you will need Leaflet-Geoman Pro in the future, it should definitely be a good deal to get it now.
