### ISSUE TITLE
Events for toolbar buttons.

### ISSUE THREAD

**Issue by alexshnur** [geoman-io/leaflet-geoman#503]
Hello! This would be very useful if there were these events for actions: ['finish', 'removeLastVertex', 'cancel']
As an example:

map.on('pm:CircleMarckerCancel', (e) => {});
map.on('pm:CutFinish', (e) => {});

and other.
Thank you!!

**Comment by codeofsumit** [comment]
great suggestion, thank you! Marked as a feature request 👍

**Comment by Falke-Design** [comment]
Is implemented in Version 2.8.0
