### ISSUE TITLE
How to back to original position when edit canceled  ?

### ISSUE THREAD

**Issue by Dastnbek** [geoman-io/leaflet-geoman#505]

**Comment by codeofsumit** [comment]
When editing starts, store the layers coords and when you want a user to discard changes you apply those original coords again. You can easily do that in your application code.

**Comment by henrikmaa** [comment]
For anyone that has this issue in the future: 

```
//when editing is started, store original coordinates
layer.on("pm:enable",e => {
   let restorePosition = e.target.getLatLngs();
})
```

when you want to perform cancel edit do something like:

```
 //set new position to layer, stop editing to prevent vertexes render old position
 layer.setLatLngs(restorePosition)
 layer.pm.disable()
```
