### ISSUE TITLE
The way editing common edges and vertex

### ISSUE THREAD

**Issue by gostohov** [geoman-io/leaflet-geoman#513]
Polygons with common vertex are not merge in one multipolygon with common edge, they are presented like two separate polygons.

Is there is the way to achieve this behavior while editing ?
![osfxB](https://user-images.githubusercontent.com/12113169/67631516-bd8f7380-f8a8-11e9-8e1b-8e1faab73e59.gif)

**Comment by codeofsumit** [comment]
You mean this, right?
https://github.com/geoman-io/leaflet-geoman/issues/493
