### ISSUE TITLE
Moving circles snap to circle center point

### ISSUE THREAD

**Issue by Rombecchi** [geoman-io/leaflet-geoman#514]
If you try to move a circle placing the cursor away from center, it will snap the circle in the center point after you start drag.
This will not happen moving a polygon, rectangle or whatsoever....
Thanks

**Comment by codeofsumit** [comment]
@Rombecchi the reason is that Circles have only one point to snap to: the center.
Polygons don't have a center point.

You are currently explaining how things behave. Can you explain what you expect to happen instead?

**Comment by codeofsumit** [comment]
I will close the issue for now but lets keep the discussion going. If there comes an action item out of it, we will reopen.
I would still love to know what you expect to happen instead.
