### ISSUE TITLE
Programmatically remove layers - delete all shapes

### ISSUE THREAD

**Issue by Rombecchi** [geoman-io/leaflet-geoman#515]
Hi,
aside the "RemovalMode", is it possible to programmatically delete a single or multiple layer(s)?
How can I delete all shapes from my map?
Thank you so much!

**Comment by codeofsumit** [comment]
Hi, you can do this with leaflet alone:

```js
map.eachLayer(function(layer){
    layer.removeLayer();
});
```

https://leafletjs.com/reference-1.6.0.html#map-eachlayer

**Comment by torrid33** [comment]
Is it possible to delete shapes within a layer and then add more shapes to that layer rather than removing that layer?

**Comment by Falke-Design** [comment]
Not with Geoman. But maybe there is a Leaflet plugin that you can use https://leafletjs.com/plugins.html
