### ISSUE TITLE
Performance issues with geoman and LayersControl

### ISSUE THREAD

**Issue by kev494** [geoman-io/leaflet-geoman#519]
We are loading approx. 4000 CircleMarkers. These are divided into two LayerGroup so we have a basic filter function for these markers. They are loading quite fast, but after we draw a polygon with the geoman library the markers need quite long to render after toggle it within the LayersControl. We also tried it with and without opt-in.

We tried the same feature set with leaflet-draw and hadn't any issues. 

Help would be much appreciated.

**Comment by kev494** [comment]
I tried to recreate it in this jsfiddle: [https://jsfiddle.net/duxn4bLv/](url)

To reproduce this, do the following steps:

1. Check terminals
2. Uncheck terminals (you should see, its quite fast)
3. Draw a polygon
4. Check terminals (its quite slow now)

**Comment by codeofsumit** [comment]
Thanks a lot. Yes we do have a performance issue in certain cases. I will tackle it quite soon.
And thanks also for the demo, that will help!

**Comment by jbccollins** [comment]
Yeah this is my blocker for switching over to this library instead of using leaflet-draw. Wish I knew enough to help fix this :/

**Comment by codeofsumit** [comment]
I found the source for the slowdown 🎉. Working on it as right now

**Comment by jbccollins** [comment]
You are the bomb dot com. <3

**Comment by codeofsumit** [comment]
![perftest](https://user-images.githubusercontent.com/2399810/76544292-13476f80-6488-11ea-91d3-8f4dfb2152b3.gif)

Shit's happening. 👆this is the performance test (first one in the suite) that checks that 6000 markers are handled in under 1 second

**Comment by codeofsumit** [comment]
Made it 👊
Fix is in the next release

**Comment by jbccollins** [comment]
I can't find an option for a one-time donation on your github sponsor page but I'd like to make a small contribution if you're up for adding that option :)

**Comment by codeofsumit** [comment]
Haha PayPal always works 
https://www.paypal.me/sumitkumar/

**Comment by codeofsumit** [comment]
It's done
https://github.com/geoman-io/leaflet-geoman/issues/366#issuecomment-601660278

**Comment by kev494** [comment]
Thanks 🎉

**Comment by jbccollins** [comment]
Fantastic!
