### ISSUE TITLE
Remove Control

### ISSUE THREAD

**Issue by meteerogl** [geoman-io/leaflet-geoman#520]
Now, we are using leaflet.draw and there are lots of layers in used map. I am adding initial layers when opening map as L.FeatureGroup. I tested Geoman in our project. But when I using Geoman and click any layers, after remove mode(in geoman); I can remove all layers. For example 

drawnItems = new L.FeatureGroup();
drawnItems.addLayer(layers.shelves);
layers.walls.addTo(map);

I want to this; User can remove or edit shelves but can not edit or remove wall. How can I do.
Can I enable drawing mode for some specific layers.

**Comment by DazDotOne** [comment]
If you never need to edit certain layers, this is quite trivial to achieve:

~~From the docs~~

````javascript
L.PM.initialize({ optIn: true });

L.marker([51.50915, -0.096112], { pmIgnore: false }).addTo(map);
````

You may need to experiment a little with your `layers.walls` variable though.

**Comment by codeofsumit** [comment]
@DazDotOne thanks for helping out around here! Really appreciate it
