### ISSUE TITLE
pm:drag for vertex

### ISSUE THREAD

**Issue by tarikcarli** [geoman-io/leaflet-geoman#521]
i study on project with leaflet.pm and i can achieve when one of the vertex is moving, i can fire event multiple times. pm:drag provide this functionality for layer all but i am looking for this for vertex. Are there anybody out there to help me ?

**Comment by codeofsumit** [comment]
as soon as a vertex marker is added to the map, you can grab it and add the `pm:drag` event to the marker of that vertex.

```js
// listen to vertexes being added to currently drawn layer (called workingLayer)
map.on('pm:drawstart', ({ workingLayer }) => {
  // working layer should include the markers of all vertexes. You can add the `pm:drag` event to them.
});
```

Let me know if this helps.
