### ISSUE TITLE
Expand on sample documentation

### ISSUE THREAD

**Issue by jasonwinget** [geoman-io/leaflet-geoman#525]
Please add additional examples of how to deal with the data generated by events. Expand on an example of how to use data of creating a line, etc.  I normally understand the 'e' but I am missing the relevant data generated in the event, where is it?  How does someone take this utility to the next level? How do you find your data for storing in a database (not how to store it, but where is the data in the event so a function can be written to do that) for actual real-live use?

map.on('pm:drawend', e => {
  storeMyNewDrawingFunction(e.Something1, e.Something2, etc.);
});

**Comment by codeofsumit** [comment]
Thanks for the feedback. I will improve the documentation on the event payload 👍
