### ISSUE TITLE
simple problem

### ISSUE THREAD

**Issue by mbmamin1996** [geoman-io/leaflet-geoman#527]
hi
i use pm:vertexadded in my js code
and also need to use the pm:markeradded (is my question ) 

pm:markeradded is not working
can you help me to use correct name of that ???

thanks

**Comment by DazDotOne** [comment]
Have you tried hooking into `pm:create` instead?

you should be able to use that event for the same purpose:

````
map.on('pm:create', e => {
    if( e.shape === "Marker" ) {
        // do stuff
       console.log(e.marker._latlng);
    }
});
````

**Comment by codeofsumit** [comment]
There is no `pm:markeradded`. Can you explain what it should to? When it should be fired?
As @DazDotOne mentioned, if you want to know when a Marker was added to the map, `pm:create` is the way to go 👍 

Let me know if there are still questions open
