### ISSUE TITLE
Cursor is odd after adding circle marker on canvas only.

### ISSUE THREAD

**Issue by m1dst** [geoman-io/leaflet-geoman#528]
Using latest leaflet and pm...

If you set preferCanvas to true and add some circle markers, the cursor changes to indicate moving is possible.  It should be a normal cursor to match the non-canvas version.

Gif to show what you should see in the fiddle.
![aaa](https://user-images.githubusercontent.com/958968/71180896-093c1900-226b-11ea-8d21-b12d7727bf96.gif)

Fiddle showing the error.
http://jsfiddle.net/a7o3utrp/

Exactly the same fiddle with canvas disabled.
http://jsfiddle.net/a7o3utrp/1/

Just one more thing I noticed.  Using the fiddle you suggested as a base, the geoman links are not correct and as such it only loads a map and not the toolbar.  Took me a while to work out why.

**Comment by codeofsumit** [comment]
That is weird indeed. Thanks for reporting!

And thanks for the hint with the broken JSfiddle - I will change it!
