### ISSUE TITLE
how to remove  Controls(ToolBar)

### ISSUE THREAD

**Issue by Victoriacsl** [geoman-io/leaflet-geoman#529]
![image](https://user-images.githubusercontent.com/34528097/71344584-e4fb7780-259d-11ea-8714-6012eba82346.png)

Want to clear the tool in the red box, 
Not shown on map

**Comment by lukacg** [comment]
Remove this in your code 
`
ap.pm.addControls({
                position: 'topleft',
            });
`

**Comment by lukacg** [comment]
Remove this from your code 
`map.pm.addControls({
                position: 'topleft',
            });`

**Comment by Victoriacsl** [comment]
The toolbar is used in the previous module. I don't want to delete the next module

**Comment by slekya** [comment]
map.pm.removeControls();
