### ISSUE TITLE
_pmTempLayer not being set during pm:cut event

### ISSUE THREAD

**Issue by AdamJamesNaylor** [geoman-io/leaflet-geoman#531]
I believe I've found a possible issue.
When handling the 'pm:cut' event I've noticed that an additional layer is present. I was expecting one of them to have the _pmTempLayer flag set. Is that the correct behaviour?
In this fiddle https://jsfiddle.net/j9bm6agx/ you can see that undefined gets output twice if you add one polygon and then cut it once.

Expected there to either only be one layer once inside the event handler or one of the two layers to be marked as temp so I can safely ignore it during persisting.

(If I add a timeout delay of 1 second the second layer isn't present in the list of layers.)
Thanks

**Comment by codeofsumit** [comment]
Fixed the fiddle: https://jsfiddle.net/f8602zot/

Thanks for reporting the bug Adam. I'll get on it!
