### ISSUE TITLE
Change pmIgnore after adding geojson

### ISSUE THREAD

**Issue by arshdoda** [geoman-io/leaflet-geoman#533]
Is there any way to modify the pmIgnore after adding the featuregroups.

**Comment by DazDotOne** [comment]
@arshdoda It doesn't seem to be implemented as yet.

I struggled with this quite a bit. I've put an example  of how I worked around it [in an issue I started](https://github.com/geoman-io/leaflet-geoman/issues/516) regarding this feature.

However, I will say that drawing, draging, editing, and deleting are all handled slightly differently.

I'd recommend cloning the repo and looking at how things are done to see what behaviour you need to override.

most of the behaviour is in the L.PM.Map class but could be anywhere.
