### ISSUE TITLE
Enabled edit CircleMarker, then disabled, but it is still draggable

### ISSUE THREAD

**Issue by erhanfirat** [geoman-io/leaflet-geoman#536]
If I make a CircleMarker enable to edit:

```
e.layer.pm.enable({
                snapDistance: this.snapDistance,
                preventMarkerRemoval: true
              });
```

I can move marker successfully. However when I make it disabled it is still draggable.

When I dig into properties of CircleMarker item, I've seen draggable: true

It is same even in Demo: https://geoman.io/leaflet-geoman

EDIT: I have seen this issue only on CircleMarker

**Comment by codeofsumit** [comment]
I can reproduce this for CircleMarkers, but not for Markers - can you show a gif showing the problem on the demo page with a Marker?

Thanks for reporting the bug!

**Comment by erhanfirat** [comment]
@codeofsumit thanks for reply, 
I have edited my report, it is only seen in CircleMarker.
