### ISSUE TITLE
Exists something like onLoad?

### ISSUE THREAD

**Issue by mdbetancourt** [geoman-io/leaflet-geoman#551]
I loaded this library dynamically with "await import('xx')" but sometimes throw Cannot read property 'enableDraw' of undefined when i try do map.pm.enableDraw. So.. exists something like that?

Edit: i solved my problem i think this library wrap, or do something else with the function map so because i loaded this lib after i uses L.map that wrapp never happened then throw that error

**Comment by codeofsumit** [comment]
So you issue is resolved right?
