### ISSUE TITLE
Bug: Circle with CRS.Simple, radius infinite

### ISSUE THREAD

**Issue by beig** [geoman-io/leaflet-geoman#552]
When using a CRS.Simple map, the circle doesn't work.
A circle is added with an infinite radius I think. Don't know how it can be properly described 

https://jsfiddle.net/komzs2fx/

**Comment by beig** [comment]
aplogies for bothering you @codeofsumit 
could I get an estimate on my PR?

**Comment by codeofsumit** [comment]
will check it this week 👍

**Comment by wggley** [comment]
Any status?

**Comment by Falke-Design** [comment]
@wggley @beig we merged this into the develop, it will be in the next release
