### ISSUE TITLE
Strange behavior while cutting 

### ISSUE THREAD

**Issue by Mixser** [geoman-io/leaflet-geoman#555]
Hello, I faced with strange behavior while cutting. I have used the [geoman-editor](https://geoman.io/geojson-editor). I draw a polygon and want to cut a hole (including the one or more edges of polygon). And sometimes the edge is disappearing sometimes not and this is strange. Maybe this behavior relay to issue #396, but i'm not sure.

Expected behavior: the edge should disappear while cutting.

![geoman_bug](https://user-images.githubusercontent.com/1364297/76219093-51ddef80-6226-11ea-8265-c69c0d312ed7.gif)

**Comment by Falke-Design** [comment]
This is a bug of turfjs resp. the library [martinez](https://github.com/w8r/martinez) used from turfjs.
I don't know how to describe that bug, so pls follow the steps.
Look into the [jsfiddle](https://jsfiddle.net/falkedesign/4nhLpb3r/). **Zoom lvl 27!**
1. Click on the Cut button --> The Polygon is nearly cutted correct. (It's not cutted on the correct horizontal line, but has the hole)
2. Move the blue polygon over the line from the red polygon
3. Click on the Cut button --> The Polygon is not cutted correct.

I hope you understand what I mean.

I have no idea how to solve this problem. There are a few [issues ](https://github.com/w8r/martinez/issues)with the difference function and also a PR but I don't know if this helps us.
