### ISSUE TITLE
Snap to 90 Degrees While Drawing/Editing

### ISSUE THREAD

**Issue by bencote** [geoman-io/leaflet-geoman#559]
I would like to be able to hold down a key (Control or Shift) during drawing and editing to for the point to be drawn at 90 degrees (either from vertical or from the previous point).

This is similar to the existing FR #327
https://github.com/geoman-io/leaflet-geoman/issues/327

I don't want an indicator though, I would like the current point to snap to the desired bearing while holding the shift/ctrl key.

My drawing skills are limited but here is an example using Microsoft Word. In this case, the line drawing snaps to vertical, horizontal, and 45 degrees by holding shift, I would like this behavior plus 45/90 degrees relative to the previous point by holding control.

![snap](https://user-images.githubusercontent.com/1199908/76949966-bad8fd80-68df-11ea-844f-cda9d4a7db1c.gif)

**Comment by codeofsumit** [comment]
Marked as Feature Request and closed - please upvote this issue if you would like to see this 👍

**Comment by mike16889** [comment]
I would also like this feature, Maybe have it customizable, like with snap distance but with angle, so for @bencote, he would set it to 45°, but i would want to set it to 15°, others may want to set it to 90°.

Possibly even let users supply an array of points if they don't want it to be a specific amount so it could be like this:

```
{
	snapAngle: true,
	snapAngleInterval: 45
}
```
OR
```
{
	snapAngle: true,
	snapAngleInterval: [45,90,135,180,225,270,315,360]
}
```

**Comment by codeofsumit** [comment]
Love the suggestion Mike 👍. I think that’s definitely the route to go for this feature.

**Comment by AdamJamesNaylor** [comment]
@codeofsumit has any work been progressed on this feature? I will need to be making heavy use of this so would be happy to start a fork to get his implemented?

**Comment by Falke-Design** [comment]
@AdamJamesNaylor give https://github.com/Falke-Design/PMOrtho a try

**Comment by hoanphi2201** [comment]
@codeofsumit Any updated for this feature.

**Comment by Falke-Design** [comment]
@hoanphi2201 there are no updates on this, and it will not implemented soon from our side. You can use the Sub-Library https://github.com/Falke-Design/PMOrtho it is working with the latest version 2.9.0

Same Feature Requests: #559, #327

**Comment by stefanKuijers** [comment]
@codeofsumit Is there still any interest in implementing this? Just asking as I'm not having a lot of luck with PMOrtho thus far.

**Comment by Sunnova-JonnyFriedman** [comment]
Super interested in this feature set. Is this still on the Geoman roadmap??

**Comment by dailyprice** [comment]
This has been added as a feature in Geoman Pro: [Link to docs](https://www.geoman.io/docs/changelog/pro#v2110-added-snapguides)
