### ISSUE TITLE
limitMarkersToCount Problem

### ISSUE THREAD

**Issue by shym88** [geoman-io/leaflet-geoman#560]
Hi,
When i try limitMarkersToCount nothing get happens.

`map.pm.setGlobalOptions({ limitMarkersToCount: 15 });`

I checked leaflet-geoman.min.js there is no attribute such as limitMarkersToCount 
I use 2.4.0 version.

https://unpkg.com/@geoman-io/leaflet-geoman-free@2.4.0/dist/leaflet-geoman.min.js

**Comment by codeofsumit** [comment]
Hi @shym88, yes it's not released yet. Will do so in the coming days

**Comment by codeofsumit** [comment]
@shym88 it's released now 🎉  - v2.5.0 is out

**Comment by shym88** [comment]
Thank you but i tried limitMarkersToCount nothing change, all markers shown.

map.pm.setGlobalOptions({ limitMarkersToCount: 15 });

Also i tried;

 theCollection.pm.enable({
        limitMarkersToCount: 15
});

**Comment by shym88** [comment]
When I checked global options
map.pm.getGlobalOptions() returns above;

{
  "snappable": true,
  "limitMarkersToCount": 15
}

**Comment by codeofsumit** [comment]
Can you create a jsfiddle demonstrating the problem please?

**Comment by shym88** [comment]
I'm sorry I saw wrong.

The application crashed when i setted limitMarkersToCount=5. I have a lot of objects, so I thought nothing changed.

When i click edit button 5 marker is shown for each object. I thought markers open on onyl mouse over (one) object, not each object.

You can see the sample below. However my data is more than sample.
https://jsfiddle.net/seyma/swqfvxem/

Is there a way for open markers only one object?

**Comment by codeofsumit** [comment]
hi @shym88, the option you are looking for is `limitMarkersCountGlobally`.

```
map.pm.setGlobalOptions({ limitMarkersToCount: 15, limitMarkersCountGlobally: true });
```

This feature is currently only available in [Leaflet-Geoman Pro](https://geoman.io/leaflet-geoman#pro) though (which has [additional options to cover large projects](https://geoman.io/blog/performance-for-massive-geodata))

Be aware that in celebration of its launch there is currently a *50% discount* on the Pro library with the discount code `performance`. Let me know if I can assist you in any way 👍
