### ISSUE TITLE
[INFO] globalCutEnabled?

### ISSUE THREAD

**Issue by ad-git** [geoman-io/leaflet-geoman#566]
Why don't exist the function globalCutEnabled like: globalEditEnabled, globalRemovalEnabled and globalDragModeEnabled

Thanks for your fantastic work.

**Comment by codeofsumit** [comment]
Hi @ad-git 

good question, Edit, Removal and Drag are all Global Modes that put all layers into a specific state.
Cut is not like that. It's a shape of the Drawing Mode and is simply subtracted from any intersecting layer.

Anyway, you can check if the user has the Cut Tool enabled with `map.pm.Draw.Cut.enabled()`.
This should also work for the other shapes like `map.pm.Draw.Circle.enabled()`.

Let me know if this works 👍
