### ISSUE TITLE
Cut creates ghost layers that stays permanently on leaflet layers array

### ISSUE THREAD

**Issue by diegosps** [geoman-io/leaflet-geoman#572]
First, thanks for your amazing library! Really helpfull!

Repro https://jsfiddle.net/pj79x3vm:

- Draw two rectangles:
![image](https://user-images.githubusercontent.com/1766388/78594731-3105bb80-781f-11ea-8a40-e05243055265.png)

    - Console shows 2 layers added from draw functions: 2 features with `Polygon` type.

- With a single cut, divide them in half resulting 4 rectangles:
![image](https://user-images.githubusercontent.com/1766388/78594785-47137c00-781f-11ea-935d-501249248679.png)

    - Console shows 4 layers added from draw functions: 2 features with `MultiPolygon` type and 2 feature collections with a single feature each of type `MultiPolygon`.

- Use the removal tool to clear all polygons;

- Check the console: we still have 2 layers as `"FeatureCollection"` returning from `map.eachLayer(layer => { ... })`

Is this the expected behaviour? I guess i can filter by `"Feature"` only.

**Comment by codeofsumit** [comment]
Hmm thanks for reporting this. No that’s definitely not desired. To cut Polygons, I’m using the Turf library in Leaflet-Geoman. There are some other bugs with it and I was hoping a new stable release of Turf will be able to solve most of them but so far no luck. I will take a look if I can mitigate this issue with the existing version.

**Comment by codeofsumit** [comment]
Fixed in the latest release ✅
