### ISSUE TITLE
MarkerCluster Compatibility

### ISSUE THREAD

**Issue by mike16889** [geoman-io/leaflet-geoman#573]
I'm working on converting my project from leaflet.editable to this plugin and so far it has been very painless except for this one issue I am running into.

I am using MarkerCluster and I am calling PM on a layer (inside a cluster) via a popup and am getting the following error on drag-end:

```
Uncaught TypeError: Cannot read property 'enable' of undefined at i.applyOptions (leaflet-geoman.min.js:1)
```
the marker then disappears until MarkerCluster recalculates, It also then makes every marker in the cluster draggable, where my intention was for just that 1 marker to be editable.

Here is a [JSFiddle](https://jsfiddle.net/9g3bekco/)

**Comment by codeofsumit** [comment]
Hi @mike16889 - yes MarkerCluster compatibility was always a problem. As you can see in this PR https://github.com/geoman-io/leaflet-geoman/pull/321 I have attempted this already in 2018 but couldn't finish it at the time. I have to tackle it again in the future.

I've renamed this issue to gather upvotes from the community - this helps me prioritise development 👍 .

**Comment by mike16889** [comment]
@codeofsumit I Have come up with a temporary fix to get around it for now. Still really need this feature as I was hoping to take advantage of 'Pinning' In the near future.

My work around is to temporarily remove the layer from the cluster, add it to the map, then call marker.PM.enable() on it, then in my cancel function, remove it from the map and put it back in the cluster.

something like this:
```
function edit(layer){
	cluster.removeLayer(layer);
	layer.addTo(map);
}

function cancelEdit(layer){
	map.removeLayer(layer);
	cluster.addLayer(layer)
}
```

**Comment by codeofsumit** [comment]
@mike16889 can you contact me via email? sumit@geoman.io - let's see what we can do here

**Comment by francharbo** [comment]
@codeofsumit @mike16889 
Did you manage to work it out ?

geoman looks so cool, but this uncompatibility with markerclustergroup is a real problem.
It also seems that the two of them together makes the application really slow even when geoman is initialized ith optIn: true

**Comment by Falke-Design** [comment]
@mike16889 @francharbo it would be very nice, if you can test the code at the last post on #629. This should make Geoman with MarkerCluster compatible
