### ISSUE TITLE
There are no build instructions

### ISSUE THREAD

**Issue by sorpigal** [geoman-io/leaflet-geoman#574]
I am not a nodejs sort of person, but I can read instructions and follow them. I have been unable to build geoman myself. There are no instructions so I have done some research on how nodejs and webpack stuff works in general, made some guesses, and ended with a mess.

Can someone who knows how this works produce a step by step guide starting with 'git clone' and ending with a newly-built leaflet-geoman.js?

**Comment by sorpigal** [comment]
Aha, it's in CONTRIBUTING. This is not very clear, but maybe I should have read all .md files just in case.

**Comment by codeofsumit** [comment]
Hi @sorpigal, the  CONTRIBUTING.md is Standard on Github for this but I will make sure to link to it in the README file so people have it easier. Thanks for the suggestion 👍

**Comment by Falke-Design** [comment]
It may be helpful to add the npm scripts as well:
```
npm start --> run webpack dev config with watch mode
npm prepare --> run webpack for release
...
```

**Comment by swapnasheela12** [comment]
hi codeofsumit,

i am trying to use your plugin in angular 9 with ngx-leaflate.there show PM object in MAP object but still got this error

Property 'pm' does not exist on type 'Map'.
please guide me for this.

thanks
