### ISSUE TITLE
Why there is not global edit events?

### ISSUE THREAD

**Issue by majsterkoo** [geoman-io/leaflet-geoman#575]
Hi, I have bigger project, where editing layers is not enabled by default. Edit layers can only users with special permissions and is loaded only when user select build mode. Have you any idea, how I can simply add edit event on existing layers? I only need properties of edited layer (polyline). I'm thinking about recreating layers with events when user select build mode, but it seems as dirty solution... Is there any elegant solution or I must "manually" add event to all layers? No other way? :/

Thanks for response.

**Comment by Falke-Design** [comment]
There is a `pm:update` event on the layer: [L.PM.Edit.Line.js#L133](https://github.com/geoman-io/leaflet-geoman/blob/f17acc05d7d78922b8a21ad3e73e3f7d4908db13/src/js/Edit/L.PM.Edit.Line.js#L133) it fires only if there are changes on the layer after disableing edit mode.

Also you a few other events: Scroll to event table after [Edit Mode](https://github.com/geoman-io/leaflet-geoman#edit-mode)
