### ISSUE TITLE
Polygon editing reverse state

### ISSUE THREAD

**Issue by shaan1974** [geoman-io/leaflet-geoman#578]
Sorry but i'm not really an expert with git and maybe my message is not done correctly :)

But i have one question. When we create a polygon and we close it by clicking on the first point.
Is it possible on "pm:create" event to edit again ( plygon.toggleEdit() ) and revert the editing as we don't click on the last point to close the polygon ? ( As picture below )
With event "pm:vertexadded" it's possible with "map.pm.Draw["Polygon"]._removeLastVertex()" but when we click on last point to close the polygon this event is not call. The one called is "pm:drawend".

![](https://www.retroplayers.be/git/polygon.png)

Many thanks.

**Comment by Falke-Design** [comment]
You can reinit the draw polygon with the existing latlngs:
```
map.on('pm:create',function (e) {
  e.layer.removeFrom(map);
  setTimeout(function (){ //Needed because snapping
    map.pm.enableDraw('Polygon');
    var latlngs = e.layer.getLatLngs();
    if(!L.LineUtil.isFlat(latlngs)){
      latlngs = latlngs[0];
    }
    latlngs.forEach(function (latlng) {
      map.pm.Draw.Polygon._createVertex({latlng: latlng})
    })
  },100);
})
```
Example: https://jsfiddle.net/falkedesign/omw2pt34/ draw a polygon

Copy from: https://stackoverflow.com/a/61171500/8283938

**Comment by shaan1974** [comment]
Your my saviour!
Many thanks for your help and the example.
