### ISSUE TITLE
Allow only certain layers to be editable

### ISSUE THREAD

**Issue by jesah** [geoman-io/leaflet-geoman#583]
I dont want to use pmIgnore cause its in the init phase and I need to see other polygons
when I edit one of them and then be able to edit another when a user selects another layer from a list. 

https://jsfiddle.net/x78hkogr/

**Comment by Falke-Design** [comment]
Hi @jesah I have created a library to lock layers: https://github.com/Falke-Design/PMLock

@codeofsumit:
> I think it would help in L.PM.Utils to add
> // filter out layers that don't have the leaflet-geoman instance
>layers = layers.filter(layer => !!layer.pm);
> // filter out everything that's leaflet-geoman specific temporary stuff
>layers = layers.filter(layer => !layer._pmTempLayer);
> // filter out disabled layers
>layers = layers.filter(layer => !layer.pm.enabled());

i would like that too

**Comment by ramirez** [comment]
I still don't understand what enable() and disable() do. They don't seem to do anything for me, and I want to be able to enable or disable layers for geoman programmatically, so I'd ask for this feature to be reopen.

**Comment by Falke-Design** [comment]
I closed this and added it to the feature requests. It will be implemented if enough upvotes

**Comment by ramirez** [comment]
Thanks! I'm using the lock layers plugin and it works for me, but it would be cool to have it integrated directly in geoman. How can I vote?

L.

**Comment by Falke-Design** [comment]
With a 👍

**Comment by ramirez** [comment]
done!

**Comment by Falke-Design** [comment]
A workaround is to remove the `pm` property on the layer:
To disable the layer for Geoman edits:
```
delete layer.pm
```

To enable the layer for Geoman edits:
```
layer.pm = new L.PM.Edit.Rectangle(layer)
```

Or you can use `L.PM.reInitLayer(layer);`  but this is now only in the develop branche available. (But will be released soon 2.8.0)

**Comment by Falke-Design** [comment]
A nice feature would be also to make only certain layergroups editable

**Comment by Falke-Design** [comment]
This feature is added with the Release 2.11.0
