### ISSUE TITLE
Two marker button with different icon?

### ISSUE THREAD

**Issue by hoangeiu** [geoman-io/leaflet-geoman#584]
Hi there,
How can I create two marker button with different icons. I mean how can I extend your code. I know I can do something via Leaflet.EasyButton. But I really want to extend from your code because some features of your code is really nice and I want to keep using it.
Best,

**Comment by codeofsumit** [comment]
Hi @hoangeiu, that should be possible by CSS only.
You can hook into the `pm:create` event for example and apply another CSS class to the marker that changes the icon - something like that should work.
