### ISSUE TITLE
Wrapping geodesic circles at the antimeridian?

### ISSUE THREAD

**Issue by jziggas** [geoman-io/leaflet-geoman#585]
This:

![image](https://user-images.githubusercontent.com/1485767/80997486-64803980-8e0f-11ea-9d33-010101e0d56c.png)

Instead of this:

![image](https://user-images.githubusercontent.com/1485767/80997673-a7421180-8e0f-11ea-8c7d-461cb2ff1f7f.png)

**Comment by Falke-Design** [comment]
Linked in #547
