### ISSUE TITLE
Click to edit the circle or polygon generated according to the data, but the API cannot be triggered. 

### ISSUE THREAD

**Issue by wl001** [geoman-io/leaflet-geoman#586]
Click to edit the circle or polygon generated according to the data, but the API cannot be triggered. Only the graphics drawn by the tool can trigger the API. How can I solve this problem

**Comment by Falke-Design** [comment]
When do you load your data from the API?

The events are triggered by all layers that are created (with the controls but also without the controls) after L.PM is initialized.

So add your data from the API after L.PM is initialized / you see the controls.

If this is not working, please create a jsfiddle and share your code with us.
