### ISSUE TITLE
[Question] How to get the geojson of all features added by Leaflet-geoman

### ISSUE THREAD

**Issue by AnubhabMondal** [geoman-io/leaflet-geoman#605]
HI @codeofsumit ,
 What code should I implement to get geojson all the features added by geoman ?

**Comment by Falke-Design** [comment]
You can get all layers from the map and check if they have the pm property and not temporary layers.

```

function generateGeoJson(){
	var fg = L.featureGroup();    
	var layers = findLayers(map);
        layers.forEach(function(layer){
  	    fg.addLayer(layer);
         });
	console.log(fg.toGeoJSON());
}

function findLayers(map) {
    var layers = [];
    map.eachLayer(layer => {
      if (
        layer instanceof L.Polyline || //Don't worry about Polygon and Rectangle they are included in Polyline
        layer instanceof L.Marker ||
        layer instanceof L.Circle ||
        layer instanceof L.CircleMarker
      ) {
        layers.push(layer);
      }
    });

    // filter out layers that don't have the leaflet-geoman instance
    layers = layers.filter(layer => !!layer.pm);

    // filter out everything that's leaflet-geoman specific temporary stuff
    layers = layers.filter(layer => !layer._pmTempLayer);

    return layers;
  }
```

Demo: https://jsfiddle.net/falkedesign/054go8j2/

**Comment by AnubhabMondal** [comment]
@Falke-Design Thank You very much. Your replay is valuable and that works for me. Now I can export geojson value.
  Can u plz give me an idea of how to import those values into my map for next time? If u share something any code structure that would really very helpful for me.
  Thanks.

**Comment by AnubhabMondal** [comment]
Hi,  @Falke-Design Can you plz share something ..?

**Comment by Falke-Design** [comment]
@AnubhabMondal I created a example for you: https://jsfiddle.net/falkedesign/4fycojbu/ 

This has nothing to do with geoman anymore #close

**Comment by AnubhabMondal** [comment]
Thank You so much @Falke-Design for your help.
