### ISSUE TITLE
Calling toGeoJSON() on a LayerGroup which has had a Layer removed from it should not include the removed Layer.

### ISSUE THREAD

**Issue by AdamJamesNaylor** [geoman-io/leaflet-geoman#607]
https://codepen.io/adamjamesnaylor/pen/YzwpZQp?editors=0010

**Reproduction steps:**
1) Click the map to add a `Marker` (it will be added to the `LayerGroup`)
2) The console will log that two layers are present in the map's `_layers` property. One is the `Marker` and one is the `LayerGroup` containing a copy of the `Marker`.
3) Use the toolbar's remove button to delete the `Marker`.
4) The console will log that the `Marker` has been correctly removed from the `_layers` array but not from the `LayerGroup`.

Consequently, calling `toGeoJSON()` on the `LayerGroup` will incorrectly include the now deleted `Marker`.

**Geoman version:** 2.5.0
**Expected behaviour:**
Calling `toGeoJson()` on a `LayerGroup` that has had a `Layer`/`Marker` removed from it should not include it in the resulting GeoJSON.

**Comment by Falke-Design** [comment]
Hi @AdamJamesNaylor I know what you thinking about but this is in my eyes no Geoman problem. 

You add the layer to a layergroup (that you created) over the event `pm:create`, so you have also remove the layer from the layergroup when `pm:remove` is called.
What I mean is that not Geoman adds the layer to the layergroup, you are adding the layer out of the "Geoman Box", so you have to remove it too.

It will not work to remove the layer from all LayerGroups because maybe the developer / user want to save it in the group and only want that it is not longer displayed on the map. Therefore it does not make sense to delete outside of the "Geoman Box"

@codeofsumit what do you think?

**Comment by AdamJamesNaylor** [comment]
Thanks @Falke-Design but the codepen was just an example.
The layer group (in my use case) is created not by user code but by Leaflet itself when you call `L.geoJSON()`. Arguably the problem still may reside in Leaflet as `removeLayer()` may not do what is expected above.

The use case you describe is interesting - I would find it unexpected to call `removeLayer()` when you only want the layer to no longer display on the map? That seems it would require a different API? Something like `display = false` or some CSS class/rule? I may be misunderstanding the internal intention of Leaflet adding the 'copy' of the layer inside the LayerGroup AND the `_layers` array itself?

I'll try and amend the codepen to more closely reflect my example. Also I might do some tests of Leaflet directly to see if the issue exists there.

**Comment by Falke-Design** [comment]
Yes pls make a new example 👍

But yes in Leaflet if you add a layer to a group or the map (is the same behavior) it is always a copy. This can be negative and positive.

Here is a example (look into the console): https://jsfiddle.net/falkedesign/8puem0jk/

**Comment by AdamJamesNaylor** [comment]
So I've tested with plain Leaflet and the behaviour also occurs there meaning you are correct this is not a Geoman issue 👍 

So I will amend my code to keep track of the LayerGroup returned by `L.geoJSON()` and then call `LayerGroup.removeLayer()` perhaps inside `pm:remove` 👍 

Thanks @Falke-Design, closing.

**Comment by codeofsumit** [comment]
I agree with @Falke-Design explanation. It’s like keeping application state - Geoman makes no assumptions what where you store your data (layergroup, memory, database) - it just manipulates what’s on the map and notifies you about changes.
