### ISSUE TITLE
Ability to union two or more polygons into one

### ISSUE THREAD

**Issue by AdamJamesNaylor** [geoman-io/leaflet-geoman#608]
One of my use cases is the ability for a user to draw two overlapping polygons that can then be combined/merged into a single polygon.

Likely using something like;
`var union = turf.union(poly1, poly2);`

The [documentation](http://turfjs.org/docs/#union) shows an example.

Will need a discussion around how the UX will be handled.

My initial proposal is to;

1. First add the ability for a user to select multiple polygons at once (including a TBD indication of that selection), possibly using the `ctrl` key.
2. Then add a toolbar that appears near/next to the selection including contextual buttons. For now just `union`.
3. Once clicked, the overlap is removed and the resulting single union remains.
4. If no overlap exists nothing happens.
5. No pre-checks are performed (like only showing the button if an overlap exists) as the number and complexity of the polygons selected could be significant.

If this sounds adequate @codeofsumit, I'll get a fork up together.

**Comment by AdamJamesNaylor** [comment]
Initial PR [here](https://github.com/geoman-io/leaflet-geoman/pull/609).

**Comment by Falke-Design** [comment]
Closed and will be implemented if it has enough upvotes
