### ISSUE TITLE
Break/split a Polyline

### ISSUE THREAD

**Issue by arrubiu** [geoman-io/leaflet-geoman#612]
Hi!
Very interesting plugin :)

Is there a way to break/split a Polyline? 

Thanks,
Sergio

**Comment by Falke-Design** [comment]
Hi @arrubiu this is currently being developed as a pro feature

**Comment by codeofsumit** [comment]
The improvement on the current cutting feature to also affect Polylines will be brought to this OSS version as well quite soon 👍 .

Splitting BY Polyline will remain in the Pro version for now.
