### ISSUE TITLE
Question: What is the correct method for adding custom buttons to Geoman?

### ISSUE THREAD

**Issue by AdamJamesNaylor** [geoman-io/leaflet-geoman#614]
Apologies if this is documented somewhere but I was trying to add a custom button to the geoman toolbar which participated in the button toggling that the existing buttons perform.

You can see in this fiddle that the top button toggles any other buttons which are toggled when clicked but not the other way around. Existing buttons do not toggle off the custom button when clicked.
https://jsfiddle.net/Imbick/hxt07L5j/

I may well be doing this completely wrong but couldn't find any documentation on what is the correct technique for this.

**Comment by Falke-Design** [comment]
This week we will release a new Version where you can create custom buttons.
Look into: #602

**Comment by AdamJamesNaylor** [comment]
> This week we will release a new Version where you can create custom buttons.
> Look into: #602

Thanks @Falke-Design, glad to hear it's progressing.
