### ISSUE TITLE
Cut event raised before layers are updated.

### ISSUE THREAD

**Issue by AdamJamesNaylor** [geoman-io/leaflet-geoman#619]
I'm not sure if it's intentional but the `pm:cut` event is raised before the layers are updated with the cut on the map.

You can see the behaviour in this [fiddle](https://jsfiddle.net/Imbick/u6n35rb0/).
When you cut the layer the first console entry shows the state of the map's layers then a second later the updated layers are logged.

If this is intended, perhaps we need a `pm:cutend` event that is raised once the cut is applied?
Right now it's not possible to use an event hook to perform operations (such as `toGeoJSON()` on the resulting cut geometry) without using a brittle `setTimeout()` type workaround.

Happy to raise a PR once it's clear which way round it should be 👍

**Comment by Falke-Design** [comment]
Maybe it would be better if we call the `pm:edit` event when cut is disabled? 

I like your approach of reading out the layers, but please keep in mind that Geoman was never designed to work the way you do. Have you already thought about the way i explained in #605? I think then you will have not so much problems.

**Comment by AdamJamesNaylor** [comment]
Thanks @Falke-Design 
Are you able to point out which part of the code isn't the way Geoman was designed to work?
The way the jsfiddle is reading out the layers is just an example to show the issue - not of any approach being used.
👍

**Comment by Falke-Design** [comment]
Geoman was not designed to have no temporary layers on the map at the time of an event.

I think I will add a function that we can read out the layers at any time.

**Comment by Falke-Design** [comment]
@AdamJamesNaylor please look at #624 if this is working for you

**Comment by Falke-Design** [comment]
Fixed in Release:  `2.7.0`
