### ISSUE TITLE
doubleclick on map get's polygon stuck in "self intersection" state

### ISSUE THREAD

**Issue by smeijer** [geoman-io/leaflet-geoman#631]
When using both `allowSelfIntersection: false`, and `finishOn: dblclick` to finish polygons, the double click gets the polygon stuck in an `intersecting` state.

To reproduce: [jsfiddle](https://jsfiddle.net/smeijer/4x8or2n5/3/)

1. Initialize with:

```js
map.pm.addControls({
  position: 'topleft',
});

map.pm.setGlobalOptions({
  allowSelfIntersection: false,
  finishOn: 'dblclick',
});
```

2. Click the `draw polygon` button

3. Create a polygon with 3 (or more) vertices

4. Finish by clicking the mouse button twice (`dblclick`).

5. Polygon is now stuck in an `intersecting` state, so it can't be closed/finished.

![pm-self-intersect](https://user-images.githubusercontent.com/1196524/87561353-da7d0880-c6bc-11ea-884f-f4a9dfd1feca.gif)

**Comment by smeijer** [comment]
I've updated the title, as it turns out that it doesn't have anything to do with the `finishOn: 'dblclick'` part. Also without that setting, the polygon gets stuck when double-clicking the map.

**Comment by Falke-Design** [comment]
Thx for reporting! This is already fixed in the develop branche https://github.com/geoman-io/leaflet-geoman/pull/621
But I found a new bug in the develop version. When dblclick is called no vertex is created.

**Comment by smeijer** [comment]
That's awesome! 

Regarding your finding. Is that a bug, or a feature? I think it is actually a nice user experience if a double click doesn't add a vertex. Especially in the mode where double click finishes the feature. This would prevent accidental vertex insertions, where users don't won't to add a vertex, but just want to finish the feature.

**Comment by Falke-Design** [comment]
We can discuss about this but I use it to create the last vertex and then finish it at the same time. When I want to finish the polygon without creating a vertex I click on the first marker.

@codeofsumit how do you see that?

**Comment by smeijer** [comment]
Would it be possible to publish a patch or prerelease that contains this bug fix?

**Comment by codeofsumit** [comment]
I will release a patch version within the next few days 👌

**Comment by JamboBuenna** [comment]
@codeofsumit Any idea when this patch is going to go out as an npm package. 
Picked up the code change on develop and this fix works great, but having problems getting our build pipeline working against your dev branch and would prefer to fix to an npm release.

**Comment by codeofsumit** [comment]
Yeah sorry for not having released sooner. I'm on it!
