### ISSUE TITLE
Union functionality

### ISSUE THREAD

**Issue by pate313373** [geoman-io/leaflet-geoman#638]
Hi,

I added a nice functionality with the help of turf to union shapes:

- userGroup is a featureGroup in my case

`function unifyGroup(userGroup){
				var polyList = userGroup.getLayers();
				var unionTemp = polyList[0].toGeoJSON();
				for (var i = 1; i < polyList.length; ++i) {
					unionTemp = turf.union(unionTemp, polyList[i].toGeoJSON());
				}

var fullUnion = L.geoJson(unionTemp);
				userGroup.clearLayers();
				fullUnion.eachLayer(function (layer) {	
					userGroup.addLayer(layer);
				});
			  return userGroup;
			}`

Maybe you want to integrate it. 👍

**Comment by Falke-Design** [comment]
Thx for comment, we will implement in the future a function with that.
Same as: #608
