### ISSUE TITLE
Feature Request: add border while editing marker

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#648]
It would be nice to have a border like Leaflet.Draw has while editing a marker

Like this: 

![Skjermbilde 2020-08-24 kl  13 28 05](https://user-images.githubusercontent.com/39732540/91040053-e5a54b80-e60d-11ea-97bf-7d51fa1402d1.png)

(I know its short, but more description is not needed)

**Comment by Falke-Design** [comment]
You can upvote for [Feature Requests](https://github.com/geoman-io/leaflet-geoman/issues?q=is%3Aissue+is%3Aclosed+label%3A%22feature+request%22+sort%3Areactions-%2B1-desc)

**Comment by Falke-Design** [comment]
Can be easy done, described in: #687

I remove the feature request Tag
