### ISSUE TITLE
Ability to Toggle snapping while drawing/editing

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#651]
It would be nice to turn snapping off while editing and drawing. 

For example: I am currently drawing an object, but now (while drawing) I need to turn snapping off (Same as ALT key, but permanent/until i press button again to enable snapping)

Maybe this is already possible in some way? tried to look at the code, but did not find a good way to solve this?

Thankyou

**Comment by Falke-Design** [comment]
This is already feature of the Pro version `snappingOption`
