### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by rushikmaniar** [geoman-io/leaflet-geoman#652]
got this error while change circle radius (no layers in map except circle)

steps to regenerate :
in your live demo example https://geoman.io/leaflet-geoman

1 . remove all layers using remove layers tool
2. now draw one circle using circle tool
3.  choose edit layers and edit circle radius 
now you will get this error in console

leaflet-geoman.min.js:1 Uncaught TypeError: Cannot read property '0' of undefined
    at i._checkPrioritiySnapping (leaflet-geoman.min.js:1)
    at i._handleSnapping (leaflet-geoman.min.js:1)
    at i.fire (leaflet.js:5)
    at i._onDrag (leaflet.js:5)
    at i.fire (leaflet.js:5)
    at i._updatePosition (leaflet.js:5)

**Comment by Falke-Design** [comment]
Thx for reporting. There is already a PR #627 and will be merged soon

**Comment by Falke-Design** [comment]
Fixed in Release:  `2.7.0`
