### ISSUE TITLE
_hiddenPolyCircle bug with pmIgnore:true

### ISSUE THREAD

**Issue by andrewkazan** [geoman-io/leaflet-geoman#661]
I've changed package leaflet.pm to geoman. And if I was set edit mode (circle or square), and move the cursor on the map, I receive a message:

Uncaught TypeError: Cannot read property '_hiddenPolyCircle' of undefined
    at leaflet-geoman.min.js:4907
    at NewClass.eachLayer (leaflet-src.js:6299)
    at NewClass._createSnapList (leaflet-geoman.min.js:4905)
    at NewClass._handleSnapping (leaflet-geoman.min.js:4850)
    at NewClass._syncHintMarker (leaflet-geoman.min.js:5446)
    at NewClass.fire (leaflet-src.js:584)
    at NewClass._fireDOMEvent (leaflet-src.js:4162)
    at NewClass._handleDOMEvent (leaflet-src.js:4117)
    at HTMLDivElement.handler (leaflet-src.js:2507)

**Comment by Falke-Design** [comment]
We fixed this in the newest Release: `2.7.0` on 03. Sept. Please check it out and tell me if it works.

**Comment by TNLuke** [comment]
I'm seeing this error in the 2.7.0 release, in draw or edit mode, for all shapes other than markers. Doesn't seem to affect anything that I can tell, just generates tons of errors in the console.

**Comment by Falke-Design** [comment]
@TNLuke can you pls create a jsfiddle. I can't reproduce

**Comment by TNLuke** [comment]
Thanks, @Falke-Design. I narrowed it down to a CircleMarker layer that I don't want geoman to work with, so it has the `pmIgnore: true` option. 

https://jsfiddle.net/yk7vuqfL/2/

**Comment by TNLuke** [comment]
Heh, I just added `snapIgnore: true` as well, and it fixed it.

https://jsfiddle.net/yk7vuqfL/3/

**Comment by Falke-Design** [comment]
@TNLuke thx for the example, I fixed the bug in #668
