### ISSUE TITLE
Any examples of how to use with VectorGrid.Slicer?

### ISSUE THREAD

**Issue by Destreyf** [geoman-io/leaflet-geoman#664]
I have a jsfiddle showing a sample of my map, I am wanting to use the VectorGrid.Slicer with Geoman, however it doesn't appear to have any way to edit those layers.

I have a JSFiddle here: https://jsfiddle.net/bcrymwph/ of a very simple geojson using the VectorGrid.Slicer.

I am wondering if anyone has an example of this, the only option i've come up with is to somehow copy the feature/layer i want from the VectorGrid.Slicer into a separate one, but i am wondering if there's a better way or if someone has an example of this.

**Comment by Falke-Design** [comment]
It is not possible to edit it directly, because VectorGrid creates SVG paths and Geoman is working with Leaflet layers. 
To simplify: Geoman working with Leaflet layers before rendering and VercorGrid after rendering

**Comment by Destreyf** [comment]
@Falke-Design 

Thank you for the quick follow up on this, I can do some work on my end to copy the geojson data into a separate layer when they're in edit mode, my plan is to have them select an object to edit, so should be fairly easy to lookup the geojson data and attach it to an existing layer.

**Comment by Falke-Design** [comment]
@Destreyf when it works for you, maybe you can add your code here for other users

**Comment by Destreyf** [comment]
Just following up, I got this to work, my setup is a little different as i'm using ngx-leaflet and some other stuff inside of Angular 10, but i put a fiddle together that is a rough representation of what i'm doing.

https://jsfiddle.net/e9n30q68/4/

Basically on the VectorGrid layer, i have a click event, the `e.layer` property is the "layer" within the VectorGrid plugin, i can see the properties of the clicked object, i lookup the id from the VectorGrid layer on my geojson features and then create a new GeoJSON layer with just the feature itself, add this to an "Edit Layer" which is just used for easy cleanup.

The GeoJSON layer is only created if the user clicks on a shape/feature from the VectorGrid layer _while_ the "Edit Layer" is enabled, this prevents the system from copying layers.

Once you finish editing, it runs an "update" function that patches the geojson object and reinitialize the VectorGrid, thus updating the objects on screen with the changes that were made.

@Falke-Design Thank you for your quick followup as that prevented me from going down a different rabbit hole that wouldn't have been fruitful.

A few notes:
- There's a `toGeoJSON` method on the VectorGrid, but it doesn't appear to work, this is an issue with VectorGrid itself it appears.
- The demo snippet i put together doesn't debounce the edits when you finish, so it runs the seutpVectorGrid function multiple times.
- The geoman plugin is awesome and has fantastic performance for editing!

**Comment by Terrafire123** [comment]
Here's a demo of Leaflet.VectorTileLayer using a Protobuf:
https://jsfiddle.net/Terrafire123/Lgt69ryu/1/
