### ISSUE TITLE
Add to imageOverlay possibilityto being editted

### ISSUE THREAD

**Issue by DimitryD** [geoman-io/leaflet-geoman#673]
Hello,

We're using leaflet-geoman in our project to draw on map some lines, polygons and images.
With polylines and polygons it's working well for us, but with imageOverlay we've faced some lack of support from library...
So, is it possible to add ability to imageOverlay to be dragged and rotated in the edit mode?
And how much time may it take, if you will do it?

Thank you in advance

**Comment by Falke-Design** [comment]
@DimitryD it would be nice when you create a jsfiddle for us. 
Also I can say, that we only will support dragging and no rotating.

**Comment by DimitryD** [comment]
https://jsfiddle.net/em806a14/13/

@Falke-Design here small example with predefined marker, polygon and imageOverlay. 
When we press button on toolbar "Drag layers", we can drag marker and polygon.
But imageOverlay can't be dragged.

**Comment by Falke-Design** [comment]
@DimitryD I created a PR #675, it will be added to the next release

**Comment by DimitryD** [comment]
Thanks a lot for your work @Falke-Design !

But what about 'no rotating'? 
Is it some architectural problems or something else? Because we really need this feature...
And for now we have not found a library that handle rotating applicable to our project
Except leaflet-distortableimage but it has variety of problems and currently we can not use it in production

**Comment by Falke-Design** [comment]
@DimitryD we are not supporting rotation because we have not the time to implement this feature for now. 

If you really need this feature get in contact with @codeofsumit (sumit@geoman.io)
