### ISSUE TITLE
QUESTION: marker plotting

### ISSUE THREAD

**Issue by snc001** [geoman-io/leaflet-geoman#674]
I want to plot one marker at a time.

So once a marker is plotted on the map I want to disable the 'drawMarker' option [like when you click on finish].

I have tried using the listener on the from the map [pm:drawstart] to get the working layer then call [pm:vertexadded] but it doesn't seem to be hitting the vertexadded event. 

I must be using the wrong one so if anyone is able to guide me that would be amazing :)

**Comment by Falke-Design** [comment]
Use:
```
// disable marker draw after a marker is drawn
map.on('pm:create', e => {
  var layer = e.layer;
  if(layer instanceof L.Marker) {
    map.disableDraw('Marker');
  }
});
 ```

From: #445

**Comment by Falke-Design** [comment]
@CptHolzschnauz to have only the latest drawn marker draggable, you can do this:

```
map.pm.setGlobalOptions({
  markerEditable: false,
  continueDrawing: false,
  markerStyle: {
    draggable: true
  }
});

const draggableMarkers = [];
map.on('pm:create', (e)=>{
  if(e.layer instanceof L.Marker && e.layer.dragging){
    draggableMarkers.forEach((marker)=> marker.dragging && marker.dragging.disable());
    // dragging is available because of draggable: true
    e.layer.dragging.enable();
    draggableMarkers.push(e.layer)
  }
})
```

Please make the next time a new issue instead of adding a question in a unrelated issue

**Comment by CptHolzschnauz** [comment]
Thx for your hint. I thought it would be cool to add this hint in under this topic because i found the thread over Google as well. I will do accordingly in the future.
