### ISSUE TITLE
adding pmIgnore to marker does not get ignored by geoman

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#677]
When using pmIgnore on a marker it is not ignored by Geoman.

If you try to add any shape and move it over the marker you will see that it snaps to the marker which is pmIgnore: true

In my own project I loaded Geoman like specified in the docs. 

import L from 'leaflet';
import '@geoman-io/leaflet-geoman-free';

Try to add a shape on the jsfiddle over the marker and it will snap

https://jsfiddle.net/k4y25ht3/1/

**Comment by Falke-Design** [comment]
Add `snapIgnore: true` to the options of the layer.

```
L.marker([58.970471,5.730373], { pmIgnore: true, snapIgnore:true }).addTo(map);
```

Let me know if it works.


@codeofsumit and others: should be snapping disabled if pmIgnore is `true`?

**Comment by henrikmaa** [comment]
> Add `snapIgnore: true` to the options of the layer.
> 
> ```
> L.marker([58.970471,5.730373], { pmIgnore: true, snapIgnore:true }).addTo(map);
> ```
> 
> Let me know if it works.
> 
> @codeofsumit and others: should be snapping disabled if pmIgnore is `true`?

It worked in the jsfiddle, ill try in my project tommorrow, thankyou!

And; I would expect it to be unsnappable if pmIgnore: true, as pm "ignore" should mean it is 100% "removed" from geoman in my opinion
