### ISSUE TITLE
want to disable or lock selected layers for editing or dragging

### ISSUE THREAD

**Issue by rushikmaniar** [geoman-io/leaflet-geoman#679]
How can we disable or Lock Selected Layers for editing or dragging

Steps to regenerate :

1. Created circle and added to map
2. called circle.pm.disable() // want to disable editing layer or dragging layer
3. After Disabling layer I can edit and Drag layer using tools. how can we disable it ?

link : https://codesandbox.io/s/zen-hill-q1evf?file=/src/App.tsx

so i want to disable / lock  selected layers for editing or dragging .

Thank you.

**Comment by Falke-Design** [comment]
There is no way to lock layers.

Take a look here: https://github.com/geoman-io/leaflet-geoman/issues/583

When you want a locking feature add a thumb up to the feature request above.
