### ISSUE TITLE
allowSelfIntersect ignored on finishing cut

### ISSUE THREAD

**Issue by vilup** [geoman-io/leaflet-geoman#680]
Hello I am not sure this is a bug. But when I set globally `allowSelfIntersect: false` or even when i specifically enable Draw.Cut with the `allowSelfIntersect: false` option I am still able to finish an intersecting cut. Edit mode doesnt allow me to intersect, creating intersecting polygons is correctly forbidden and even in Cut mode the line correctly highlights and doesnt let me place an intersecting vertex, but it allows me to finish the cut, which i think it shouldn't. Is it an issue on my part? It works fine in the editor, but i wasnt able to get it working on 2.7 or 2.6.
 
![ignoreIntersect](https://user-images.githubusercontent.com/47676039/95784722-a8d40780-0cd4-11eb-96f4-9a039f375fc8.gif)
Again sorry for the poor video quality. And any help would be appreciated. Thanks

**Comment by Falke-Design** [comment]
I already fixed this for polygons a while ago but I forgot the cutting! Thx for reporting
