### ISSUE TITLE
Change buttons style

### ISSUE THREAD

**Issue by freddie1729** [geoman-io/leaflet-geoman#683]
Is it possible to change the style of the buttons? I prefer the white buttons, as seen in the documentation, however when I use the current version of Geoman, the draw buttons appear with shadow behind the icons.

**Comment by Falke-Design** [comment]
You can overwrite the default css.

What browser are you using? And can you pls share a image which shadow you mean

**Comment by freddie1729** [comment]
Using Chrome. I'd like the draw buttons to look like the zoom buttons I have, if possible.

![image](https://user-images.githubusercontent.com/13642255/96023252-0ccc0c80-0e4a-11eb-90df-d180ead161e5.png)

**Comment by Falke-Design** [comment]
This looks not correct ... 

This is the default:
![toolbar](https://user-images.githubusercontent.com/19800037/96167187-50447a80-0f1f-11eb-90e7-f37eb5b7b916.PNG)
https://geoman.io/geojson-editor

Maybe you overwrite the default css and add the shadow by your own.
