### ISSUE TITLE
Marker editing enabled() func? (dragging.enabled())

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#688]
Hi,

How do I check if a marker is in editing mode/dragging mode(since marker are draggable not editable)?
normal layers can be checked for editing with:

`e.target.pm.enabled()`

but there is no such function for dragging?
am I missing something from docs or should this be added?

Here is a fiddle, put a marker in edit mode then click on it while in edit mode. then e.target.pm.enabled() will return false in console because editing mode is false, but _dragging is true

https://jsfiddle.net/es8p49b1/2/

**Comment by Falke-Design** [comment]
@henrikmaa thx for reporting, this will be fixed in the next release, it should be tested with `enabled()`
