### ISSUE TITLE
Toggle pmIgnore?

### ISSUE THREAD

**Issue by triptec** [geoman-io/leaflet-geoman#702]
Is there a way to toggle pmIngore functionality on different layers?

My use case is basically that I have multiple geojson datasets and they are all shown on the map but I only want a user to be able to remove things from the "active" dataset. When switching active dataset is there a way to do this without having to remove the layer and then re-add it with pmIgnore toggled?

**Comment by Falke-Design** [comment]
There is a feature request for this: #583 else you can try the additional library https://github.com/Falke-Design/PMLock

You have always to add and remove the `pm` property on the layer:
To disable the layer for Geoman edits:
```
delete layer.pm
```

To enable the layer for Geoman edits:
```
layer.pm = new L.PM.Edit.Rectangle(layer)
```

Or you can use `L.PM.reInitLayer(layer);`  but this is now only in the develop branche. (But will be released soon)
