### ISSUE TITLE
Circle marker editing stays stuck on other elements

### ISSUE THREAD

**Issue by alexandreDavid** [geoman-io/leaflet-geoman#709]
If I modify the position of a circle marker and I pass close to a polygon, this one stays stuck on the polygon and impossible to remove it.
Reproducted on the demo

**Comment by codeofsumit** [comment]
Thanks for reporting! Here's a GIF illustrating the problem.

![snap-problem](https://user-images.githubusercontent.com/2399810/99581929-b0788180-29e1-11eb-96f3-4e5baadc9e93.gif)
