### ISSUE TITLE
Problem with events for CircleMarker

### ISSUE THREAD

**Issue by AntreKotik** [geoman-io/leaflet-geoman#712]
For shape CircleMarker event "pm:disable" is fired on start editing and not on its completion. Maybe because of this "pm:update" also doesn't work properly.

For example
```
function onEachFeature(feature, layer) {
            layer.on('dblclick', function (e) {
                e.target.pm.toggleEdit({snappable: false});
            });
            layer.on('pm:enable', e => {
                console.log(e);
            });
            layer.on('pm:disable', e => {
                console.log(e);
            });
        }
```
Here both events are fired at once on Edit mode toggle.

**Comment by AntreKotik** [comment]
A redundant " ! " in line 71 in /src/js/Edit/L.PM.Edit.CircleMarker.js 

` if (!this.enabled()) {
      if (this._layerEdited) {
        Utils._fireEvent(this._layer,'pm:update', { layer: this._layer, shape: this.getShape() });
      }
      this._layerEdited = false;
      Utils._fireEvent(this._layer,'pm:disable', { layer: this._layer, shape: this.getShape() });
    }`

**Comment by Falke-Design** [comment]
Yes I think you are right, I will look at it and then change it 👍
