### ISSUE TITLE
preventMarkerRemoval bug? - Prevent removal of first and last vertex on polyline and polygon?

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#714]
Using preventMarkerRemoval right click to remove vertex, you can accidentally delete a Polyline or polygon.

For example Polyline requires 2 vertexes. If you right click it is "deleted" (actually still an object but cant be visible on map anymore because of missing position).

In my opinion it should not be allowed to remove first and last vertex of polyline?
The issue is the same for polygon if you dont have a total of 3 vertexes left. Not sure how to fix polygon tho..

Do you guys agree that this should be prevented?

**Comment by Falke-Design** [comment]
This is the expected behaviour. 
The layer has no more coords and is also removed from the map. So there is no more reference on the map to the layer -> layer is deleted.

If this is wanted to prevent we can add a option for this.

**Comment by henrikmaa** [comment]
I think it would be benificial  for geoman to have an option for it. And maybe an option to set an amount of time you need to hold the vertex until it deletes on touch devices?

**Comment by Falke-Design** [comment]
Good idea, I will take a look on it

**Comment by henrikmaa** [comment]
Just want to give kudos @Falke-Design for all your help! Latest release 2.8.0 works great as well!

**Comment by henrikmaa** [comment]
Would it be a good idea to also listen for if `marker.on('move', this._onMarkerDrag, this)`; has been fired? I think so to further prevent deletion of vertex.  

For example, lets say long-tap requires to hold for 2 seconds. Then you drag around the vertex, releases after 3 seconds, now the vertex is deleted. 

Listen to onMarkerDrag: drag the vertex for 3 seconds, (markerDrag is firing while dragging, preventing the long tap). Vertex is not deleted.

Or maybe there is a better way to handle deletion of vertex on touch overall?
