### ISSUE TITLE
Can I set vertex styles using pathOption?

### ISSUE THREAD

**Issue by henrikmaa** [geoman-io/leaflet-geoman#717]
Can I change styling of vertex with pathOptions or ideally Something like this, or do I need to change css directly?

```
layer.pm.enable({
        snappable: true,
        allowSelfIntersection: false,
        snapDistance: 20,
        preventMarkerRemoval: false,
        vertexStyle: {
         size: [20,20]
         }
      });
```

I tried to use MarkerStyle which I saw was in the demo, but it does not seem to do anything? Or it only works while drawing?

```
layer.pm.enable({
        snappable: isSnapping,
        allowSelfIntersection: false,
        snapDistance: 20,
        preventMarkerRemoval: false,
        markerStyle: {
          opacity: 0.5,
          draggable: false,
        }
      });
```

**Comment by Falke-Design** [comment]
A vertex marker is completly styled in css:
https://github.com/geoman-io/leaflet-geoman/blob/ff58d546ae5807a331485c16b5ac442b6bbce527/src/css/layers.css#L1-L19

the `markerStyle` option is only to style the marker layer of `enableDraw('Marker')`
