### ISSUE TITLE
Problem with default icon marker - Fix Tooltip position #708

### ISSUE THREAD

**Issue by mbisurgisoshace** [geoman-io/leaflet-geoman#718]
Hi, I think that the PR that I am mentioning (#708) has some issues. We were using everything fine till 2.7, and 2.8 generates this error when we try to load our app, and the logs in the browser console mentioned the L.Icon.Default(). Here is the image of the error. 
<img width="360" alt="Captura de Pantalla 2020-12-03 a la(s) 17 48 10" src="https://user-images.githubusercontent.com/44878235/101086640-ee53d900-358f-11eb-8448-e8332a9cf8ce.png">

Thanks very much!

**Comment by Falke-Design** [comment]
What leaflet version are you using?

**Comment by mbisurgisoshace** [comment]
I tried switching to leaflet 1.7.1 (version you are pointing in the commit) we are also using react and react-leaflet. But as I mentioned, till 2.7 everything was working fine!

**Comment by Falke-Design** [comment]
And what Version are you now using? 
Have you defined `L` as a global variable?
can you create outside of geoman a icon with `var icon = new L.Icon.Default()`?
Can you please create a sandbox? [Demo](https://codesandbox.io/s/angry-babbage-cns52?file=/src/App.tsx) it worked for me on this demo

**Comment by mbisurgisoshace** [comment]
Hi, thanks for your help! I matched all the versions on your demo, and now its working again! 
Thanks.
