### ISSUE TITLE
L.Util.throttle is not a function

### ISSUE THREAD

**Issue by skorzyk** [geoman-io/leaflet-geoman#727]
hey after posting a minified plugin geoman keep popping up new bugs missing features. e.g. L. Util. throttle is not a function. I use various other plugins, is there a conflict between plugs?

**Comment by Falke-Design** [comment]
No it shouldn't. This is a default Leaflet function.

Which leaflet version are you using? Frameworks React, Vui, Vanilla?
Is it possible for you to create a demo? On jsfiddle.net for example

**Comment by skorzyk** [comment]
for leaflet versions we are using old 0.7. As for the demo, it will be hard because it is a large application .. We are using only js and jquery

**Comment by Falke-Design** [comment]
Can you not update to 1.7.1? Geoman will not work else. 

It would be a good choice to change the version too, because leaflet has improved performance and a lot of good features.

**Comment by skorzyk** [comment]
We have plan to update leaflet. You think it can be a reason that errors?

**Comment by Falke-Design** [comment]
Yes sure.
Here the doc for [0.7.x](https://leafletjs.com/reference-0.7.7.html#util) without `L.Util.throttle`
And here the doc for [1.7.1](https://leafletjs.com/reference-1.7.1.html#util-throttle) with `L.Util.throttle`
