### ISSUE TITLE
How to edit / enable only a specific LayerGroup with edit control?

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#731]
Hi, I couldn't find any options in leaflet.pm to assign editable layer control  into a specific Layer Group like leaflet.Draw doing. see the below example.
```
var drawLayerGroup = L.featureGroup().addTo(map);
var options ={
position:'topright',
 edit:{ featureGroup: drawLayerGroup  , remove:false} // <--------
}
var drawControl = new L.Control.Draw(options);
map.addControl(drawControl );
```
So, Is there any way I can achieve the above code using leaflet.pm library?

**Comment by Falke-Design** [comment]
It is not possible to edit only certain layers. Maybe in future.

Workarounds: https://github.com/geoman-io/leaflet-geoman/issues/583

**Comment by CityBelfast** [comment]
Sorry, I'm getting an error due to undefined .getTranslation method (see the below error). I'm just wondering whether  it is something related to free version! can we create Custom EditLayer Control using the free version of leaflet.pm?
![image](https://user-images.githubusercontent.com/76213912/102775035-ff6c5a80-4383-11eb-957c-200b373d0383.png)

**Comment by Falke-Design** [comment]
It looks like, that are you not using the latest release. You can check this in the console with `L.PM.version` it should be 2.8.0

Maybe you are not importing the correct package. The project changed the name from leaflet.pm to leaflet-geoman. So please check if your are using the corret package while importing

**Comment by CityBelfast** [comment]
Yes, It was my mistake. i was using leaflet.pm version
