### ISSUE TITLE
Base map get dragged/moved other than the rectangle layer 

### ISSUE THREAD

**Issue by geohuz** [geoman-io/leaflet-geoman#735]
I'm using the leaflet-geoman with my svg indoor floorplan map in pixel coordinates, my code as below:
```
const screenWidth = 1200 
export default function App() {
  const svgRef = useRef()
  const mapContainerRef = useRef()

  const baseMapRef = async (node) => {
    if (node!==null) {
      const MAP = L.map(mapContainerRef.current, {
        crs: L.CRS.Simple,
        minZoom: -1,
        maxZoom: 10,
        zoom: 1,
      })
      
      let bb = node.getBBox()
      let width = bb.width
      let height = bb.height
      let whRatio = width / height
      let screenHeight = screenWidth / whRatio

      mapContainerRef.current.style.width = `${screenWidth}px`
      mapContainerRef.current.style.height = `${screenHeight}px`

      select(svgRef.current)
        .attr('width', width)
        .attr('height', height)
        .attr('viewBox', `0 0 ${width} ${height}`)

      let yx = L.latLng;
      const xy = (x, y) => {
        if (L.Util.isArray(x)) {
          return yx(x[1], x[0])
        }
        return yx(y, x)
      }
      let mapBounds = [xy(0, 0), xy(width, height)]
      
      MAP.fitBounds(mapBounds)
      
      L.svgOverlay(svgRef.current, mapBounds, {interactive: true})
        .addTo(MAP)

      MAP.pm.addControls({
        drawMarker: true,
        drawPolygon: true,
        editPolygon: true,
        deleteLayer: true,
        drawPolyline: true
      })

  return (
    <div ref={mapContainerRef}>
      <svg ref={svgRef}>
        <SVG innerRef={baseMapRef} src={require('./mymap.svg')} />
      </svg>
    </div>
  )
}
```

here is the video: https://user-images.githubusercontent.com/730770/102953301-f0b0af80-450b-11eb-935b-a77f1ed80889.mov

You can see after the basemap get dragged, you can never drag the rectangle layer.

**Comment by Falke-Design** [comment]
It would be nice, if you create a demo for us in vanilla js on: https://jsfiddle.net/o1dwu2vg/

**Comment by Falke-Design** [comment]
Here is a example: https://jsfiddle.net/falkedesign/u80dsh2j/

This is not really a bug from us. The Problem is that a SVGOverlay is acting like a layer. So when you create the rectangle it is on top of the svg but when you drag the svg, it is moved to the front and then it is always above the rectangle. Normally you wouldn't see the rectangle anymore, but your svg is transparent so the change from the front in the back is not visible.

When you call `svg.bringToBack()` you can drag the rectangle again

**Comment by geohuz** [comment]
Thanks @Falke-Design ! I will make adjustment on my side.
