### ISSUE TITLE
Edit button doesn't have cancel button

### ISSUE THREAD

**Issue by shoeb8997** [geoman-io/leaflet-geoman#736]
In my use case, when user enables the edit mode and changes the shape of layer wrongly.He doesn't have a option of cancel button to revert the changes back.below is the way I  want cancel button with the undo functionality for the layers.

![image](https://user-images.githubusercontent.com/28921782/102975956-d9cb8680-4526-11eb-980f-f3d9eff18194.png)

**Comment by Falke-Design** [comment]
There is already a Feature Request for this: #320 Upvote, if it should be implemented.
