### ISSUE TITLE
Incorrect hint when drawing polygon

### ISSUE THREAD

**Issue by diadenchuk** [geoman-io/leaflet-geoman#742]
When a user starts drawing the polygon, he gets a hint 'Click to continue drawing', and once a user has drawn at least three vertices the hint changes to 'Click the first market to finish'.
But if a user decides to remove the last vertex, and there're only two vertices left which mean the polygon cannot be finished, the hint has to be again 'Click to continue drawing' but instead the user still sees 'Click the first market to finish' although there are only two or even one vertex on the map.

![image](https://user-images.githubusercontent.com/12237813/103347619-291e3380-4aa0-11eb-945c-cc4f7391e36d.png)

**Comment by Falke-Design** [comment]
Thx for reporting, I will fix this
