### ISSUE TITLE
Demo folder / example improvements

### ISSUE THREAD

**Issue by do-me** [geoman-io/leaflet-geoman#749]
Noticed two things in [demo folder / example](https://github.com/geoman-io/leaflet-geoman/tree/master/demo):

- Leaflet tiles aren't loading 
- Why not use CDN by default in demo? Would be nice to have an out-of-the-box example after cloning without tweaking around first.

**Comment by Falke-Design** [comment]
I will add the CDN as comment but not as default source, because this are the demos for the local builded geoman

**Comment by Falke-Design** [comment]
I will close this, if I fixed it
