### ISSUE TITLE
While trying to create a polygon within a polygon, if the cursor is near the parent or a nearby boundary, the cursor is sticking to that nearby boundary

### ISSUE THREAD

**Issue by shoeb8997** [geoman-io/leaflet-geoman#750]
My usecase is While trying to create a polygon within a polygon, if the cursor is near the parent or a nearby boundary, the cursor is sticking to that nearby boundary

**Comment by Falke-Design** [comment]
This is the feature **Snapping**, you have a few options in the [drawing mode](https://github.com/geoman-io/leaflet-geoman#draw-mode). You can disable it with `snappable: false` or reduce the distance to the snapped layer `snapDistance: 20`. 

```
// enable polygon draw mode  
map.pm.enableDraw('Polygon', {  
  snappable: false,  
  snapDistance: 20,  
}); 
```


Also you can ignore snapping on created layers with `snapIgnore: true` --> `layer.options.snapIgnore = true`
