### ISSUE TITLE
LineString disappear when click edit button

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#751]
Hi, I'm facing some issue on the drawing tool with following drawing options. If click on the layer edit button then the border get disappear from both polygon and line string. As a result, the lineString is not visible on the map. I'm not sure is it something do with the drawing tool options?

```
  var drawOptions = {snappable: true,snapDistance: 30,snapMiddle: true,allowSelfIntersection: false,
            templineStyle: { color: 'red', },
            hintlineStyle: { color: 'blue', dashArray: [5, 5] },
            pathOptions: { color: 'red', fillColor: 'orange', fillOpacity: 0.7 },
            markerStyle: { opacity: 0.9, draggable: false, icon: bulletRedMarker },
            cursorMarker: true,
            finishOn: 'contextmenu',
            finishondoubleclick: true,
            layerGroup: drawLayerGroup1
        };
        map.pm.setGlobalOptions(drawOptions)
        map.pm.disableDraw();
        map.pm.addControls({ editMode: true, oneBlock: false, cutPolygon: false, drawCircleMarker: false });
```

![image](https://user-images.githubusercontent.com/76213912/104242442-14a24980-5457-11eb-8bb2-da612c214ecb.png)

After clicking Edit layer button
![image](https://user-images.githubusercontent.com/76213912/104242497-2683ec80-5457-11eb-9dfc-817a5e195049.png)

**Comment by CityBelfast** [comment]
https://user-images.githubusercontent.com/76213912/104245671-9648a600-545c-11eb-9d29-31609c348d23.MOV

**Comment by CityBelfast** [comment]
https://user-images.githubusercontent.com/76213912/104247483-d1000d80-545f-11eb-9975-737f08c82723.MOV

**Comment by Falke-Design** [comment]
This is a bug in geoman, you can fix it, when you use `#f00` instead of `red`:
```
 pathOptions: { color: '#f00', fillColor: 'orange', fillOpacity: 0.7 },
```
