### ISSUE TITLE
Polygon, Rectangle  and Linestring geometries turn into Edit mode when I put second marker on the map

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#752]
Hi,
There is an issue I found while dropping more than one marker on the map. As soon as I place the second marker on the Map all the geometries turn into edit mode. see the below attached screenshots. 

When drop 1 marker on the map
![image](https://user-images.githubusercontent.com/76213912/104244312-10c3f680-545a-11eb-8857-08ee5fa2deb1.png)

If I drop second marker on the screen all the geometry turn into edit mode
![image](https://user-images.githubusercontent.com/76213912/104244416-423cc200-545a-11eb-8a34-86d7ef8eaccc.png)

here is my drawing tool configuration
![image](https://user-images.githubusercontent.com/76213912/104246438-e96f2880-545d-11eb-9170-4249c30cd798.png)

**Comment by CityBelfast** [comment]
see the attached video clip

https://user-images.githubusercontent.com/76213912/104246221-8087b080-545d-11eb-9826-f56547854b51.MOV

**Comment by Falke-Design** [comment]
This should be fixed in Version [2.9.0](https://github.com/geoman-io/leaflet-geoman/releases/tag/2.9.0), what version are you using?

**Comment by CityBelfast** [comment]
I'm using 2.8.0 version. Thanks
