### ISSUE TITLE
Question: metric & showArea options for the drawn shapes

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#757]
Hi,
Would it be possible to set **metric** option, which determines which measurement system and **showArea** option, which shows the area of drawn polygon in m3 or km2, I'm able to do it the same using leaflet.draw tool. but I'm not sure how to do it using geoman drawing tool. I tried it the following way; but it's not working
map.pm.Draw.Polygon.setPathOptions({ showArea: true, metric: true });

Shows Measurement system and Area of geometry while drawing shape using leaflet
![image](https://user-images.githubusercontent.com/76213912/104574162-a378b700-564d-11eb-9ad0-f562d2723934.png)

--

**Comment by Falke-Design** [comment]
The [measurement options](https://github.com/geoman-io/leaflet-geoman#measurement-) are only available in the [Pro ⭐ Version](https://geoman.io/leaflet-geoman-pro).

You need to create your own code for that if you don't want to pay for the pro version.

I think the events `pm:vertexadded` and `pm:centerplaced` can be useful for that

**Comment by CityBelfast** [comment]
thanks for the update
