### ISSUE TITLE
Ignore LayerGroup for edit

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#758]
I'm facing an issue with a drawing tool. I have assigned my tool to a separate layerGroup called $drawItemsLayerGroup (see the below code for the tool);

```
let **$drawItemsLayerGroup** = new L.layerGroup().addTo(map);                   
let drawOptions = {
templineStyle: { color: '#000', weight: 2 },
cursorMarker: true, 
finishondoubleclick: true,
layerGroup:**$drawItemsLayerGroup** };
map.pm.setGlobalOptions(drawOptions)  
map.pm.addControls({ editMode: true, oneBlock: true});   
map.pm.Draw.Polygon.setPathOptions({ snapIgnore : true,groupName: "editBoundary" });
map.pm.Draw.Rectangle.setPathOptions({ snapIgnore : true,groupName: "editBoundary" });
map.pm.Draw.Line.setPathOptions({ snapIgnore : true, groupName: "editBoundary"});
map.pm.Draw.Circle.setPathOptions({ snapIgnore : true, groupName: "editBoundary" });  

map.on('pm:create', function (e) {  
   e.layer.groupName = e.layer.options.groupName;                       
});
```

![image](https://user-images.githubusercontent.com/76213912/104620930-747f3700-5687-11eb-962a-e286a5fcc053.png)

At the same time, I have loaded a collection of features into a different layer Group called otherLayerGroup and attached it to the map. But when I click on the edit layer button, I expect only $LayerDrawItems group be editable; but here  the entire geometries turn into edit mode. see the below code and images. I'm not sure why second layer group get editable when I click edit tool, which is assign to different layerGroup.

```
 let otherLayerGroup = new L.layerGroup().addTo(map);
 let features= JSON.parse(result);
 L.Proj.geoJson(otherLayerGroup , { style: { stroke: false, fillOpacity: 0.4 } }).addTo(otherLayerGroup );
```

![image](https://user-images.githubusercontent.com/76213912/104621151-af816a80-5687-11eb-9134-ad713ce7ef24.png)

**Comment by Falke-Design** [comment]
The LayerGroup that you add to the options, are only where the drawn layers should be added. It has nothing to do what you can edit / delete / cut.

`pmIgnore` is what are you searching for:

```
 L.Proj.geoJson(otherLayerGroup , { style: { stroke: false, fillOpacity: 0.4, pmIgnore: true} }).addTo(otherLayerGroup );
```

**Comment by CityBelfast** [comment]
thanks

**Comment by CityBelfast** [comment]
would it be possible to set pmIgnore=true by default globally ?

**Comment by Falke-Design** [comment]
Yes with: `L.PM.setOptIn(true);`
And with `L.marker([0,0],{pmIgnore: false})` you can enable it for Geoman -> means: not ignored, so editable

**Now it depends what you want:**
1. If you want that the drawn layers can be edited, you need to add this:
```
map.pm.setGlobalOptions({pathOptions: {pmIgnore: false}, markerStyle: {pmIgnore: false}})
```

2. If they should be editable but not snappable:
```
map.pm.setGlobalOptions({pathOptions: {pmIgnore: false, snapIgnore: true}, markerStyle: {pmIgnore: false, snapIgnore: true}})
```

3. If the drawn layers should be ignored / not editable:
**Normaly you don't need to do anything**, but there is a bug so use this workaround: 
```
map.pm.setGlobalOptions({pathOptions: {pmIgnore: false}, markerStyle: {pmIgnore: false}})
map.on('pm:create',(e)=>{
       e.layer.options.pmIgnore = true;
       delete e.layer.pm
    })
```

**Comment by CityBelfast** [comment]
This is really helpful. thanks a lot for the update.

**Comment by CityBelfast** [comment]
I tied to do the way you have suggested for setting up pmIgnore:true and snapIgnore: false,  in the L.Proj.geoJson. 
But For some reason snapping got broken. here are the different codes that I've tried at my end.
1.
var geoJson = new L.geoJson(data, {                       
                        style: {color: 'blue',  weight: 1,fillColor:'#000',fillOpacity: 0.2,pmIgnore: true, snapIgnore: false,}
                    });
 snapLayerGroup.addLayer(geoJson);

Also I tried those two options outside the style options.
2. 
var geoJson = new L.geoJson(data, {
                        pmIgnore: true, 
                        snapIgnore: false,                       
                        style: {color: 'blue',  weight: 1,fillColor:'#000',fillOpacity: 0.2,}
                    });
 snapLayerGroup.addLayer(geoJson);

**here are my settings.**
var drawOptions = {
            snappable: true,
            snapDistance: 30,
            snapMiddle: true,
            allowSelfIntersection: false,
            templineStyle: { color: '#CE0048', },
            hintlineStyle: { color: '#24F262', dashArray: [5, 5] },
            pathOptions: { color: '#CE0048', fillColor: '#FCDCA1', fillOpacity: 0.7 },
            markerStyle: { opacity: 0.9, draggable: false, icon: bulletRedMarker },
            cursorMarker: true,
            finishondoubleclick: true,
            layerGroup: drawLayerGroup1
        };
        map.pm.setGlobalOptions(drawOptions)
        map.pm.addControls({ editMode: true, oneBlock: false, cutPolygon: false, drawCircleMarker: false });
          map.pm.Draw.Polygon.setPathOptions({ color: 'green', groupName: 'example', snapIgnore: true, pmIgnore: false,  });
        map.pm.Draw.Line.setPathOptions({ color: '#CE0048', groupName: 'example', snapIgnore: true, pmIgnore: false,  });
        map.pm.Draw.Circle.setPathOptions({ color: 'green', groupName: 'example', snapIgnore: true, pmIgnore: false,  });

![image](https://user-images.githubusercontent.com/76213912/104645383-e31fbd00-56a6-11eb-928c-c61b1980939c.png)

**Comment by Falke-Design** [comment]
If `pmIgnore: true` is set on a layer snapping can not be enabled. With `pmIgnore: true` geoman can not find this layer.

What do you want exactly?

**Comment by CityBelfast** [comment]
I need to disable the layer editing and enable snapping for the layer I have loaded on the map

**Comment by Falke-Design** [comment]
Today in Geoman it is not possible to "lock" layers, so I created a while ago a sub plugin for this: [PMLock](https://github.com/Falke-Design/PMLock)

Add the plugin src to you html:
```
    <script src="https://cdn.jsdelivr.net/gh/Falke-Design/PMLock@latest/js/pmLock.js"></script>
```
and then use this code:
```
    pmLock = new L.PMLock(map,{showControl: false})
    var geoJson = new L.geoJson(data, {
      style: {color: 'blue',  weight: 1,fillColor:'#000',fillOpacity: 0.2, pmLock: true}
    });
    snapLayerGroup.addLayer(geoJson);

    var drawOptions = {
      snappable: true,
      snapDistance: 30,
      snapMiddle: true,
      allowSelfIntersection: false,
      templineStyle: { color: '#CE0048', },
      hintlineStyle: { color: '#24F262', dashArray: [5, 5] },
      pathOptions: { color: '#CE0048', fillColor: '#FCDCA1', fillOpacity: 0.7 },
      markerStyle: { opacity: 0.9, draggable: false,}, // icon: bulletRedMarker },
      cursorMarker: true,
      finishondoubleclick: true,
      layerGroup: drawLayerGroup1
    };
    map.pm.setGlobalOptions(drawOptions)
    map.pm.addControls({ editMode: true, oneBlock: false, cutPolygon: false, drawCircleMarker: false });
    map.pm.Draw.Polygon.setPathOptions({ color: 'green', groupName: 'example'  });
    map.pm.Draw.Line.setPathOptions({ color: '#CE0048', groupName: 'example' });
    map.pm.Draw.Circle.setPathOptions({ color: 'green', groupName: 'example'  });
```

**Comment by CityBelfast** [comment]
Thank you, I will try it via L.PMLock then.

**Comment by CityBelfast** [comment]
Hi,  I've noticed PMLock doesn't work if user do following steps
1. Turn OFF Underneath transparent features (i.e. disable invisible snapping layer)
2. Press Edit Layer button
    **result**:  only one geometry for edit  (see the below image) 
 ![image](https://user-images.githubusercontent.com/76213912/106183818-aa004600-6198-11eb-893c-e3f33b61e535.png)

3.  now Turn ON the Underneath Features for snapping then all the features turn into Edit Mode. (see the below picture)
![image](https://user-images.githubusercontent.com/76213912/106184229-27c45180-6199-11eb-8d47-3fab6d343ce2.png)

here is my code

const pmLock = new L.PMLock(state.Map);      
     function layerGroupSnapoadAlltheFeatures (result) {
		L.Proj.geoJson(result, style: { pmLock: true }}).addTo(fn.layerGroupSnap);
	}
