### ISSUE TITLE
pmIgnore check & Opt-In draw Bug

### ISSUE THREAD

**Issue by Falke-Design** [geoman-io/leaflet-geoman#759]
While drawing and `L.PM.setOptIn(true)` an error is thrown: `layer.pm undefined`

https://github.com/geoman-io/leaflet-geoman/blob/7cdb0edadc800edf3498fe6f78d140bccaa0aaa9/src/js/Draw/L.PM.Draw.js#L176-L184

Needs to be:
```
  _finishLayer(layer){
    if(layer.pm) {
      // add the pm options from drawing to the new layer (edit)
      layer.pm.setOptions(this.options);
      // set the shape (can be a custom shape)
      layer.pm._shape = this._shape;
    }
    this._addDrawnLayerProp(layer);
  },
```

-----

Also layers with `pmIgnore: true` should not be editable / moveable / deleteable

https://github.com/geoman-io/leaflet-geoman/blob/7cdb0edadc800edf3498fe6f78d140bccaa0aaa9/src/js/Mixins/Modes/Mode.Removal.js#L5-L8

https://github.com/geoman-io/leaflet-geoman/blob/7cdb0edadc800edf3498fe6f78d140bccaa0aaa9/src/js/L.PM.Utils.js#L12-L33

**Comment by brugsel** [comment]
Also running into the same problem. Any timeline on when the fix will be released?

**Comment by Falke-Design** [comment]
@brugsel we want to publish the release this week.
