### ISSUE TITLE
Pointer Cursor not applied when using canvas while delete mode

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#765]
Hi, 
I need to click 6 or 7 click on  line geometry to delete it from the map.  please see the below video.  is there anyway I can change the default cursor to a pointer when mouse-over the line geometry?

https://user-images.githubusercontent.com/76213912/105099937-66c11b80-5aa4-11eb-8763-1bb285a8a296.MOV

**Comment by Falke-Design** [comment]
I'm confused.

It should be already working correct with the cursor. You can see it here, it is using canvas: https://jsfiddle.net/falkedesign/xgr1q03o/

Please look if the css class `leaflet-interactive` is added to the canvas:
![grafik](https://user-images.githubusercontent.com/19800037/105395388-f38fe480-5c1e-11eb-895b-8d3a56a9d441.png)

**Comment by CityBelfast** [comment]
I can't see leaflet-interactive class in the canvas?   I have updated the leaflet-geoman.min.js version last week and pm.lock.js file yesterday. do you think I'm using old version of leaflet-geoman-min.js?

![image](https://user-images.githubusercontent.com/76213912/105418329-d9f99780-5c34-11eb-81b3-9d9a803ab7c7.png)
