### ISSUE TITLE
Polygon cannot be drawn on Safari

### ISSUE THREAD

**Issue by diadenchuk** [geoman-io/leaflet-geoman#768]
When 'allowSelfIntersection' parameter is set to false, the polygon cannot be drawn (on the screenshot). It's only reproducible on Safari. Also, we've found this only after we upgraded the react-leaflet to 3rd version.

https://codesandbox.io/s/elated-villani-q0gei?file=/src/map/MapWithGeoman.tsx

![image](https://user-images.githubusercontent.com/12237813/105333132-0afaad80-5bde-11eb-84d0-913d4c1fe446.png)

**Comment by Falke-Design** [comment]
I think this has something to do with leaflet core: https://github.com/Leaflet/Leaflet/issues/7255

I tried it, on every click two vertexes are created and then it has a self intersection. 

You can test this, when you click `Remove Last Vertex` then it is working until the next click.

Can you please try to use not the lastest Version of leaflet, try to use one of 1.6.x

**Comment by diadenchuk** [comment]
I tried 1.6.x and it worked as expected. I am gonna close this one and will track the leaflet core bug. Thanks 🤝
