### ISSUE TITLE
Question: how to close Custom button toggle automatically

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#769]
Hi,
I'm not sure how to close the toggle automatically after the custom action click. I tried with return 'finish' keyword  but it doesn't close automatically. see the attached screenshot and  the code below.

const actions = ['cancel', {
                text: 'Union', onClick: function () {
                    //---todo----
                    return 'finish';
                }
            }, {
                    text: 'Split', onClick: function () {
                    //---todo----
                    return 'finish';
                }
                }];
map.pm.Toolbar.createCustomControl({ name: "Union", tool: "custom", className: "fa fa-object-group", title: "Merge selected Polygons into single polygon.", afterClick: function () { }, actions: actions, toggle: true });            

![image](https://user-images.githubusercontent.com/76213912/105355567-3f746680-5bea-11eb-8fbf-740659d93bbb.png)

**Comment by Falke-Design** [comment]
Call `this.toggle(false)`

```
const actions = ['cancel', {
text: 'Union', onClick: function () {
    this.toggle(false)
}
}, {
text: 'Split', onClick: function () {
    this.toggle(false)
}
}];
map.pm.Toolbar.createCustomControl({ name: "Union", tool: "custom", className: "fa fa-object-group", title: "Merge selected Polygons into single polygon.", afterClick: function () { }, actions: actions, toggle: true });
```

**Comment by CityBelfast** [comment]
thanks you

**Comment by owolfy** [comment]
I receive "toggle is not a function" error. Can you tell what I am doing wrong?
`const drawMenu = {
name: 'test',
block: 'draw',
toggle: true,
actions: [
        {
text: 'click here',
onClick: () => {
drawMenu.toggle(false);
}`
`map.pm.Toolbar.createCustomControl(drawMenu);`

**Comment by owolfy** [comment]
@Falke-Design thanks!
