### ISSUE TITLE
Remove only custom button

### ISSUE THREAD

**Issue by arshdoda** [geoman-io/leaflet-geoman#771]
Hi,

I want to show the custom button if layer geometry is "polygon" and remove if layer geometry is "linestring"

Is there any function to remove the customButton.

I tried following:
```
const customButton = {
        name: 'custom',
        title: 'Custom',
        className: 'control-icon leaflet-pm-icon-edit',
        onClick: () => { 
        },
        afterClick: (e, obj) => {
        },
        doToggle: true,
        toggleStatus: false,
        disableOtherButtons: true,
        tool: 'custom',
        block: 'edit',
        actions: ['finishMode'],
    };

map.pm.Toolbar.createCustomControl(customButton) //Adding the button

map.pm.Toolbar.getButtons()['custom'].remove(); // It is not removing the button
```

**Comment by Falke-Design** [comment]
You can remove it like that:

```
map.pm.addControls({
  custom: false
})
```

And showing it again with:
```
map.pm.addControls({
  custom: true
})
```

**Comment by arshdoda** [comment]
> map.pm.addControls({
>   custom: false
> })

Not Working

**Comment by Falke-Design** [comment]
Look into this example: https://jsfiddle.net/falkedesign/pk2jyg71/

It should work.

Change between `custom: false` and `custom: true`

**Comment by arshdoda** [comment]
> Look into this example: https://jsfiddle.net/falkedesign/pk2jyg71/
> 
> It should work.
> 
> Change between `custom: false` and `custom: true`

Still not working. May be issue with npm package

**Comment by Falke-Design** [comment]
In the demo it is working how you expecting?

Do you use the latest version of Geoman 2.9.0 and Leaflet 1.7.1?

**Comment by arshdoda** [comment]
Yes, i am using the latest ones

**Comment by Falke-Design** [comment]
You also use the same name as in your shared code? `name: custom`

**Comment by arshdoda** [comment]
> You also use the same name as in your shared code? `name: custom`

Yes.

 I tried locally. Issue with npm package

**Comment by Falke-Design** [comment]
Hmmm Typescript, vanilla, or which framework you are using?

**Comment by arshdoda** [comment]
using reactjs

**Comment by Falke-Design** [comment]
Can you please create a demo like this: https://codesandbox.io/s/elated-villani-q0gei?file=/src/map/MapWithGeoman.tsx

**Comment by tobilg** [comment]
I have a similar issue with #796
