### ISSUE TITLE
Cursor doesn't turn into all-scroll point After clicking Move or Delete button.

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#772]
Hi - I'm facing an issue when I want to move or delete a geometry from map. 8 out of time times, cursor doesn't turn into all-scroll symbol.  As  a result, I'm unable to delete or move geometry from map 

I'm expecting the below cursor after clicking  move button
![image](https://user-images.githubusercontent.com/76213912/105383369-f54ead80-5c08-11eb-8846-03124fb3ed36.png)

But I'm getting grab Cursor pointing as below
![image](https://user-images.githubusercontent.com/76213912/105383553-229b5b80-5c09-11eb-9c93-73a000450b0f.png)

**Comment by Falke-Design** [comment]
I can't reproduce.

Errors in the console?

Maybe the invisible building layers are over the drawn one. Try to call `buildingGroup.bringToBack()`

**Comment by CityBelfast** [comment]
Ok ..I I will try it and let you know.
