### ISSUE TITLE
PMLock Doesn't work When drawing tool is in Edit mode.

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#780]
Hi,
 I've noticed PMLock doesn't work if drawing tool is in edit mode.  If user wants to load non-editable layer for snapping purpose while user is already in Edit mode then all the layers turn into edit mode. Please see the below steps.

1. Turn OFF the Underneath Snapping layer(i.e.  the layer for snapping and not editable), before click the Edit Layer button.
2. Now Press Edit Layer button
    **result**:  only one geometry in edit mode , which is right. see the below image
 ![image](https://user-images.githubusercontent.com/76213912/106183818-aa004600-6198-11eb-893c-e3f33b61e535.png)

3.  But now if user Turn ON the Snapping layer while he is in edit mode. The result is that then all the features turn into Edit Mode. (see the below picture)
![image](https://user-images.githubusercontent.com/76213912/106184229-27c45180-6199-11eb-8d47-3fab6d343ce2.png)

Here is my code

const pmLock = new L.PMLock(Map);      
     function layerGroupSnapoadAlltheFeatures (result) {
		L.Proj.geoJson(result, style: { pmLock: true }}).addTo(layerGroupSnap);
	}

Is there any way I could turn Off the edit mode of the drawing tool when I click on button to load underneath layer? 
I tried Map.pm.disableDraw(); but it doesn't disable the edit mode. 

this is related to #758 issue

**Comment by CityBelfast** [comment]
it would be greatly appreciated if I get any help to resole this issue.

**Comment by Falke-Design** [comment]
Please try to disable and enable the edit mode again.

When clicking on button to load layer below:
```
var editState = map.pm.globalEditModeEnabled();
map.pm.disableGlobalEditMode();

functionToLoadYouLayersBelow ...

if(editState){
   map.pm.enableGlobalEditMode();
}
```

**Comment by CityBelfast** [comment]
> var editState = map.pm.globalEditModeEnabled();
> map.pm.disableGlobalEditMode();

Thanks you.
