### ISSUE TITLE
[Q] - Catch map events with a pressed key

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#781]
I would need to able to catch map event `pm:create` when user draw a shape with `shift` key pressed.

Leaflet provides [originalEvent](https://leafletjs.com/reference-1.4.0.html#mouseevent-originalevent) object in `MouseEvent` object to be able to catch mouse events with a key pressed.

I think it would be possible to implement this by creating `click` event on map. There I can find out if `shift` was pressed on the first and the last click when a new shape was created by geoman. In `pm:create` event I can get the global variable and check if `shift` was pressed.

I am wondering if there is a better way to find out if `shift` was pressed directly in `pm:create` without implementing an additional click event on map.

**Comment by Falke-Design** [comment]
No I don't think that there is a better way

**Comment by AndrejGajdos** [comment]
Ok, thanks. Maybe you can consider this as a feature request.
