### ISSUE TITLE
PMLock issue

### ISSUE THREAD

**Issue by CityBelfast** [geoman-io/leaflet-geoman#794]
Hi - Due to ES6 syntax (i.e. default parameter in function  & lambda expression )  in PMLock coding, I'm facing some issue on IE11 browser as these syntax doesn't support IE11 browser. Whereas, I could replace those lambda expression into ES5. But for some reason the code doesn't work in both chrome and IE11. 

Here is the ES5 pmLock code.
[pmlock.txt](https://github.com/geoman-io/leaflet-geoman/files/5974703/pmlock.txt)

I'm getting this error while deleting geometry.
![image](https://user-images.githubusercontent.com/76213912/107833931-b2f23980-6d8c-11eb-9e5f-4448d4265bfd.png)

It would be really appreciated if I get some help to fix this pmLock issue to support IE11 browser?

**Comment by Falke-Design** [comment]
@CityBelfast please use the newest version `/dist/index.js`  [CDN](https://cdn.jsdelivr.net/gh/Falke-Design/PMLock@latest/dist/index.js)

**Comment by CityBelfast** [comment]
Please accept my deepest thanks @Falke-Design.
