### ISSUE TITLE
Remove complete line instead of a portion.

### ISSUE THREAD

**Issue by arshdoda** [geoman-io/leaflet-geoman#799]

**Comment by arshdoda** [comment]
Solved using vector grids

**Comment by Falke-Design** [comment]
You can also set `L.PM.setOptIn(true);` then is geoman for no layer enabled.
When you want to enable a layer for geoman, call:
```
layer.options.pmIgnore = false;
L.PM.reInitLayer(layer);  
```

https://github.com/geoman-io/leaflet-geoman#opt-in
