### ISSUE TITLE
The pm: snapdrag event does not fire after clicking at the moment of intersection

### ISSUE THREAD

**Issue by jCodeX1** [geoman-io/leaflet-geoman#800]
Good day, I ran into a problem, the solution to which I cannot find.
I have a tooltip that shows the area of ​​a plot, changing it is called on the pm: snapdrag event. But the problem is that if you make an intersection and click on the mouse button to save the area, then the pm: snapdrag event stops generating exactly until I let’s say I do not create a new point for the site. I am attaching a video with a demo. I would be grateful for your help!

https://user-images.githubusercontent.com/47521463/109490070-6434e700-7a90-11eb-9e23-d00f9cec2c8a.mp4

**Comment by Falke-Design** [comment]
@jCodeX1 I fixed this, it will be in the next Release. Thx for reporting.

But I think that for your use `pm:markerdrag` would be the correct event.

**Comment by jCodeX1** [comment]
@Falke-Design thx )

**Comment by jCodeX1** [comment]
@Falke-Design I'm sorry, but I tried pm: markerdrag, and unfortunately for me this event does not fire when the marker is dragged.
Here is my code:
`
this.editLayer
        .on('pm:enable', (e) => {
          this.onEditModeEnabledHook(e);
        })
        .on('pm:snapdrag', (e) => {
          console.log('snapdrag', e);
          this.onEditVertexMoved(e);
        })
        .on('pm:markerdrag', (e) => {
          console.log('markerdrag', e);
        })
        .on('pm:vertexremoved', (e) => {
          this.onEditVertexRemoved(e);
        })
        .pm
        .enable({ allowSelfIntersection: false });
`

**Comment by Falke-Design** [comment]
@jCodeX1 look into this example: https://jsfiddle.net/falkedesign/6z1f83L5/

Are you using the latest version of Geoman? 2.9.0 `console.log(L.PM.version)`

**Comment by jCodeX1** [comment]
@Falke-Design version 2.7.0 🤔

**Comment by Falke-Design** [comment]
I suggest you to update, we implemented this in the latest version

**Comment by jCodeX1** [comment]
@Falke-Design what should I update? if I don't have a geoman, I understand that it is included in the leaflet package

**Comment by Falke-Design** [comment]
You need to update Geoman. This has nothing to do with Leaflet core.

Update [npm](https://www.npmjs.com/package/@geoman-io/leaflet-geoman-free): `npm install @geoman-io/leaflet-geoman-free@2.9.0`
or 
Update Html Script: `<script src="https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.min.js"></script>`

**Comment by jCodeX1** [comment]
@Falke-Design yes i did it but the version (L.PM.version) hasn't changed

**Comment by Falke-Design** [comment]
Are you using NPM?

**Comment by jCodeX1** [comment]
@Falke-Design  

Yes, the addiction has appeared, but the version has not changed

<img width="489" alt="Снимок экрана 2021-03-02 в 10 26 17" src="https://user-images.githubusercontent.com/47521463/109619668-bb46c480-7b41-11eb-9f45-1d1a8052a70b.png">

My code: 
```js
console.log(L.PM.version);
      this.editLayer
        .on('pm:enable', (e) => {
          this.onEditModeEnabledHook(e);
        })
        .on('pm:snapdrag', (e) => {
          this.onEditVertexMoved(e);
        })
        .on('pm:markerdrag', (e) => {
          console.log('markerdrag', e);
        })
        .on('pm:vertexremoved', (e) => {
          this.onEditVertexRemoved(e);
        })
        .pm
        .enable({ allowSelfIntersection: false });
```

**Comment by Falke-Design** [comment]
This is weird ...

Maybe it is one of the following points:
- Call `npm install` to update the npm-packages local
- Have you regenerated / rebuild your code?
- Restart your server

**Comment by jCodeX1** [comment]
@Falke-Design Unfortunately, yes, I did all the options listed many times, but this did not solve my problem (

**Comment by jCodeX1** [comment]
@Falke-Design  

This is my L.PM object, maybe it can help somehow

<img width="798" alt="Снимок экрана 2021-03-02 в 10 39 12" src="https://user-images.githubusercontent.com/47521463/109621358-8a678f00-7b43-11eb-9466-60b4ac25c85d.png">

**Comment by Falke-Design** [comment]
Maybe you are using Geoman twice ... have you included in your html Geoman directly? Or have you downloaded it anywhere instead of using npm? Maybe you can search through your complete project, search for `geoman` or `pm`

**Comment by jCodeX1** [comment]
@Falke-Design  I performed the following operations, and then I wrote npm install, and that's it, I expected it to work

<img width="414" alt="Снимок экрана 2021-03-02 в 10 49 57" src="https://user-images.githubusercontent.com/47521463/109622666-0910fc00-7b45-11eb-9165-b470631d7a1f.png">

**Comment by Falke-Design** [comment]
So it is working now?

**Comment by jCodeX1** [comment]
@Falke-Design Yes, fine, I defeated the problem 😌 it was that the geoman was connected via html in my code, I removed that and imported a new plugin, now everything is fine!)
Thank you for your help!)

**Comment by Falke-Design** [comment]
Nice to hear!

I let this issue open until the fix for `pm:snapdrag` is fixed

**Comment by jCodeX1** [comment]
@Falke-Design one more question, after crossing my faces take their original form, but at the same time I do not know which hook to use to get the event after returning the figure to a valid view, is there any hook for changing the figure as a whole?

**Comment by Falke-Design** [comment]
You can listen on `pm:edit`, this event is fired, when the marker drag is finished.

**Comment by jCodeX1** [comment]
@Falke-Design a little wrong, when crossing, dragging ends, and I still have coordinates (for example, NN coordinates), but after dragging in the intersection, when I release the mouse button, the figure takes on a new view (with coordinates for example N1-N2), as a result, I save the coordinates NN , but about the new coordinates N1-N2, I don’t know, how can I handle this case?

**Comment by jCodeX1** [comment]
@Falke-Design `pm:edit` also does not fire after mouse release when crossing

**Comment by Falke-Design** [comment]
Yes you are right ...

This is the order of events, maybe this helps you:
1. `pm:markerdragstart`
2. `pm:markerdrag`
3. `pm:markerdragend`
3.1. With intersection `pm:intersect`
3.2. Without intersection `pm:edit`

**Comment by jCodeX1** [comment]
@Falke-Design The problem is that pm: intersect only fires when I made an intersection (after releasing the mouse button, it won't work), and `pm:markerdragend` just fires when the mouse is released, and I don't know the final state of the shape. So my guess is that this will no longer be a problem when the `snapdrag` hook works.
