### ISSUE TITLE
Strange dragging behaviour in dragging layergroup

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#807]
Hello again,

I have a map with a lot of geojson objects and by default, they are not editable. I render them with option `pmIgnore={true}`. I would like to enable edit and drag mode only on selected geojsons. User can drag selected geojsons all together.

There is a strange behavior when user starts dragging polygons, dragging freezes and it doesn't work. It works after second click.

Steps to reproduce:

1.) Click on geojson. _This action selects both geojsons_.
2.) Start dragging polygons. _Dragging freezes_.
3.) Click on geojson. _Dragging works_

![geoman_3](https://user-images.githubusercontent.com/1593758/110234904-59190580-7f2d-11eb-9bb1-b7e11da0fc05.gif)

Here is a [codesandox](https://codesandbox.io/s/quizzical-cray-jls47).

You already provided the [solution](https://github.com/geoman-io/leaflet-geoman/issues/778#issuecomment-767520895) in my previous question. Now I tried your updated version of PMDrag and I have no idea why it behaves like this in this case.

**Comment by Falke-Design** [comment]
A Quick fix is that you add this `layer.pm._safeToCacheDragState = true;` in following line:
https://github.com/Falke-Design/PMDrag/blob/339082d337c311f19a93cc394f11599068b2d762/src/DragMixin.js#L26

Or you wait until I fix this in pmDrag

**Comment by AndrejGajdos** [comment]
@Falke-Design thank you again.
