### ISSUE TITLE
Editing only one / two polygons

### ISSUE THREAD

**Issue by r4naf** [geoman-io/leaflet-geoman#808]
Hello! How to prevent editing of all polygons except some?
All polygons on one layer. There are a lot of polygons, I want to exclude some of the editing.
Maybe I didn't understand how to work with **pmIgnore: true**

**Comment by Falke-Design** [comment]
you can disable only editing for layers, you can only disable all Geoman functions when the layer has the option `pmIgnore: true`: `layer.setStyle({pmIgnore: true)}`

There is a open Feature Request for this, you can upvote it, so that it will be earlier implemented #583
