### ISSUE TITLE
collision pmDrag subplugin with MarkerCluster

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#809]
Hi again,

This is a follow-up issue on [this](https://github.com/geoman-io/leaflet-geoman/issues/807) previous one. In my project, I am using MarkerCluster and it seems like there is a collision between pmDrag and MarkerCluster.

[codesandbox](https://codesandbox.io/s/goofy-elbakyan-fbd18)

![geoman](https://user-images.githubusercontent.com/1593758/110292923-3864b480-7fee-11eb-992d-89d5f07516ce.gif)

**Comment by Falke-Design** [comment]
I looked into it but I didn't found the bug so you have to fix it by your self. I can't support all possible things and you are trying to combine a lot of not well supported features.

I suggest you to recalc the (center-)latlng of the marker while `pm:drag` is for the polygon called.

**Comment by Falke-Design** [comment]
You can always ask and I will help so good as I can.
