### ISSUE TITLE
[Q] How to change layers in FeatureGroup in PMDrag subplugin

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#814]
This is not an issue, but I came across a use-case which I am not able to fix. Multiple polygons are draggable by using FeatureGroup in PMDrag. User can select polygons to drag and edit. If user changes selected polygons, FeatureGroup needs to be updated, but I have no idea how to do that. I tried to implement it like this, but it doesn't work. I would be thankful for any advice.

```
if (!dragFeatureGroup.current) {
        dragFeatureGroup.current = L.featureGroup(layersToDrag).addTo(map);
      } else {
        const featureLayersIds = Object.keys(
          dragFeatureGroup.current._layers
        ).map((keyId) => parseInt(keyId, 10));
        layersToDrag.forEach((layerToDrag) => {
          const layerAdded = featureLayersIds.some(
            (featuredLayerId) => featuredLayerId === layerToDrag._leaflet_id
          );
          if (!layerAdded) {
            console.log("add layer", layerToDrag);
            dragFeatureGroup.current.addLayer(layerToDrag);
          }
        });

        const layersToDragIds = layersToDrag.map(
          (layerToDrag) => layerToDrag._leaflet_id
        );
        const layerIdsToRemoveFromFeatureGroup = difference(
          featureLayersIds,
          layersToDragIds
        );
        Object.keys(dragFeatureGroup.current._layers).forEach(
          (featureLayerId) => {
            const removeLayer = layerIdsToRemoveFromFeatureGroup.some(
              (layerId) => layerId === parseInt(featureLayerId, 10)
            );
            const layerToRemove =
              dragFeatureGroup.current._layers[featureLayerId];
            if (removeLayer) {
              console.log("remove layer", layerToRemove);
              dragFeatureGroup.current.removeLayer(layerToRemove);
              map.addLayer(layerToRemove, { pmIgnore: true });
              if (layerToRemove?.pm) {
                layerToRemove.pm.disableLayerDrag();
                layerToRemove.pm.disable();
              }
            }
          }
        );
        console.log("mutated featureGroup", dragFeatureGroup.current);
      }
```

[codesandbox.io](https://codesandbox.io/s/proud-sunset-fslvt?file=/src/useDraw.js)

![geoman](https://user-images.githubusercontent.com/1593758/111195229-54eb8880-85bc-11eb-9709-0c9e65e457d8.gif)

**Comment by Falke-Design** [comment]
![issue_pmdrag](https://user-images.githubusercontent.com/19800037/111221038-47dd9200-85da-11eb-9ca9-737bead3612c.gif)

Is working for me (Firefox / Windows). 

But a problem is, that it is loading very long until the drag cursor is visible and if I click again "select first" and then "select second" I can't drag.
![issue_pmdrag2](https://user-images.githubusercontent.com/19800037/111221425-c33f4380-85da-11eb-9a89-86725be78cbb.gif)

**Comment by AndrejGajdos** [comment]
@Falke-Design I am going to open new issue, because this sample project actually works without any issues
