### ISSUE TITLE
Layers are still enabled after disabling

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#815]
I came across an issue, which I am not able to fix. I don't know if something is wrong in my implementation or in geoman. I would be thankful for any advice.

User can select polygons to enable drag and edit mode on them. When selected polygons are changed, drag and edit mode is disabled on previous polygons and enabled on newly selected polygons. The issue is that edit mode is still enabled on some polygons from the previous selection.

I created [a recording](https://drive.google.com/file/d/1790X09fOBTi_XN_VWQ7X-ypitmDJ53m2/view) to replicate this issue:

1.) User draws a rectangle, which creates a selection. Two polygons are selected.
2.) User hits edit button on toolbar. It enables edit and drag mode for selected polygons.
3.) User hits draw rectangle button on toolbar. It disables edit and drag mode for selected polygons.
4.) User draws a rectangle and selects only one polygon.
5.) User hits edit button to enable edit and drag mode on selected polygon. --> edit mode is enabled on the previous selected polygon which was disabled.

[codesandbox.io](https://codesandbox.io/s/dazzling-banzai-9kr0c?file=/src/useDraw.js)

**Comment by Falke-Design** [comment]
It is working for me :/

**Comment by AndrejGajdos** [comment]
@Falke-Design would you mind creating a recording? I tried Chrome and Firefox and I have the same issue in both browsers.

**Comment by Falke-Design** [comment]
https://user-images.githubusercontent.com/19800037/111300979-f670e980-8651-11eb-8478-2df84395f278.mp4

**Comment by AndrejGajdos** [comment]
@Falke-Design what browser are you using? I tried Firefox and there it takes several seconds when disabled layer is re-enabled. I created a new [recording](https://drive.google.com/file/d/1D-HPFVkwt0laY9eQvvOt4V1BZ6NiAUR-/view?usp=sharing). Also, codesandbox can be much slower than a local dev machine.

**Comment by Falke-Design** [comment]
Ok yes it is is also re-enable the polygons after a while ... I have no idea how to solve this and what can be the issue. I think when you find out, why / where the long loading is comeing from, we can solve this.

A way would be to add a log where you enable the layers and look from where the function is callled `console.error('test')`

**Comment by AndrejGajdos** [comment]
@Falke-Design that's the thing, I am trying to figure out last 2 days where is the long loading coming from. I edited [codesandbox](https://codesandbox.io/s/cranky-heyrovsky-rxjb3?file=/src/useDraw.js) and added `console.log` for render and effect in each component, everywhere where I enable/disable layers, every event listener. Nothing is triggered when disabled layer is re-enabled. Do you have any other ideas how to figure it out?

**Comment by AndrejGajdos** [comment]
I fixed that by removing disabled layers and adding them to the map again which makes whole code base more complicated. I know that I combine not well supported features, so it's up to you if you want to close this or take a look at it later at some point.

**Comment by Falke-Design** [comment]
I will close this and hopefully we can implement this things some day and make it better working together

**Comment by Falke-Design** [comment]
Feature Requests: #818, #819
