### ISSUE TITLE
Imcomplete type definition

### ISSUE THREAD

**Issue by soletan** [geoman-io/leaflet-geoman#821]
The current state of [leaflet-geoman.d.ts](https://github.com/geoman-io/leaflet-geoman/blob/master/leaflet-geoman.d.ts#L127) is causing issues with code complying with your documentation, mainly with regard to PM.Map. These methods are missing there at least:

* [controlsVisible()](https://github.com/geoman-io/leaflet-geoman#leaflet-geoman-toolbar)
* [removeControls()](https://github.com/geoman-io/leaflet-geoman#leaflet-geoman-toolbar)
* [reInitLayer()](https://github.com/geoman-io/leaflet-geoman#init-leaflet-geoman)
* [setGlobalOptions()](https://github.com/geoman-io/leaflet-geoman#draw-mode)

**Comment by tirli** [comment]
@Falke-Design [reInitLayer()](https://github.com/geoman-io/leaflet-geoman/blob/master/leaflet-geoman.d.ts#L195) is still incomplete. It should accept layer as an argument.

**Comment by Falke-Design** [comment]
@tirli  yes you are right ... will be fixed
