### ISSUE TITLE
Make ability to install PM after map is initialized

### ISSUE THREAD

**Issue by rendrom** [geoman-io/leaflet-geoman#823]
Hello!

I use asynchronous component loading to avoid load extra code if editing is not require. In current version of PM, if the leaflet map has already been initialized, the editor will not work in the usual way of initializing.
For myself, I decided in this way:
```typescript
const pm = new (L.PM as any).Map(map);
map.pm = pm;
```
it would be great to have PM method to properly set the editor to an already initialized map.
For example:
```typescript
L.PM.addTo(map)
```

and also be great to import such a method directly from the library

```typescript
import setup from '@geoman-io/leaflet-geoman-free';

setup(leafltMap);
```

if such library development is acceptable, I am ready to prepare the PR after discussing

**Comment by Falke-Design** [comment]
Let us discuss here: #705
