### ISSUE TITLE
pmDrag's addLayer method leaking

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#824]
Hi there,

I think pmDrag subplugin should have a method for resetting mutated leaflet's events. If you change routes in a React project and `import "./pmDrag";` is run again, project throws an error: `Maximum call stack size exceeded`, because [addLayer](https://github.com/Falke-Design/PMDrag/blob/master/src/index.js#L123) method will run in a loop.

[codesandbox.io](https://codesandbox.io/s/serverless-waterfall-0or1h?file=/src/App.js)

![geoman](https://user-images.githubusercontent.com/1593758/112303647-d322eb80-8c9c-11eb-9c60-dedec2ac5493.gif)

**Comment by AndrejGajdos** [comment]
I was able to fix that like this:

```javascript
const defaultLeafletAddLayerEvent = React.useRef(null);

React.useEffect(() => {
		return () => {
			L.LayerGroup.prototype.addLayer = defaultLeafletAddLayerEvent.current;
		};
}, []);

React.useEffect(() => {
		defaultLeafletAddLayerEvent.current = L.LayerGroup.prototype.addLayer;
		const pmDrag = new L.PMDrag(mapRef, { overwriteLayerGroup: true });
		pmDrag.setMode(1);
}, [mapRef]);

```

I am not sure if this is the best way to fix this. I will this issue opened.

**Comment by Falke-Design** [comment]
I think / hope that pmDrag is not longer needed after the next release.

**Comment by AndrejGajdos** [comment]
@Falke-Design great news, thank you.
