### ISSUE TITLE
Dragging doesn't work with layerPane option in canvas mode

### ISSUE THREAD

**Issue by AndrejGajdos** [geoman-io/leaflet-geoman#837]
Hello again,

I came across a use case where dragging doesn't work. If I want to render map in [canvas](https://leafletjs.com/reference-1.7.1.html#map-prefercanvas) mode and use my own panes, dragging doesn't work.

I set panes like this:

```
map.pm.setGlobalOptions({
      panes: {
        vertexPane: "drawing",
        layerPane: "drawing",
        markerPane: "drawing",
      },
```

You can check [recording](https://drive.google.com/file/d/1dPNQZHqO_gkg1dHy07Kgo6CEhQWND-17/view?usp=sharing) and [codesandbox](https://codesandbox.io/s/amazing-mendel-weoi3?file=/src/useDraw.js:5399-5401) to reproduce the issue.

edit: I played with this and figured out that dragging in canvas mode doesn't work if `layerPane` option is used.

**Comment by AndrejGajdos** [comment]
I did a workaround in my code and don't use `layerPane` option. I think dragging single polygon works, only dragging whole layer group doesn't work. Feel free to close this because this issue is perhaps related to pmDrag subplugin.

**Comment by Falke-Design** [comment]
I think that we have implemented in the next release your needs. Editing + Drag and LayerGroup dragging. 
I tested it with the PR for LayerGroup dragging and I didn't have the same problem, so maybe it will not exists with the new (and better supported) code.

**Comment by AndrejGajdos** [comment]
@Falke-Design awesome, I will test it out and let you know if I find any issues.
