### ISSUE TITLE
TypeScript getGeomanDrawLayers improvement

### ISSUE THREAD

**Issue by hstevanoski** [geoman-io/leaflet-geoman#865]
I think the return type of the `getGeomanDrawLayers` method should be improved.  
Currently, in `leaflet-geoman.d.ts`, we have the following:

```ts
/** Returns all Geoman layers on the map as array. Pass true to get a L.FeatureGroup. */
getGeomanLayers(featureGroup?: boolean): L.FeatureGroup | L.Layer[];
/** Returns all drawn Geoman layers on the map as array. Pass true to get a L.FeatureGroup. */
getGeomanDrawLayers(featureGroup?: boolean): L.FeatureGroup | L.Layer
```

The issue is that `getGeomanDrawLayers` doesn't return an array (missing `[]` after `L.Layer`), so you have to rely on the `getGeomanLayers` method to perform array-specific operations (not ideal in more complex scenarios).

**Comment by Falke-Design** [comment]
Thank you for reporting, this is not the wanted behaviour, we will change it to `L.Layer[]`.

@ryan-morris can you add this please in the next TypeScript PR?

**Comment by ryan-morris** [comment]
Will do
