### ISSUE TITLE
start drawing with out placing a vertex first for selection purposes

### ISSUE THREAD

**Issue by t1a2l** [geoman-io/leaflet-geoman#874]
In leaflet draw i can draw a rectangle without placing a first vertex, i just click on an empty spot and start creating a shape. i am looking for a solution of selecting a bunch of marker using the rectangle tool.

**Comment by Falke-Design** [comment]
In Leaflet-Draw you also creating the first vertex and then the second one ... there is no need for holding the mouse down (if this is what you mean).

Why is the current method not good / working for you? You can select the markers same as in leaflet-draw (with the rectangle) or do I missunderstand something?

**Comment by t1a2l** [comment]
@Falke-Design - leaflet draw editing did not work for me because of a handler bug on RTL maps. I solved the bug a few minutes ago accedently and leaflet draw no working ok. So no need for this library currently. 
In general I was looking for a way like leaflet draw where you can click in empty place and start creating a rectangle and unless you add a "created" event it will be a simple selection that select markers on the map.

**Comment by Falke-Design** [comment]
You can use the Rectangle as selection tool with this code:

```
// click on Toolbar "Rectangle" or start it manually with map.enableDraw('Rectangle');

// create event
map.on('pm:create',(e)=>{
    if(e.shape === "Rectangle"){    
        var layer = e.layer;
        var selection = layer.getBounds();
        // delete layer
       layer.removeFrom(map);
    }
});

```

**Comment by knorke132** [comment]
Drawing without needing to do the first click would still be a desirable option for many people.
All Common applications let the user draw with just holding down the mouse button, this is way more intuitive

**Comment by Falke-Design** [comment]
Link #1106
