### ISSUE TITLE
prevent firing click event on remove layer 

### ISSUE THREAD

**Issue by nikopeikrishvili** [geoman-io/leaflet-geoman#877]
Hi all,
I have a polygon, I have "click" the event on this polygon that opens a popup with some information.
when I need to remove this polygon "click" events also fired and  the layer popup opens at the same time,
param that comes with pm:remove event is not an event object to stopPropagation

is there any workaround to fix this issue?

thanks

**Comment by Falke-Design** [comment]
Can you please share your code, it's working for me, that no popup is opened: https://jsfiddle.net/falkedesign/qfm9s7c2/

Else you can add a check in the click event if the map has the layer.

**Comment by nikopeikrishvili** [comment]
The problem is not that the popup is not opening, problem is that if I have click event on the layer, (on click popup appears) if I try to remove this layer, the click event is also firing and a popup opens.
https://jsfiddle.net/gfj8qLb2/7/

if you try to remove the layer, in the console you will see, "remove", and after a "click"

so the question is how to prevent click firing when pm:remove event happen

**Comment by Falke-Design** [comment]
I tried a little bit around and found following solution:
```
layer.on('click',function(e){
  if(!map.pm.globalRemovalEnabled()){
       console.log('click')
  }
})
```
Now it detects if the removal mode is activ -> means on `click` the layer is removed
