### ISSUE TITLE
I want the mark to show the latlng

### ISSUE THREAD

**Issue by 2qq2qq** [geoman-io/leaflet-geoman#882]
I want the mark to show the latlng. What can I do？thanks

**Comment by Falke-Design** [comment]
Please look into the Leaflet docu: https://leafletjs.com/examples/quick-start/
You can add a popup to the marker with `marker.bindPopup("Marker Latlng: "+marker.getLatLng());`

Anyway this no issue / question of this library. Look into the Leaflet core project.
