### ISSUE TITLE
duplicate canvas element with preferCanvas: true

### ISSUE THREAD

**Issue by plarner30** [geoman-io/leaflet-geoman#889]
Is it possible to use Geoman with a specific instance of Leaflet's Render class? 

With Map setting, preferCanvas: true i'm getting a secondary <canvas element added to the DOM when enabling drawing. This gets left behind when drawing is disabled and blocks click events to the applications primary canvas.

**Comment by Falke-Design** [comment]
Can you please create a demo? https://jsfiddle.net/o1dwu2vg/
