### ISSUE TITLE
Why does the _mRadius value increase when dragging the circle?

### ISSUE THREAD

**Issue by ykparkwixon** [geoman-io/leaflet-geoman#892]
Hello, 

When I get the _mRadius value from a circle layer on pm:centerplaced event, It is increasing.

here is my step:
- draw a circle and set the code for getting _mRadius value on pm:centerplaced event
- click 'Edit Layer' button on tool bar
- grap the center marker and drag here and there
- read the _mRadius value

I know that my question is similar to closed issue #357.  
However, It still increasing. even if not dragging from pole to pole. no matter how big or small moving area.

How can I solve this problem?

I have test with leaflet1.4, leaflet1.7 and geoman.io from CDN.

Now behaves as expected.

![circle](https://user-images.githubusercontent.com/2399810/52883953-e7669700-316c-11e9-94a5-9f2b33c6c169.gif)

_Originally posted by @codeofsumit in https://github.com/geoman-io/leaflet-geoman/issues/357#issuecomment-464197111_

**Comment by Falke-Design** [comment]
I understand! Fixed this in #894 and will be in the next release. 
Thx for reporting this issue

**Comment by ykparkwixon** [comment]
> I understand! Fixed this in #894 and will be in the next release.
> Thx for reporting this issue

Oh, Thanks for your work!
