### ISSUE TITLE
Rotate rect

### ISSUE THREAD

**Issue by Mackiavelly** [geoman-io/leaflet-geoman#910]
![rect-bug](https://user-images.githubusercontent.com/11190487/118615373-578b7980-b7c9-11eb-9e6a-ae5769db6791.gif)

**Comment by Falke-Design** [comment]
Thanks for reporting that bug. I can only reproduce this on geoman.io, does this also happens localy?

**Comment by Falke-Design** [comment]
Fixed with Release 2.11.3
