### ISSUE TITLE
can't click to vertex in drawing (50/50)

### ISSUE THREAD

**Issue by Mackiavelly** [geoman-io/leaflet-geoman#911]
[demo](https://jsfiddle.net/mackiavelly/yudn3aoq/1/)
Then drawing new polyline sometimes can't click to vertex because draw marker has more z-index
![polyline-vertex](https://user-images.githubusercontent.com/11190487/118657863-866b1500-b7f4-11eb-9702-c4fd982a7509.gif)
If the cursor is below the center of the vertex, then a click sets a new point, if the cursor is above the center completes the line.

**Comment by Falke-Design** [comment]
Thank you for reporting. 
I don't know if we can fix this, because this is a leaflet internal issue. It is not possible to set the Z-Index for Markers (vertex).
