### ISSUE TITLE
Issue on edit LatLongs programmatically

### ISSUE THREAD

**Issue by contibru** [geoman-io/leaflet-geoman#914]
Hey everyone,
I notice a problem when I change de coordinates of a polygon programmatically.
The vertices remain in map.
This code bellow doesn`t allow the user overllaping a polygon into another.

This is the code:
```
let intersection = turf.intersect(overlay.toGeoJSON(), this.polygon.toGeoJSON());
if (intersection) {
        const diff = turf.difference(this.polygon.toGeoJSON(), intersection);
        const path = L.GeoJSON.coordsToLatLngs(diff.geometry.coordinates, 1);
        this.polygon.setLatLngs(path);
}
```
A gif showing the problem:

![polygon](https://user-images.githubusercontent.com/30509284/118814471-92071c00-b886-11eb-8a60-354f9934246c.gif)

**Comment by Falke-Design** [comment]
You can use the interal functions of Geoman to re-render the vertex markers:

```
      layer.setLatLngs(coords);
      // re-enable markers for the new coords
      layer.pm._initMarkers();
```

With `layer.pm._handleLayerStyle(true);` you can flash the layer red, if you want this.

**Comment by contibru** [comment]
So, I used this to avoid the error for now.

```
// @ts-ignore
this.polygon.pm._initMarkers();
```

**Comment by SellingSystems** [comment]
How would this work with a marker? I am allowing the user to either drag the marker or enter new coords which are used in a setLatLng command. When I try to drag the marker after updating the position with a setLatLng it snaps back to the position it was at before the setLatLng. I have tried using toggleEdit and disabling and enabling PM but it doesn't seem to help.
