### ISSUE TITLE
How can I hide the 'Rotate Layers' button from the tool bar?

### ISSUE THREAD

**Issue by ykparkwixon** [geoman-io/leaflet-geoman#919]
How can I hide the 'Rotate Layers' button from the tool bar?

Isn't there any option for that such as 'cutPolygon:false' for map.pm.addControls?

**Comment by Falke-Design** [comment]
There is a option: `rotateMode`:

```
map.pm.addControls({
    rotateMode: false
});
```

It's missing in the Readme, we will add it

**Comment by ykparkwixon** [comment]
> There is a option: `rotateMode`:
> 
> ```
> map.pm.addControls({
>     rotateMode: false
> });
> ```
> 
> It's missing in the Readme, we will add it

Thanks for your reply!~
