### ISSUE TITLE
Leaflet-geoman editor demo: invalid key

### ISSUE THREAD

**Issue by arjanvlek** [geoman-io/leaflet-geoman#924]
The demo page of the editor on https://geoman.io/leaflet-geoman  shows 'Invalid key' across the entire map.

![Schermafbeelding 2021-05-27 om 10 14 45](https://user-images.githubusercontent.com/10106652/119791098-cb6a0800-bed4-11eb-9859-266f4bb5aa00.png)

**Comment by codeofsumit** [comment]
Yes, unfortunately, our Editor and Demo receive a LOT of traffic and map tiles are really expensive. We are out of requests for the month. We have to find a way to monetize & pay for that through donations or Github Sponsors.

**Comment by matkoniecz** [comment]
Not sure is it worth doing, but have you considered self-hosting tiles?

**Comment by matkoniecz** [comment]
Tiles are now loaded from OpenStreetMap servers. Are you aware of https://operations.osmfoundation.org/policies/tiles/  ?

Especially

> Heavy use (e.g. distributing an app that uses tiles from openstreetmap.org) is forbidden without prior permission from the Operations Working Group. See below for alternatives.

given

> Yes, unfortunately, our Editor and Demo receive a LOT of traffic and map tiles are really expensive.

**Comment by Falke-Design** [comment]
We increased the possible tiles requests on MapTiler and added OSM as Fallback. So yes we know about that and we think that we reduced the tiles request to a number which falls not under "heavy use". We'll keep an eye on that and see how it works.

**Comment by codeofsumit** [comment]
> Not sure is it worth doing, but have you considered self-hosting tiles?

No - Geoman.io is a free editor and the demo map is for a free open source plugin. We don't have the resources to build our own tile distribution for this purpose.
