### ISSUE TITLE
Draw Rectangle when load Shapes from GeoJson

### ISSUE THREAD

**Issue by maxicastle** [geoman-io/leaflet-geoman#937]
Hello,

I need to draw a set of shapes as Rectangles for easy width/height edition, but i can't find a way to do it,
it doesn't even matter if some shape is a rectangle (5 Points) or polygon(3 points or more), the library always draw the shape as a polygon.

any idea to solve this?

**Comment by Falke-Design** [comment]
I think you importing the layers over `L.geoJSON()`. Then this is not a problem of Geoman, this is a Leaflet core issue. The problem is that geojson don't know the type `Rectangle` so Leaflet creates always `L.Polygon`.

Please look into this question and tell us if it helped: https://github.com/geoman-io/leaflet-geoman/discussions/899#discussioncomment-735248

**Comment by maxicastle** [comment]
Thank you so much, you have save me my friend

that code already works 
[https://github.com/geoman-io/leaflet-geoman/discussions/899#discussioncomment-735248](url)

Option 1 properties: {shape: "Rectangle"}
`var removeList = [];
  var addList = [];
  // function to check if it is a Rectangle
  var onEachFeature = (feature, layer) => {
      if (feature.properties.shape === 'Rectangle') {
        console.log("Rectanlge");
        // we need to create a new Rectangle Layer and add it to an array
        addList.push(L.rectangle(layer.getBounds()));
        // we add the current layer to the remove list
        removeList.push(layer)
      }
  };
  var geo = L.geoJSON(json, {
    onEachFeature
  }).addTo(map);

  // we remove and add the rectangle layers here, because it throws an error if this happens in the onEachFeature function
  removeList.forEach((layer) => {
    layer.removeFrom(geo);
  });
  addList.forEach((layer) => {
    layer.addTo(geo);
  });`

Option 2 No Properties
`  var removeList = [];
  var addList = [];
  // function to check if it is a Rectangle
  var onEachFeature2 = (feature, layer) => {

    // we get all latlngs and flatten it to a single level array
    var latlngs = layer.getLatLngs().flat(999);
    // Rectangle has exact 4 latlngs
    if(latlngs.length === 4) {
      var first = latlngs[0];
      // check if similar lat / lng coords existing
      var lats = latlngs.filter((_latlng) => _latlng.lat === first.lat);
      var lngs = latlngs.filter((_latlng) => _latlng.lng === first.lng);

      // check if different lat / lng coords existing
      var secondLats = latlngs.filter((_latlng) => _latlng.lat !== first.lat);
      var secondLngs = latlngs.filter((_latlng) => _latlng.lng !== first.lng);

      // lats, lngs, secondLats, secondLngs needs to be length 2, and secondLats, secondLngs needs to have the same coords
      if (lats.length === 2 && lngs.length === 2 && secondLats.length === 2 && secondLats[0].lat === secondLats[1].lat && secondLngs.length === 2 && secondLngs[0].lng === secondLngs[1].lng) {
        console.log("Rectanlge");
        // we need to create a new Rectangle Layer and add it to an array
        addList.push(L.rectangle(layer.getBounds()));
        // we add the current layer to the remove list
        removeList.push(layer)
      }
    }
  };

  var geo = L.geoJSON(json, {
    onEachFeature
  }).addTo(map);

  // we remove and add the rectangle layers here, because it throws an error if this happens in the onEachFeature function
  removeList.forEach((layer) => {
    layer.removeFrom(geo);
  });
  addList.forEach((layer) => {
    layer.addTo(geo);
  });`


Test
![Picture1](https://user-images.githubusercontent.com/6173674/122664330-5ea9fc80-d166-11eb-8b5a-a426442d4304.png)

**Comment by aliyilmaz** [comment]
Specify the type of shapes in geojson (assign Rectangle, Polygon, Circle, CircleMarker, Marker, Polyline to layer.feature.properties.type).

Do not read the json file using L.geojson.
