### ISSUE TITLE
Events not firing when data loaded from json

### ISSUE THREAD

**Issue by cksadra** [geoman-io/leaflet-geoman#938]
can you help me? @codeofsumit
All events work properly when drawing a layer or marker and can get coordinatesand more
But when loading coordinates from json or any ... No event fired. and can't get data.
What is the problem?

**Comment by Falke-Design** [comment]
Can you please share your code?

Are you adding the events to the layers of the `L.geoJSON` import?

Like:
```
      var json =     {
        type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [
            [
              [-81.909315, 30.333176],
              [-81.909315, 30.37643],
              [-81.84133, 30.37643],
              [-81.84133, 30.333176],
              [-81.909315, 30.333176],
            ],
          ],
        },
      };

      L.geoJSON(json, {
        onEachFeature(feature, layer) {
          layer.on('pm:edit', (e) => console.log(e));
        }
      }).addTo(map);
```

**Comment by cksadra** [comment]
My data loaded by Ajax:
var geoJason = {
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {
            "shape": "Marker",
            "name": "Point 1",
            "category": "default"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [50.403643, 31.521154]
        },
        "id": "19606eb2-5649-4389-a8ca-4c0395e8e92b"
    }, {
        "type": "Feature",
        "properties": {
            "shape": "Marker",
            "name": "Point 2",
            "category": "default"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [50.410123, 31.519654]
        },
        "id": "4e69f8b9-b83a-4afd-a5de-b4dc30d5afa6"
    }, {
        "type": "Feature",
        "properties": {
            "shape": "Circle",
			"radius": 385.5669735362315,
            "name": "Circle 1",
            "category": "default"
        },
        "geometry": {
            "type": "Point",
            "coordinates": [50.395467281, 31.51709342]
        },
        "id": "4e69f8b9-b83a-4afd-a5de-b4dc30d5afa9"
    }, {
        "type": "Feature",
        "properties": {
            "shape": "Line",
            "name": "Line 1",
            "category": "default"
        },
        "geometry": {
            "type": "LineString",
            "coordinates": [
                [50.401196, 31.51874],
                [50.412054, 31.523386]
            ]
        },
        "id": "a4ecb399-ff45-4531-8857-f680a89e59ee"
    }, {
        "type": "Feature",
        "properties": {
            "shape": "Polygon",
            "name": "Polygon 1",
            "category": "default"
        },
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [50.401111, 31.513618],
                    [50.411453, 31.517093],
                    [50.409436, 31.511349],
                    [50.401111, 31.513618]
                ]
            ]
        },
        "id": "5719bb3c-30da-4e72-bcb7-c9d91d7d1e60"
    }]
}
			datalayer = L.geoJSON(geoJason, {
				onEachFeature:onEachloadDataMap,
				pointToLayer: function (feature, latlng) {
					var objPrpts = feature.properties;
					var objGmtr = feature.geometry;
					if (objPrpts.shape == 'Circle') {
						return L.circle(latlng, objPrpts.radius).bindTooltip(objPrpts.objName, {permanent: true, direction:"center"});
					} else if (objPrpts.shape == 'CircleMarker') {
						return L.circleMarker(latlng, objPrpts.objStyle).bindTooltip(objPrpts.objName);
					} else if (objPrpts.shape == 'Marker') {
						var thisIcon = L.icon({iconUrl:objPrpts.objGrpIcon,
							iconSize:[objPrpts.objWidth, objPrpts.objHeight],
							iconAnchor:[(objPrpts.objWidth/2), (objPrpts.objHeight-4)],
							popupAnchor:[0, -(objPrpts.objHeight-4)]});
						return L.marker(latlng, {
							icon: thisIcon,id:objPrpts.objId,group:objPrpts.objGrpId,region:objPrpts.objRegion}).bindTooltip(objPrpts.objName);
						if (_mode == 'single'){setTimeout(function() {dnMap.flyTo(latlng, objPrpts.objZoom, {animate: true,duration: 0.75});}, 150);}
					}
				}
			}).addTo(dnMap);

'###
And then .....
			
			var _latLngs = '', lyrType = '', drawType = '', strLatLngs = '', arrLatLngs = '', LatlngCentroid = '', intCircleRadius = '';	
			dnMap.on('pm:create', function (e) {
				lyrType = getLayerType(e.layer);
				strLatLngs = e.layer.toGeoJSON().geometry.coordinates;
				if (lyrType == 'polygon' || lyrType == 'rectangle') {
					arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1).slice(1,-1)+']');
				} else if (lyrType == 'polyline') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');
				} else if (lyrType == 'circle') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');intCircleRadius = e.layer.getRadius();
				} else if (lyrType == 'point') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs)+']');}
				if (lyrType == 'polyline') {drawType = 'linestring';} else {drawType = lyrType;}
				$(".draw-icon").css("background-image", "url(./images/maps/icon_maps_"+drawType+"_20.png)");
				$("input[name='idxRadius']").val(intCircleRadius);
				$("#idxDrawType").val(drawType);
				$("#idxCoords").val(strLatLngs);
				$("div.located").show().effect("shake");
				LatlngCentroid = getCentroid(arrLatLngs);
				if (LatlngCentroid != false) {
					var lonCentroid = LatlngCentroid[0];
					$("input#idxMidLon").val(lonCentroid);
					var latCentroid = LatlngCentroid[1];
					$("input#idxMidLat").val(latCentroid);
				}
				//return lyrType+'|'+LatlngCentroid+'|'+exportPoint;
				/*******Edit layer*******/
				e.layer.on('pm:edit', function (ev) {
					lyrType = getLayerType(ev.layer);
					if (lyrType == 'polygon' || lyrType == 'rectangle') {
						_latLngs = ev.layer.getLatLngs();
						_latLngs = L.polygon(_latLngs);
					} else if (lyrType == 'polyline') {
						_latLngs = ev.layer.getLatLngs();
						_latLngs = L.polyline(_latLngs);
					} else if (lyrType == 'point') {
						_latLngs = ev.layer.getLatLng();
					}
					if (_latLngs != '') {
						//strLatLngs = stringifyLatLngs.match(/([\d\.]+)/g).join(',');
						if (lyrType == 'point') {strLatLngs = (_latLngs.lng+','+_latLngs.lat);
						} else {strLatLngs = _latLngs.toGeoJSON().geometry.coordinates;}
						if (lyrType == 'polygon' || lyrType == 'rectangle') {
							arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1).slice(1,-1)+']');
						} else if (lyrType == 'polyline') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');
						} else if (lyrType == 'circle') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');intCircleRadius = e.layer.getRadius();
						} else if (lyrType == 'point') {arrLatLngs = $.parseJSON('['+strLatLngs+']');}
					} else if (_latLngs == '') {strLatLngs = '';}
					if (lyrType == 'polyline') {drawType = 'linestring';} else {drawType = lyrType;}
					$(".draw-icon").css("background-image", "url(./images/maps/icon_maps_"+drawType+"_20.png)");
					$("input[name='idxRadius']").val(intCircleRadius);
					$("#idxDrawType").val(drawType);
					$("#idxCoords").val(strLatLngs);
					if (lyrType != 'point') {
						LatlngCentroid = getCentroid(arrLatLngs);
					} else {LatlngCentroid = arrLatLngs;}
					if (LatlngCentroid != false) {
						$("input#idxMidLon").val(LatlngCentroid[0]);
						$("input#idxMidLat").val(LatlngCentroid[1]);
					}
					//return lyrType+'|'+LatlngCentroid+'|'+exportPoint;
				});
				/*******Edit layer*******/
			});
			dnMap.on('pm:remove', function (y) {
				$("#idxDrawType, #idxCoords, #idxMidLat, #idxMidLon").val('');
			});

**Comment by Falke-Design** [comment]
Yes like I said, you need to add the events in the `onEachFeature` too:

```
function onEachloadDataMap(feature, layer){
... other code ...

layer.on('pm:edit', function (ev) {
				lyrType = getLayerType(ev.layer);
				if (lyrType == 'polygon' || lyrType == 'rectangle') {
					_latLngs = ev.layer.getLatLngs();
					_latLngs = L.polygon(_latLngs);
				} else if (lyrType == 'polyline') {
					_latLngs = ev.layer.getLatLngs();
					_latLngs = L.polyline(_latLngs);
				} else if (lyrType == 'point') {
					_latLngs = ev.layer.getLatLng();
				}
				if (_latLngs != '') {
					//strLatLngs = stringifyLatLngs.match(/([\d\.]+)/g).join(',');
					if (lyrType == 'point') {strLatLngs = (_latLngs.lng+','+_latLngs.lat);
					} else {strLatLngs = _latLngs.toGeoJSON().geometry.coordinates;}
					if (lyrType == 'polygon' || lyrType == 'rectangle') {
						arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1).slice(1,-1)+']');
					} else if (lyrType == 'polyline') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');
					} else if (lyrType == 'circle') {arrLatLngs = $.parseJSON('['+JSON.stringify(strLatLngs).slice(1,-1)+']');intCircleRadius = e.layer.getRadius();
					} else if (lyrType == 'point') {arrLatLngs = $.parseJSON('['+strLatLngs+']');}
				} else if (_latLngs == '') {strLatLngs = '';}
				if (lyrType == 'polyline') {drawType = 'linestring';} else {drawType = lyrType;}
				$(".draw-icon").css("background-image", "url(./images/maps/icon_maps_"+drawType+"_20.png)");
				$("input[name='idxRadius']").val(intCircleRadius);
				$("#idxDrawType").val(drawType);
				$("#idxCoords").val(strLatLngs);
				if (lyrType != 'point') {
					LatlngCentroid = getCentroid(arrLatLngs);
				} else {LatlngCentroid = arrLatLngs;}
				if (LatlngCentroid != false) {
					$("input#idxMidLon").val(LatlngCentroid[0]);
					$("input#idxMidLat").val(LatlngCentroid[1]);
				}
				//return lyrType+'|'+LatlngCentroid+'|'+exportPoint;
			});

}

**Comment by cksadra** [comment]
Tanx @Falke-Design 
Fixed.
please check persian translation for update "Rotate String"
