### ISSUE TITLE
Error trying to access layer attributes with Typescript

### ISSUE THREAD

**Issue by lucas-santosP** [geoman-io/leaflet-geoman#945]
Hi, I'm trying to listen to the  `pm:create` event using **Typescript**, but when I try to access **any attribute** of the `layer` like this:
```js 
map.on("pm:create", (e) => {
  e.layer.toGeoJSON();
}
```
I got this error:
```js 
Property 'toGeoJSON' does not exist on type 'Layer'.ts(2339)
```

I tried the same code on js and works fine... So this is expected behavior because the lib doesn't have complete Typescript support yet or I'm doing something wrong?

Package versions:
```
"leaflet": "^1.7.1",
"@geoman-io/leaflet-geoman-free": "^2.11.2",
"@types/leaflet": "^1.7.3",
```

**Comment by Falke-Design** [comment]
The return type of `e.layer` is `L.Layer` and it has no function `toGeoJSON()`. So you need first to cast the `e.layer` to the correct Class. You can get this over `e.shape`:

```
map.on("pm:create", (e) => {
  if(e.shape === 'Polygon'){
     (e.layer as Polygon).toGeoJSON();
  }
}

**Comment by lucas-santosP** [comment]
> The return type of `e.layer` is `L.Layer` and it has no function `toGeoJSON()`. So you need first to cast the `e.layer` to the correct Class. You can get this over `e.shape`:
> 
> ```
> map.on("pm:create", (e) => {
>   if(e.shape === 'Polygon'){
>      (e.layer as Polygon).toGeoJSON();
>   }
> }
> ```
Alright, this works now thanks. 

But there is no documentation about how to use Typescript with the lib? 
I would prefer to use TS, but I'm thinking that will be more difficult... if you know a repo example using it would be great to take a look too.

**Comment by Falke-Design** [comment]
I created a discussions post to create a documentation of the "confusing" Typescript points #949. But there should not much of this.

@ryan-morris maybe you have example repo

**Comment by lucas-santosP** [comment]
Ok thanks. I appreciate the effort, I'll take a look and try to help if I found something.

The main question of this issue has been resolved, so I'll close it.

**Comment by ryan-morris** [comment]
@Falke-Design, @lucas-santosP  the closest I would have to an example would be [this link](https://codesandbox.io/s/zealous-dhawan-svinj?file=/src/app/app.component.ts), posted in #790 . It's a little angular specific but the geoman interactions should apply as basic typescript implementation.
