### ISSUE TITLE
How to get all boundary values of a drawn circle

### ISSUE THREAD

**Issue by chenqing8** [geoman-io/leaflet-geoman#959]
I want to know which attribute can get the boundary value of the graph, or how to get the boundary value

**Comment by Falke-Design** [comment]
You can use the `pm:create` event to catch the new drawn layer and then use `layer.getBounds()` to get the boundary.

```
// listen to when a new layer is created
map.on('pm:create', function(e) {
  console.log(e.layer.getBounds())
});
```
https://jsfiddle.net/falkedesign/Lgmfjsqk/
