### ISSUE TITLE
Can't find marker icon

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#960]
Hello:

In my React app I import as follows:
`import L, { CRS } from 'leaflet';
import '@geoman-io/leaflet-geoman-free';
import '@geoman-io/leaflet-geoman-free/dist/leaflet-geoman.css';`

A few lines down I also imported these icons, though I'm not sure if this is necessary:
`import markerIconPng from 'leaflet/dist/images/marker-icon.png';
import markerShadowPng from 'leaflet/dist/images/marker-shadow.png';`

When I click on the "Draw Marker" icon to place a marker on the map. the marker icon is not found.  I see this in the Chrome developer tools console:

![geomanMarkerIssue](https://user-images.githubusercontent.com/5943189/127877310-0c8d75ec-29b6-417b-b1c9-59cb76fb40bf.JPG)

Is there something I am missing in my code?

Thaml you.

**Comment by Falke-Design** [comment]
This is a "issue" of Leaflet Core not of Geoman.

Maybe this helps you: https://stackoverflow.com/q/47313165/8283938
