### ISSUE TITLE
Determine if there are drawings left on the map

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#961]
If the user were to click the "Remove Layers" button, then click the finish button, is there an event to register to that can be used to determine if there are any other drawings left on the map?  

Thank you.

**Comment by Falke-Design** [comment]
You can listen on the `pm:globalremovalmodetoggled` event:

```
map.on('pm:globalremovalmodetoggled', function(e) {
  console.log(e)
  if(!e.enabled){
    if(map.pm.getGeomanLayers().length > 0){
      console.log('Layers existing')
    }else{
      console.log('No layers existing')
    }
  }
});
```

pm:globalremovalmodetoggled
