### ISSUE TITLE
Marker button repeating

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#962]
In my React.js code I create a const for all of the required drawing buttons.:
`    const mapDrawBtns =  {
        Marker: 'drawMarker',
        Polygon: 'drawPolygon',
        Rectangle: 'drawRectangle',
        Line: 'drawPolyline',
    };`

When I click on the "Draw Marker" button, I can use my mouse to place a marker where I want on the map with the mouse click.  However, after the mouse click, the marker icon stays with the mouse movement indicating that I want to place another marker somewhere else.  This keeps happening until I click the Cancel button.  Given my React code, what / where do I make a setting to allow for only one placement of a marker when I click the "Draw Marker" button?

Thank you.

**Comment by Falke-Design** [comment]
You can disable the "effect" with `continueDrawing: false`:

```
map.pm.setGlobalOptions({continueDrawing: false})
```

https://jsfiddle.net/falkedesign/34ntjysv/
