### ISSUE TITLE
Drag features is not working on touch devices with leaflet 1.7.1

### ISSUE THREAD

**Issue by xylolink** [geoman-io/leaflet-geoman#970]
Hi everyone,

I discovered recently leaflet-geoman and this library is great. It's now integrated in our mapping apps developped with ReactJS.
Thanks for your examples, it's was really helpfull !

However, I have an issue concerning dragging with touch device. It works perfectly on desktop but nothing happened with mobile devices. What seemed weird to me, is that it's working well with the example of geoman.io webpage (geoman.io/geojson-editor) or with this one  https://jsfiddle.net/o1dwu2vg/ but not on this simple example : https://d2io1.csb.app/

Finally, I discovered that leaflet 1.6.0  is used in the first example. Here it works : https://zhbsw.csb.app/

Do you have any idea to solve this issue as I need to stay on leaflet 1.7.1 ?

Thanks in advance.

**Comment by Falke-Design** [comment]
I think this can be an issue of this: https://stackoverflow.com/a/65369228

**Comment by xylolink** [comment]
thanks for the answer. I went back to 1.6.0 temporary, I will test the next leaflet release.
