### ISSUE TITLE
editPolygon not in docs

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#974]
I just noticed this today, I will say there is a chance that I am not finding this in the documentation.

editPolygon is an option that, from what I see, turns on and off the "Edit Layers" button (the button whos icon is an arrow pointing to a node on a line)

This option is used in the demo.js file in the github code that can be cloned.

However, I cannot find editPolygon defined anywhere in the geoman-io documentation.  

Is this intentional?

Thank you

**Comment by Falke-Design** [comment]
`editPolygon` was replaced with `editMode` on the 2.0 release. I fix the demo, thanks for reporting.

**Comment by Falke-Design** [comment]
Fixed with Release 2.11.3
