### ISSUE TITLE
Freehand ("non straight") Polygon Draw?

### ISSUE THREAD

**Issue by gmarshall56** [geoman-io/leaflet-geoman#976]
Is there currently, or, if not, will there be a drawing option that allows for freehand drawing of polygons, meaning drawing of "non straight" polygons?

[See here for example of Leaflet FreeDraw](https://github.com/Wildhoney/Leaflet.FreeDraw)

Thank you.

**Comment by Falke-Design** [comment]
Currently it is not possible and we are not working on it, but I add this issue to the Feature Request list
Here is a example to use it with Geoman: https://github.com/geoman-io/leaflet-geoman/discussions/947
