### ISSUE TITLE
Setting maxRadiusCircle breaks some draw functionalities

### ISSUE THREAD

**Issue by eribum** [geoman-io/leaflet-geoman#983]
Hello there! 

If set a value for the maxRadiusCircle option, when drawing a circle, no HintMarker or tooltip is displayed. Also, the circle center no longer snaps. After setting the circle center on the map by clicking, everything works again.

Here is a jsFiddle where this issue can be reproduced: [https://jsfiddle.net/tc4xz6Lv/](https://jsfiddle.net/tc4xz6Lv/)

Thank you for this amazing library!
Best Regards

**Comment by Falke-Design** [comment]
Thanks for reporting, we will fix this!

**Comment by Falke-Design** [comment]
Fixed with Release 2.11.3

**Comment by Falke-Design** [comment]
Thx for checking. I didn't saw that this was a problem too, will be fixed
