### ISSUE TITLE
Cannot read property 'lng' of undefined. I use extends L.map class

### ISSUE THREAD

**Issue by DriveSoft** [geoman-io/leaflet-geoman#984]
Hello.

I am stuck with a problem.

I made a class that extends the functionality of the leaflet map for my project.

file: classLeafletMap.js
```
export class NewMap extends L.map {
...
```

file: index.html
```
import {NewMap} from '{% static 'script/classLeafletMap.js' %}';
mymap = new NewMap('mapid', { zoomControl: false });
```

plugins like "leaflet-bing-layer.js", "easy-button.js", "leaflet.markercluster-src.js" works fine,
BUT not leaflet-geoman.min.js

I just get error in leaflet-geoman.min.js
"Cannot read property 'lng' of undefined"

But if I don't use the new class NewMap to extends Leaflet functionality everything works fine.

Is it a bug or Am I doing something wrong?
I don't use webpack or react, just JS and modules.

**Comment by Falke-Design** [comment]
Is it possible to create a fiddle? https://jsfiddle.net/o1dwu2vg/

When and where comes the error "Cannot read property 'lng' of undefined"?

**Comment by DriveSoft** [comment]
Sorry to bother you, I found my mistake :)
https://jsfiddle.net/u0f3zjoe/

Unfortunately I can't find how to delete this issue.

**Comment by Falke-Design** [comment]
No problem.

You can't delete a issue, it is only possible to close it
