### ISSUE TITLE
Rectangle tool shows only three handles and won't finish on click.

### ISSUE THREAD

**Issue by renewestenberg** [geoman-io/leaflet-geoman#990]
Hi, I ran into a problem with the rectangle tool. Didn't manage to get it working on fiddle but here's a zipped folder with all code involded.
Run testbug.html and the problem reproduces.

As far as I can tell the other tools work as expected.

[testbug.zip](https://github.com/geoman-io/leaflet-geoman/files/7193756/testbug.zip)
l

**Comment by Falke-Design** [comment]
Sorry for the late replay ... I have fixed this with the PR #993.

This is happening because of your custom CRS

**Comment by renewestenberg** [comment]
No worries, I am mainly using the polygon tool. 

Happy to have been able to offer a chance to further improve this excellent tool.

cheers Rene

    On Sunday, October 3, 2021, 10:00:43 PM GMT+2, Falke Design ***@***.***> wrote:  
 
 


Sorry for the late replay ... I have fixed this with the PR #993.

This is happening because of your custom CRS

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Falke-Design** [comment]
Fixed with Release 2.11.3
