### ISSUE TITLE
The enableLayerDrag function disables the ability to drag on mouse up.

### ISSUE THREAD

**Issue by roderickn-wt** [geoman-io/leaflet-geoman#991]
I am calling enableLayerDrag on a shape layer that I want to be able to move, however when I release the mouse, the drag mode on the layer is disabled. Is there the correct functionality? Or is there a way to put a layer in drag mode until it is disabled? It would be nice to be able to just all the drag mode to function until the user is happy that the shape is dragged to the correct place.

**Comment by Falke-Design** [comment]
It should not disabled automatically ... Can you please create a sample on jsfiddle?

**Comment by roderickn-wt** [comment]
Here is a JSFiddle, but I can't see to recreate the issues as far as I can tell. https://jsfiddle.net/rodericknwt/58fgnmws/35/

the button is a toggle for the last layer that was added.

**Comment by Falke-Design** [comment]
Maybe you disable it in a listener of `pm:edit` or so. Drag will also disabled if you call `enable()` or `disable()`

**Comment by roderickn-wt** [comment]
Thank you, that was the cause incidentally.
